### PR TITLE
Prevent futex_wait from actually waiting if a concurrent waker was executed before us

### LINKED ISSUE #2223: Review Linux futex implementation for weak memory
This appears to be the smoking gun of `std::sync::mpsc` https://github.com/matklad/once_cell/pull/182 and crossbeam channel https://github.com/rust-lang/rust/issues/55005#issuecomment-1152732346 deadlocks

https://github.com/rust-lang/miri/blob/32a7580b05b1f34b19d830f4f99cf1d9f58f7a76/src/shims/unix/linux/sync.rs#L129-L148

The deadlock can be seen running this
```rust
use std::{sync::mpsc::channel, thread};

fn test() {
    let (tx1, rx1) = channel();
    let (tx2, rx2) = channel();
    let t1 = thread::spawn(move || {
        tx1.send(()).unwrap();
        rx2.recv().unwrap();
    });

    rx1.recv().unwrap();

    tx2.send(()).unwrap();

    assert!(t1.join().is_ok());
}

pub fn main() {
    for i in 0.. {
        dbg!(i);
        test();
    }
}
```

```
[src/main.rs:20] i = 0
[src/main.rs:20] i = 1
[2022-06-10T22:00:00Z TRACE miri::concurrency::weak_memory] outdated value read at /home/cbeuw/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/futex.rs:61:21: 69:22 (#0)
error: deadlock: the evaluated program deadlocked
   --> /home/cbeuw/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:250:66
    |
250 |             let ret = libc::pthread_join(self.id, ptr::null_mut());
    |                                                                  ^ the evaluated program deadlocked
    |
    = note: inside `std::sys::unix::thread::Thread::join` at /home/cbeuw/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:250:66
    = note: inside `std::thread::JoinInner::<()>::join` at /home/cbeuw/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/thread/mod.rs:1352:9
    = note: inside `std::thread::JoinHandle::<()>::join` at /home/cbeuw/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/thread/mod.rs:1485:9
note: inside `test` at src/main.rs:15:10
   --> src/main.rs:15:10
    |
15  |     assert!(t1.join().is_ok());
    |             ^^^^^^^^^
note: inside `main` at src/main.rs:21:9
   --> src/main.rs:21:9
    |
21  |         test();
    |         ^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error
```

(That TRACE line was added locally. I'll make a separate PR to add weak memory logging)

### PR DESCRIPTION
**Pull request by cbeuw**
Fixes #2223

Two SC fences were placed in `futex_wake` (after the caller has changed `addr`), and in `futex_wait` (before we read `addr`). This guarantees that `futex_wait` sees the value written to `addr` before the last `futex_wake` call, should one exists, and avoid going into sleep with no one else to wake us up.
https://github.com/rust-lang/miri/blob/ada7b72a879d79aaa06f0a2a95edd520615da1a2/src/concurrency/weak_memory.rs#L324-L326

Earlier I proposed to use `fetch_add(0)` to read the latest value in MO, though this isn't the proper way to do it and breaks aliasing: syscall caller may pass in a `*const` from a `&` and Miri complains about write to a `SharedReadOnly` location, causing this test to fail.
https://github.com/rust-lang/miri/blob/ada7b72a879d79aaa06f0a2a95edd520615da1a2/tests/pass/concurrency/linux-futex.rs#L56-L68

### CODE REVIEW

File: src/shims/unix/linux/sync.rs [hunk 1]
```diff
@@ -203,6 +205,10 @@ pub fn futex<'tcx>(
                 this.write_scalar(Scalar::from_machine_isize(-1, this), dest)?;
                 return Ok(());
             }
+            // Together with the SeqCst fence in futex_wait, this makes sure that futex_wait
+            // will see the latest value on addr which could be changed by our caller
+            // before doing the syscall.
+            this.atomic_fence(&[], AtomicFenceOp::SeqCst)?;
```
Comment (RalfJung) [inline src/shims/unix/linux/sync.rs:211]: So the issue is that previously, futex_wake didn't actually do anything on `addr`, so it was not ordered wrt other operations on `addr` -- and this extra fence here inserts it into the SeqCst order?

File: src/shims/unix/linux/sync.rs [hunk 2]
```diff
@@ -126,24 +126,26 @@ pub fn futex<'tcx>(
...
-            // FIXME: check if this should be changed when weak memory orders are added.
             let futex_val = this
                 .read_scalar_at_offset_atomic(
                     &addr.into(),
                     0,
                     this.machine.layouts.i32,
-                    AtomicReadOp::SeqCst,
+                    AtomicReadOp::Relaxed,
                 )?
                 .to_i32()?;
```
Comment (RalfJung) [inline src/shims/unix/linux/sync.rs:150]: I don't think I understand why SeqCst fence + relaxed access is more correct than SeqCst access. Both should get inserted into the total SeqCst order, no?

OTOH, I seem to remember my weak memory colleagues saying that when mixing multiple orderings on one location, SeqCst accesses become ill-behaved very quickly, and only SeqCst fences still make sense.

File: tests/pass/concurrency/linux-futex.rs [hunk 3]
```diff
@@ -206,6 +208,47 @@ fn wait_wake_bitset() {
     t.join().unwrap();
 }
 
+const FREE: i32 = 0;
+const HELD: i32 = 1;
+fn concurrent_wait_wake() {
+    static FUTEX: AtomicI32 = AtomicI32::new(0);
+    for _ in 0..100 {
```
Comment (RalfJung) [inline tests/pass/concurrency/linux-futex.rs:215]: 100 times is a lot.

What about reducing this (to make the test not take quite as long), and bumping up the preemption rate for this test?

Comment (RalfJung) [reply tests/pass/concurrency/linux-futex.rs:215]: FWIW, the test currently already [fails in the 3rd iteration](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=31134a8369681cade276e063328218ab),

File: src/shims/unix/linux/sync.rs (hunk 2 above)
Comment (RalfJung) [reply src/shims/unix/linux/sync.rs:150]: Also, if this relies on the fact that the fence+load happen atomically and cannot be preempted, please add a comment explaining that.

File: tests/pass/concurrency/linux-futex.rs (hunk 3 above)
Comment (RalfJung) [reply tests/pass/concurrency/linux-futex.rs:215]: Is this even about the preemption rate? If it is about picking 1 out of 2 entries in the store buffer, then 20 rounds make the probability of accidentally passing the test 2^-20, which seems easily good enough.

File: src/shims/unix/linux/sync.rs (hunk 1 above)
Comment (cbeuw) [reply src/shims/unix/linux/sync.rs:211]: futex wake syscall is not supposed to do anything on `addr`. The API user is supposed to change its value before invoking the wake syscall.

> When releasing the lock, a thread has to first reset the lock state to not acquired and then execute a futex operation

https://man7.org/linux/man-pages/man2/futex.2.html

File: src/shims/unix/linux/sync.rs (hunk 2 above)
Comment (RalfJung) [reply src/shims/unix/linux/sync.rs:150]: > Futex API implementations are not allowed to write to addr since it's "owned" by the user program, so I doubt it's possible to create synchronisation using addr anyway.

That is a good argument.

> It doesn't matter if there is a preemption between the fence and read. We must not preempt between the read and comparison.

The comparison is completely thread-local, so I don't understand this comment. Or do you mean that it is important that the thread be put to sleep atomically with the read?

File: src/shims/unix/linux/sync.rs (hunk 1 above)
Comment (RalfJung) [reply src/shims/unix/linux/sync.rs:211]: Okay so what is the correctness argument here for a racing wait and wake? We have two SC fences, so the thing weare allowed to do is case distinction on which fence comes first.

- In case the wake fence goes first, the wait fence will establish a happens-before to that fence, so the read in wait will definitely pick up all writes before the wake. Therefore it will not sleep and we are good.
- In case the wait fence goes first... then what? Since all of wait is atomic and cannot be preempted, we know the waiting thread will be in the futex wait set, so the waking thread will see and wake it. But this relies on all of wait (fence, read, add to wait set) being non-preemptible.

Comment (cbeuw) [reply src/shims/unix/linux/sync.rs:211]: Yes your reasoning are right for both cases. Except for that the fences don't actually establish happens-before, it's just a special property unique to SC fence (cannot be replicated with acquire/release fences):
```
T1:                                                 T2:
na = 10
X.store(42, Ordering.any)             
fence(sc)
                                                     fence(sc)
                                                     X.load(Ordering.any)
                                                     r = na // still a data race, does not happen before na = 10
``` 
The load _will_ read 42 as long as T2's fence and load are interleaved after T1's fence, but it does not establish HB with anything, though this doesn't matter for our case.

> For atomic operations A and B on an atomic object M, where A modifies M and B takes its value, if there is a memory_order_seq_cst fence X such that A is sequenced before X and B follows X in S, then B observes either the effects of A or a later modification of M in its modification order.

Comment (RalfJung) [reply src/shims/unix/linux/sync.rs:211]: Oh wow, that is wild. So it's a "definitely visible but not happens-before" edge? I have no idea how that makes any sense but it's good enough for our purposes here.

Can you please add a comment with this correctness argument to the code?

File: tests/pass/concurrency/linux-futex.rs (hunk 3 above)
Comment (RalfJung) [reply tests/pass/concurrency/linux-futex.rs]: > We do need to get the wake to run before the wait

So preemption is actually harmful? Should we set the preemption rate to 0?

File: src/shims/unix/linux/sync.rs (hunk 1 above)
Comment (RalfJung) [reply src/shims/unix/linux/sync.rs:211]: Also, just to be sure I understand -- earlier you said "It doesn't matter if there is a preemption between the fence and read", but in my correctness argument we crucially use that fence+read are atomic. So it does matter, after all?

Comment (cbeuw) [reply src/shims/unix/linux/sync.rs:242]: You are right, the fence+read also have to be atomic. I've added the correctness argument as comments

File: tests/pass/concurrency/linux-futex.rs (hunk 3 above)
Comment (cbeuw) [reply tests/pass/concurrency/linux-futex.rs]: I think leaving it as-is is fine. Having preemption also demonstrates that the critical sections inside futex syscalls are happening atomically

File: src/shims/unix/linux/sync.rs [hunk 4]
```diff
@@ -126,28 +126,61 @@ pub fn futex<'tcx>(
                 Align::from_bytes(4).unwrap(),
                 CheckInAllocMsg::MemoryAccessTest,
             )?;
+            // There may be a concurrent thread changing the value of addr
+            // and then invoking the FUTEX_WAKE syscall. It is critical that the
+            // effects of this and the other thread are correctly observed,
+            // otherwise we will deadlock.
+            //
+            // There are two scenarios to consider:
+            // 1. If we (FUTEX_WAIT) executes first, we'll push ourselves into
```
Comment (RalfJung) [inline src/shims/unix/linux/sync.rs:135]:
```suggestion
            // 1. If we (FUTEX_WAIT) execute first, we'll push ourselves into
```

File: src/shims/unix/linux/sync.rs [hunk 5]
```diff
@@ -126,28 +126,61 @@ pub fn futex<'tcx>(
...
+            //    the waiters queue and go to sleep. They (addr write & FUTEX_WAKE)
+            //    will see us in the queue and wake us up.
+            // 2. If they (addr write & FUTEX_WAKE) executes first, we must observe
```
Comment (RalfJung) [inline src/shims/unix/linux/sync.rs:138]:
```suggestion
            // 2. If they (addr write & FUTEX_WAKE) execute first, we must observe
```

File: src/shims/unix/linux/sync.rs [hunk 6]
```diff
@@ -126,28 +126,61 @@ pub fn futex<'tcx>(
...
+            //    to SeqCst fences that restricts what an atomic read placed AFTER the
+            //    fence can see. The read still has to be atomic, otherwise it's a data
+            //    race. This guarantee cannot be achieved with acquire-release fences
+            //    since they only talk about reads placed BEFORE a fence - and places
+            //    no restrictions on what the read itself can see, only that there is
+            //    a happens-before between the fences IF the read happens to see the
+            //    right value. This is useless to us, since we need the read itself
+            //    to see an up-to-date value.
+            //
+            // It is also critical that the fence, the atomic load, and the comparison
```
Comment (RalfJung) [inline src/shims/unix/linux/sync.rs:160]:
```suggestion
            // The above case distinction is valid since both FUTEX_WAIT and FUTEX_WAKE
            // contain a SeqCst fence, therefore inducting a total order between the operations.
            // It is also critical that the fence, the atomic load, and the comparison in FUTEX_WAIT
```

**Comment by RalfJung** [comment]
Thanks for fixing this nasty issue!
@bors r+
