### PR TITLE
Propagate the return code from the `start` lang item

### LINKED ISSUE #1064: Unwinding panics have wrong exit code
When a `panic=unwind` program panics in regular `rustc`, it has exit code 101. When it panics in Miri, it has exit code 0. That seems wrong, the exit code shouldn't indicate success.

@Aaron1011 why idea where the disparity might come from?

### PR DESCRIPTION
**Pull request by Aaron1011**
Fixes #1064

This ensures that we set the error code properly when a panic unwinds
past `main`.

I'm not sure what the best way to write a test for this is

### CODE REVIEW

File: src/eval.rs [hunk 1]
```diff
@@ -34,7 +34,7 @@ pub fn create_ecx<'mir, 'tcx: 'mir>(
     tcx: TyCtxt<'tcx>,
     main_id: DefId,
     config: MiriConfig,
-) -> InterpResult<'tcx, InterpCx<'mir, 'tcx, Evaluator<'tcx>>> {
+) -> InterpResult<'tcx, (InterpCx<'mir, 'tcx, Evaluator<'tcx>>, MPlaceTy<'tcx, Tag>)> {
```
Comment (RalfJung) [inline src/eval.rs]: Please expand the doc comment to explain the meaning of this return value.

File: src/eval.rs [hunk 2]
```diff
@@ -199,6 +203,7 @@ pub fn eval_main<'tcx>(tcx: TyCtxt<'tcx>, main_id: DefId, config: MiriConfig) {
             if !ignore_leaks && leaks != 0 {
                 tcx.sess.err("the evaluated program leaked memory");
             }
+            std::process::exit(return_code as i32);
```
Comment (RalfJung) [inline src/eval.rs]: Instead of calling `exit` here (and in the `InterpError::Exit` case below), IMO it would make more sense to let `eval_main` return the return code and have the caller exit.

Also, this `as` cast here could fail. At the least, please use `i32::try_from`.

Comment (RalfJung) [reply src/eval.rs]: This also broke the leak check, leading to some tests failing.

**Comment by Aaron1011** [comment]
@RalfJung: Updated

File: src/eval.rs [hunk 3]
```diff
@@ -29,12 +29,15 @@ pub struct MiriConfig {
     pub seed: Option<u64>,
 }
 
-// Used by priroda.
+/// Returns a freshly created `InterpCx`, along with an `MPlaceTy` representing
+/// the location where the return value of the `start` lang item will be
+/// written to.
+/// Used by `priroda` and `miri
```
Comment (RalfJung) [inline src/eval.rs]:
```suggestion
/// Public because this is also used by `priroda`.
```

File: src/eval.rs [hunk 4]
```diff
@@ -170,40 +173,51 @@ pub fn create_ecx<'mir, 'tcx: 'mir>(
...
-    Ok(ecx)
+    Ok((ecx, ret_ptr))
 }
 
-pub fn eval_main<'tcx>(tcx: TyCtxt<'tcx>, main_id: DefId, config: MiriConfig) {
-    let mut ecx = match create_ecx(tcx, main_id, config) {
-        Ok(ecx) => ecx,
+/// Evaluates the main function specified by `main_id`.
+/// Returns `Some(return_code)` if program executed completed.
+/// Returns `None` if an evaluation error occured
```
Comment (RalfJung) [inline src/eval.rs]:
```suggestion
/// Returns `None` if an evaluation error occured.
```
You really don't like trailing full stops, do you? ;)

File: src/eval.rs [hunk 5]
```diff
@@ -246,6 +260,8 @@ pub fn eval_main<'tcx>(tcx: TyCtxt<'tcx>, main_id: DefId, config: MiriConfig) {
                     trace!("    local {}: {:?}", i, local.value);
                 }
             }
+            // Let the reported error determine the return code
```
Comment (RalfJung) [inline src/eval.rs]:
```suggestion
            // Let the reported error determine the return code.
```

File: src/eval.rs [hunk 6]
```diff
@@ -170,40 +173,51 @@ pub fn create_ecx<'mir, 'tcx: 'mir>(
...
+        Ok(return_code) => {
             let leaks = ecx.memory.leak_report();
             // Disable the leak test on some platforms where we do not
             // correctly implement TLS destructors.
             let target_os = ecx.tcx.tcx.sess.target.target.target_os.to_lowercase();
             let ignore_leaks = target_os == "windows" || target_os == "macos";
             if !ignore_leaks && leaks != 0 {
                 tcx.sess.err("the evaluated program leaked memory");
+                // Ignore the provided return code - let the reported error
+                // determine the return code
```
Comment (RalfJung) [inline src/eval.rs]:
```suggestion
                // determine the return code.
```

**Comment by Aaron1011** [comment]
@RalfJung: Updated

**Comment by RalfJung** [comment]
Thanks!

@bors r+
