### PR TITLE
 [cargo-miri] Skip unit tests of `proc-macro` crates

### LINKED ISSUE #1660: cargo-miri builds proc-macro crate's unit tests as an executable and tries to interpret it as JSON
I tried this with today's nightly:
```bash
cargo new --lib cargo-miri-bug --vcs none
cd cargo-miri-bug
echo -e '[lib]\nproc-macro = true' >> Cargo.toml
cargo miri test
```
And it reported an error:
```
    Finished test [unoptimized + debuginfo] target(s) in 0.50s
     Running `/path/to/my/home/directory/.rustup/toolchains/nightly-2020-12-30-x86_64-unknown-linux-gnu/bin/cargo-miri /the/directory/cargo-miri-bug/target/debug/deps/cargo_miri_bug-90df6bde175539f3`
fatal error: file "/the/directory/cargo-miri-bug/target/debug/deps/cargo_miri_bug-90df6bde175539f3" contains outdated or invalid JSON; try `cargo clean`
error: test failed, to rerun pass '--lib'
```
But `cargo_miri_bug-90df6bde175539f3` is not JSON at all:
```
$ file target/debug/deps/cargo_miri_bug-90df6bde175539f3
target/debug/deps/cargo_miri_bug-90df6bde175539f3: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=a50f714aa423145427213e658d992f246548e39d, for GNU/Linux 3.2.0, with debug_info, not stripped
$ LD_LIBRARY_PATH=~/.rustup/toolchains/nightly-2020-12-30-x86_64-unknown-linux-gnu/lib target/debug/deps/cargo_miri_bug-90df6bde175539f3

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
It's an executable. I can even run it manually.

Actually I think, for unit tests, cargo-miri should build the entire `proc-macro` crate and use Miri to interpret it like normal crates, not building an executable with machine code. (That is, `cargo_miri_bug-90df6bde175539f3` *should* be a JSON file, but it's currently not.)

### PR DESCRIPTION
**Pull request by hyd-dev**
Fixes #1660.

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks for the PR! I am surprised that this works even for foreign-arch builds.

However, this seems like an ad-hoc work-around. I'd really prefer it we could make cargo-miri properly detect this situation upfront, instead of having to "change its mind" when the JSON read failed.

**Comment by hyd-dev** [comment]
> I am surprised that this works even for foreign-arch builds.

Non-host target builds originally worked (the tests are built and run for the host target). cargo-miri is not involved. This PR does not and should not change anything.

> I'd really prefer it we could make cargo-miri properly detect this situation upfront, instead of having to "change its mind" when the JSON read failed.

I [tried](https://github.com/rust-lang/miri/pull/1674) to detect this at `RUSTC_WRAPPER` level but failed. cargo-miri hooks into Cargo by `RUSTC_WRAPPER` and `CARGO_TARGET_*_RUNNER`, so currently I can't do anything at Cargo level - I can't change anything that Cargo [decided](https://github.com/rust-lang/miri/issues/1660#issuecomment-761092301) to do. I can't think of a better solution now.

File: cargo-miri/bin.rs [hunk 1]
```diff
@@ -646,14 +657,19 @@ fn phase_cargo_rustc(args: env::Args) {
...
+fn phase_cargo_runner(binary: &Path, mut binary_args: env::Args) {
     let verbose = std::env::var_os("MIRI_VERBOSE").is_some();
 
     let file = File::open(&binary)
         .unwrap_or_else(|_| show_error(format!("file {:?} not found or `cargo-miri` invoked incorrectly; please only invoke this binary through `cargo miri`", binary)));
     let file = BufReader::new(file);
-    let info: CrateRunInfo = serde_json::from_reader(file)
-        .unwrap_or_else(|_| show_error(format!("file {:?} contains outdated or invalid JSON; try `cargo clean`", binary)));
+    let info: CrateRunInfo = serde_json::from_reader(file).unwrap_or_else(|_| {
+        // FIXME: This is used to workaround that Cargo uses `CARGO_TARGET_*_RUNNER`
```
Comment (hyd-dev) [inline cargo-miri/bin.rs:667]: > However, this seems like an ad-hoc work-around. I'd really prefer it we could make cargo-miri properly detect this situation upfront, instead of having to "change its mind" when the JSON read failed.

I left this as a FIXME in this PR. If I can't resolve #1677, I can't find a way better than this to fix #1660 at this moment.

**Comment by RalfJung** [comment]
I thought about this some more, and I don't think we should go with this approach. The expectation with `cargo miri test` is that tests are run in Miri. This PR violates that expectation. I think it would be better to not execute the tests at all than to silently run them outside of Miri.

Does that make sense?

**Comment by hyd-dev** [comment]
> I thought about this some more, and I don't think we should go with this approach. The expectation with `cargo miri test` is that tests are run in Miri. This PR violates that expectation. I think it would be better to not execute the tests at all than to silently run them outside of Miri.
> 
> Does that make sense?

I think that's OK. I think people often run both `cargo test` and `cargo miri test`, so skipping these tests seems fine.

**Comment by hyd-dev** [comment]
Oops... I was trying to rename the branch. The branch name looks a bit messy now.

**Comment by hyd-dev** [comment]
This now skips these tests instead changing its mind when running them.

File: test-cargo-miri/run-test.py [hunk 2]
```diff
@@ -105,6 +105,18 @@ def test_cargo_miri_test():
...
+        "test.proc-macro-crate.stdout.ref", "test.stderr-proc-macro.ref",
+    )
+    test("`cargo miri test` (subcrate and proc-macro-crate, lib target)",
+        cargo_miri("test") + ["-p", "subcrate", "-p", "proc-macro-crate", "lib"],
+        "test.subcrate-proc-macro-crate.lib-target.stdout.ref", "test.stderr-proc-macro.ref",
+    )
+    test("`cargo miri test` (proc-macro-crate, test target)",
+        cargo_miri("test") + ["-p", "proc-macro-crate", "--test", "test"],
+        "test.proc-macro-crate.test-target.stdout.ref", "test.stderr-empty.ref",
+    )
```
Comment (hyd-dev) [inline test-cargo-miri/run-test.py:119]: I think just *skipping* unit tests does not need so many tests, but I borrowed these tests from #1677 directly.

**Comment by hyd-dev** [comment]
CI told me to pass `-Zmiri-disable-isolation`, but I got `TEST SUCCESSFUL!` locally. That's strange, but I'll pass it anyway.

**Comment by hyd-dev** [comment]
PR CI failure seems spurious: https://github.com/rust-lang/miri/runs/1723207293?check_suite_focus=true#step:8:218

File: test-cargo-miri/run-test.py (hunk 2 above)
Comment (hyd-dev) [reply test-cargo-miri/run-test.py]: I reworked the test. Hope it looks better now.

**Comment by hyd-dev** [comment]
https://github.com/rust-lang/miri/runs/1726916680#step:6:43:
```
230.81 KB / 2.06 MB [===>------------------------------] 10.92 % 64.72 KB/s 29s error: failed to unpack `rust-src-nightly/rust-src/lib/rustlib/src/rust/library/stdarch/crates/stdarch-verify/x86-intel.xml` into `master/lib/rustlib/src/rust/library/stdarch/crates/stdarch-verify/x86-intel.xml`
caused by: request or response body error: error reading a body from connection: end of file before message length reached
caused by: error reading a body from connection: end of file before message length reached
caused by: end of file before message length reached
Error: Process completed with exit code 1.
```
Network failure?
I'll try to retrigger it.

**Comment by hyd-dev** [comment]
https://github.com/rust-lang/miri/runs/1726955222#step:6:43:
```
76.69 MB / 103.84 MB [=========================>--------] 73.86 % 10.95 MB/s 2s error: failed to unpack `rustc-dev-nightly-x86_64-unknown-linux-gnu/rustc-dev/lib/rustlib/x86_64-unknown-linux-gnu/lib/librus` into `master/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-844665e24828f0f2.so`
caused by: request or response body error: error reading a body from connection: Connection reset by peer (os error 104)
caused by: error reading a body from connection: Connection reset by peer (os error 104)
caused by: Connection reset by peer (os error 104)
Error: Process completed with exit code 1.
```
Another network failure? :sob:

**Comment by hyd-dev** [comment]
https://github.com/rust-lang/miri/runs/1726967213#step:6:42:
```
44.25 MB / 109.67 MB [==============>--------------------] 40.35 % 8.84 MB/s 7s error: failed to unpack `rustc-dev-nightly-x86_64-apple-darwin/rustc-dev/lib/rustlib/x86_64-apple-darwin/lib/librustc_privacy` into `master/lib/rustlib/x86_64-apple-darwin/lib/librustc_privacy-2effdb4f4976d8ce.rlib`
caused by: request or response body error: error reading a body from connection: end of file before message length reached
caused by: error reading a body from connection: end of file before message length reached
caused by: end of file before message length reached
Error: Process completed with exit code 1.
```
What's wrong with it?

**Comment by RalfJung** [comment]
Maybe GHA has network trouble... try waiting a few hours.

File: cargo-miri/bin.rs [hunk 3]
```diff
@@ -89,31 +95,49 @@ fn has_arg_flag(name: &str) -> bool {
...
-        };
-        if !arg.starts_with(name) {
-            continue;
+struct ArgFlagValueIter<'a> {
+    args: TakeWhile<env::Args, fn(&String) -> bool>,
+    name: &'a str,
+}
+
+impl<'a> ArgFlagValueIter<'a> {
+    fn new(name: &'a str) -> Self {
```
Comment (RalfJung) [inline cargo-miri/bin.rs:104]: Please add a doc comment somewhere explaining this iterator. I think what it does is yield *all* values of a flag, if a flag occurs multiple times?

File: cargo-miri/bin.rs [hunk 4]
```diff
@@ -495,17 +520,26 @@ fn phase_cargo_miri(mut args: env::Args) {
     }
     cmd.env("RUSTC_WRAPPER", &cargo_miri_path);
 
-    // Set the runner for the current target to us as well, so we can interpret the binaries.
-    let runner_env_name = format!("CARGO_TARGET_{}_RUNNER", target.to_uppercase().replace('-', "_"));
-    cmd.env(&runner_env_name, &cargo_miri_path);
+    // Set the runners to us as well, so we can interpret the binaries or skip unit tests of
+    // `proc-macro` crates.
```
Comment (RalfJung) [inline cargo-miri/bin.rs:524]: Please extend the comment to explain why both host and target runner need to be set here.

File: cargo-miri/bin.rs [hunk 5]
```diff
@@ -568,24 +602,36 @@ fn phase_cargo_rustc(args: env::Args) {
...
+                    eprintln!("[cargo-miri rustc] writing run info to `{}`", filename.display());
+                }
+                info.store(&filename);
+                // For Windows, do the same thing again with `.exe` appended to the filename.
+                // (Need to do this here as cargo moves that "binary" to a different place before
+                // running it.)
+                info.store(&out_filename("", ".exe"));
+                return;
+            };
+        }
```
Comment (RalfJung) [inline cargo-miri/bin.rs:620]: Does this have to be a macro? I'd much prefer something closure-based, with proper types.

File: cargo-miri/bin.rs [hunk 6]
```diff
@@ -568,24 +602,36 @@ fn phase_cargo_rustc(args: env::Args) {
...
+        if target_crate {
+            // This is the binary or test crate that we want to interpret under Miri.
+            // But we cannot run it here, as cargo invoked us as a compiler -- our
+            // stdin and stdout are not like we want them.
+            // Instead of compiling, we write JSON into the output file with all the
+            // relevant command-line flags and environment variables; this is used when
+            // cargo calls us again in the CARGO_TARGET_RUNNER phase.
+            store!(CrateRunInfo::collect(args));
+        } else if ArgFlagValueIter::new("--extern").any(|krate| krate == "proc_macro") {
```
Comment (RalfJung) [inline cargo-miri/bin.rs:629]: I think instead of putting this into the same `if` arm as the "proper" runnable case, it might make more sense to make these separate conditions. Like, first `if !print && target_crate && is_runnable_crate()`, and then later `if is_runnable_crate () && ArgFlagValueIter::new("--extern").any(|krate| krate == "proc_macro")`. The two branches have barely anything in common anyway.

File: cargo-miri/bin.rs [hunk 7]
```diff
@@ -652,84 +698,93 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
     let file = File::open(&binary)
         .unwrap_or_else(|_| show_error(format!("file {:?} not found or `cargo-miri` invoked incorrectly; please only invoke this binary through `cargo miri`", binary)));
     let file = BufReader::new(file);
-    let info: CrateRunInfo = serde_json::from_reader(file)
-        .unwrap_or_else(|_| show_error(format!("file {:?} contains outdated or invalid JSON; try `cargo clean`", binary)));
```
Comment (RalfJung) [inline cargo-miri/bin.rs:656]: Please keep the separate `let`-binding; that's much more readable than the long function call in the `match` operand.

File: cargo-miri/bin.rs [hunk 8]
```diff
@@ -652,84 +698,93 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
...
+            cmd.current_dir(current_dir);
+            cmd.env("MIRI_CWD", env::current_dir().unwrap());
+
+            // Run it.
+            if verbose {
+                eprintln!("[cargo-miri runner] {:?}", cmd);
+            }
+            exec(cmd)
+        }
+        CrateRunInfo::Skip => {
```
Comment (RalfJung) [inline cargo-miri/bin.rs:782]: To avoid rightward drift, it'd be good to make this code more like
```
let info_inner = match info {
  CrateRunInfo::RunWith(inner) => inner,
  CrateRunInfo::Skip ==> {
    eprintln!(...);
    return;
  }
};
```
Then the control flow here doesn't test quite as deeply.
```

File: cargo-miri/bin.rs [hunk 9]
```diff
@@ -652,84 +698,93 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
...
+            eprintln!(
+                "Running unit tests of `proc-macro` crate is not currently supported by Miri."
```
Comment (RalfJung) [inline cargo-miri/bin.rs:784]: `CrateRunInfo::Skip` doesn't indicate that this has anything to do with proc-macros. Maybe the variant should be called something like `SkipProcMacroTest`?

File: test-cargo-miri/subcrate/Cargo.toml [hunk 10]
```diff
@@ -4,6 +4,10 @@ version = "0.1.0"
 authors = ["Miri Team"]
 edition = "2018"
 
+[lib]
+proc-macro = true
```
Comment (RalfJung) [inline test-cargo-miri/subcrate/Cargo.toml:8]: So the lib-crate being a proc-macro crate does not affect the bin-crates at all? I had no idea that's even possible.^^

File: test-cargo-miri/test.stderr-proc-macro.ref [hunk 11]
```diff
@@ -0,0 +1 @@
+Running unit tests of `proc-macro` crate is not currently supported by Miri.
```
Comment (RalfJung) [inline test-cargo-miri/test.stderr-proc-macro.ref:1]: Doesn't this mean https://github.com/rust-lang/miri/blob/master/test-cargo-miri/subcrate/test.rs is now dead code? That's not good, the code in there is testing some subtle things around working directories.

It might be better to add a new proc-macro-crate to the test workspace, instead of repurposing the existing subcrate.

Comment (RalfJung) [reply test-cargo-miri/test.stderr-proc-macro.ref:1]: Oh, wait, am I mixing up unit tests and `[[test]]` tests?

File: test-cargo-miri/subcrate/src/lib.rs [hunk 12]
```diff
@@ -0,0 +1,2 @@
+#[cfg(test)]
+compile_error!("Miri should not touch me");
```
Comment (RalfJung) [inline test-cargo-miri/subcrate/src/lib.rs:2]: Did you confirm that regular `cargo test` shows this error?

**Comment by RalfJung** [comment]
@hyd-dev @teryror just as a heads-up, your two PRs will likely conflict heavily with each other, and whoever goes last will need to resolve those conflicts. `cargo-miri` is usually not changing much, but now we have two large-ish PRs working on it at the same time... not much we can do about that I think.

File: cargo-miri/bin.rs (hunk 5 above)
Comment (hyd-dev) [reply cargo-miri/bin.rs]: I changed to a closure. I used a macro to avoid repeating `return`.

File: cargo-miri/bin.rs (hunk 8 above)
Comment (hyd-dev) [reply cargo-miri/bin.rs]: `CrateRunInfo::RunWith` is a struct variant, so changing to something like that requires either creating a tuple with tree elements or packing fields of that variant in another struct. I'm not sure which is more desirable.

File: test-cargo-miri/test.stderr-proc-macro.ref (hunk 11 above)
Comment (hyd-dev) [reply test-cargo-miri/test.stderr-proc-macro.ref:1]: It's not dead code. That output is at stdout:
https://github.com/rust-lang/miri/blob/b1a8a375175ad95303985acb6247c7098dcd775e/test-cargo-miri/test.subcrate.stdout.ref#L6
And still tested:
https://github.com/rust-lang/miri/blob/b1a8a375175ad95303985acb6247c7098dcd775e/test-cargo-miri/run-test.py#L105

File: test-cargo-miri/subcrate/src/lib.rs (hunk 12 above)
Comment (hyd-dev) [reply test-cargo-miri/subcrate/src/lib.rs:2]: Yes, it does. Should I add a test?

File: cargo-miri/bin.rs (hunk 8 above)
Comment (RalfJung) [reply cargo-miri/bin.rs]: I think I slightly prefer having a new type for this.

File: test-cargo-miri/subcrate/src/lib.rs (hunk 12 above)
Comment (RalfJung) [reply test-cargo-miri/subcrate/src/lib.rs:2]: No it's fine, thanks!

File: cargo-miri/bin.rs [hunk 13]
```diff
@@ -602,36 +604,28 @@ fn phase_cargo_rustc(args: env::Args) {
...
+        // (Need to do this here as cargo moves that "binary" to a different place before running it.)
+        info.store(&out_filename("", ".exe"));
+    };
+
+    if !print && target_crate && is_runnable_crate() {
+        store_json(CrateRunInfo::collect(args));
+        return;
+    }
+
+    if !print
```
Comment (RalfJung) [inline cargo-miri/bin.rs:623]: `--extern` existing implies `!print`, doesn't it?

Comment (hyd-dev) [reply cargo-miri/bin.rs:632]: rustc happily accepts `--extern proc_macro --print=cfg`. I'm not sure would Cargo do that, though.

File: cargo-miri/bin.rs (hunk 3 above)
Comment (hyd-dev) [reply cargo-miri/bin.rs:109]: I improved the documentation a little so please re-review it.

File: cargo-miri/bin.rs (hunk 13 above)
Comment (RalfJung) [reply cargo-miri/bin.rs:632]: Hm good point. Now I see why you made this one `if`.

We should also avoid calling `is_runnable_crate()` twice. So what about something like this?
```rust
let run_crate = !print && is_runnable_crate();
```

File: test-cargo-miri/test.stderr-proc-macro.ref (hunk 11 above)
Comment (RalfJung) [reply test-cargo-miri/test.stderr-proc-macro.ref:1]: Yeah I mixed up unit tests with integration tests.

File: cargo-miri/bin.rs (hunk 13 above)
Comment (hyd-dev) [reply cargo-miri/bin.rs:632]: > We should also avoid calling `is_runnable_crate()` twice. So what about something like this?

That's fair, but I'm nore sure if `run_crate` is a good name, as unit tests of `proc-macro` crates are skipped.
I can't think of a good name now, but I think changing the condition to `!print && !target_crate && is_runnable_crate() && ArgFlagValueIter::new("--extern").any(|krate| krate == "proc_macro")` could avoid another call to `is_runnable_crate()`. That's more complex, though.

Comment (RalfJung) [reply cargo-miri/bin.rs:632]: > but I'm not sure if run_crate is a good name, as unit tests of proc-macro crates are skipped.

Yeah... so, `runnable_crate`?

Comment (hyd-dev) [reply cargo-miri/bin.rs:632]: > Yeah... so, `runnable_crate`?

There's also `!print`. I don't know can `runnable_crate` covers that?

Comment (RalfJung) [reply cargo-miri/bin.rs:632]: Well, `print` is really a separate case. It means there's no crate to begin with, just a compiler query.

File: cargo-miri/bin.rs [hunk 14]
```diff
@@ -695,90 +707,89 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
...
-            // to rather do too little than too much.
-            for (name, val) in env {
-                if env::var_os(&name).is_none() {
-                    env::set_var(name, val);
-                }
-            }
+    let info = match info {
+        CrateRunInfo::RunWith(info) => info,
+        CrateRunInfo::SkipProcMacroTest => {
+            eprintln!("Running unit tests of `proc-macro` crate is not currently supported by Miri.");
```
Comment (RalfJung) [inline cargo-miri/bin.rs:712]:
```suggestion
            eprintln!("Running unit tests of `proc-macro` crates is not currently supported by Miri.");
```

**Comment by RalfJung** [comment]
This looks great. :) I just have a minor nit left for the error. Can you squash the commits together a bit? Then I'll merge. :)

**Comment by RalfJung** [comment]
Thank you so much @hyd-dev for digging into this and exploring various approaches, patiently re-implementing everything until you arrived at a solution that I am happy with. :-)

@bors r+

**Comment by hyd-dev** [comment]
Thanks, @RalfJung. Also I guess @teryror will need to resolve many merge conflicts... Sorry about that.

**Comment by hyd-dev** [comment]
Just realized I squashed one commit wrongly. eae95693d8ae5416cc24153a4055661116100467 does not contain the doc comment (https://github.com/rust-lang/miri/pull/1675#discussion_r563130573). Sorry.

**Comment by RalfJung** [comment]
As long as the PR overall contains the comment, it's not a big deal.
