### PR TITLE
More tests, fix issue 1643 and detect races with allocation.

### LINKED ISSUE #1643: Data race false positive on once_cell
Hi!

I am excited about the new data race detector, but, unfortunatelly, it fails on once_cell. I *think* this is a false positive -- I've managed to minimize the test case to do almost literally nothing, and commenting (or uncommenting) a no-op fn is what causes the bug. Here's the repro: https://github.com/matklad/once_cell/commit/93717d97b8cb5624a1ce50bf8e5b30235b9d9608

The test is modified from std: https://github.com/rust-lang/rust/blob/45f638bd8620592b7c50e9b483c2aa8ef9715f5d/library/std/src/sync/once/tests.rs#L17

### PR DESCRIPTION
**Pull request by JCTyblaidd**
Fixes #1643 by disabling race detection for V-Table memory, adds race detection between r/w & memory allocation, and adds more tests.

~~There is one unusual result in dealloc_read_race_stack_drop.rs, where the stack variable is read by thread 0 & thread 2 and so reports a race with thread 0, any ideas for the cause of the read on thread 0?~~ Fixed, bug with reporting the index a read race occured in correctly.

### CODE REVIEW

**Comment by JCTyblaidd** [comment]
Odd, compile-fail/data_race/read_write_race_stack.rs passes on my local machine

File: tests/compile-fail/data_race/alloc_read_race.rs [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    // order, otherwise the allocation is
+    // not visible to the other-thread to
+    // detect the race:
+    //  1. alloc
+    //  2. write
+    unsafe {
+        let j1 = spawn(move || {
+            //Concurrent allocate the memory.
+            //Uses relaxed semantics to not generate
+            //a release sequence.
```
Comment (bjorn3) [inline tests/compile-fail/data_race/alloc_read_race.rs:29]:
```suggestion
            // Concurrent allocate the memory.
            // Uses relaxed semantics to not generate
            // a release sequence.
```

File: tests/compile-fail/data_race/alloc_write_race.rs [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+    // order, otherwise the allocation is
+    // not visible to the other-thread to
+    // detect the race:
+    //  1. alloc
+    //  2. write
+    unsafe {
+        let j1 = spawn(move || {
+            //Concurrent allocate the memory.
+            //Uses relaxed semantics to not generate
+            //a release sequence.
```
Comment (bjorn3) [inline tests/compile-fail/data_race/alloc_write_race.rs:29]:
```suggestion
            // Concurrent allocate the memory.
            // Uses relaxed semantics to not generate
            // a release sequence.
```

File: tests/compile-fail/data_race/dealloc_read_race_stack.rs [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+    // not visible to the other-thread to
+    // detect the race:
+    //  1. stack-allocate
+    //  2. read
+    //  3. stack-deallocate
+    unsafe {
+        let j1 = spawn(move || {
+            //Concurrent allocate the memory.
+            //Uses relaxed semantics to not generate
+            //a release sequence.
```
Comment (bjorn3) [inline tests/compile-fail/data_race/dealloc_read_race_stack.rs:32]:
```suggestion
            // Concurrent allocate the memory.
            // Uses relaxed semantics to not generate
            // a release sequence.
```

File: tests/compile-fail/data_race/dealloc_read_race_stack_drop.rs [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+    // not visible to the other-thread to
+    // detect the race:
+    //  1. stack-allocate
+    //  2. read
+    //  3. stack-deallocate
+    unsafe {
+        let j1 = spawn(move || {
+            //Concurrent allocate the memory.
+            //Uses relaxed semantics to not generate
+            //a release sequence.
```
Comment (bjorn3) [inline tests/compile-fail/data_race/dealloc_read_race_stack_drop.rs:32]:
```suggestion
            // Concurrent allocate the memory.
            // Uses relaxed semantics to not generate
            // a release sequence.
```

File: tests/compile-fail/data_race/dealloc_write_race_stack.rs [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+    // not visible to the other-thread to
+    // detect the race:
+    //  1. stack-allocate
+    //  2. read
+    //  3. stack-deallocate
+    unsafe {
+        let j1 = spawn(move || {
+            //Concurrent allocate the memory.
+            //Uses relaxed semantics to not generate
+            //a release sequence.
```
Comment (bjorn3) [inline tests/compile-fail/data_race/dealloc_write_race_stack.rs:32]:
```suggestion
            // Concurrent allocate the memory.
            // Uses relaxed semantics to not generate
            // a release sequence.
```

File: tests/compile-fail/data_race/dealloc_write_race_stack_drop.rs [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+    // not visible to the other-thread to
+    // detect the race:
+    //  1. stack-allocate
+    //  2. read
+    //  3. stack-deallocate
+    unsafe {
+        let j1 = spawn(move || {
+            //Concurrent allocate the memory.
+            //Uses relaxed semantics to not generate
+            //a release sequence.
```
Comment (bjorn3) [inline tests/compile-fail/data_race/dealloc_write_race_stack_drop.rs:32]:
```suggestion
            // Concurrent allocate the memory.
            // Uses relaxed semantics to not generate
            // a release sequence.
```

File: tests/compile-fail/data_race/read_write_race_stack.rs [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+    //  1. stack-allocate
+    //  2. atomic_store
+    //  3. atomic_load
+    //  4. write-value
+    //  5. read-value
+    unsafe {
+        let j1 = spawn(move || {
+            //Concurrent allocate the memory.
+            //Uses relaxed semantics to not generate
+            //a release sequence.
```
Comment (bjorn3) [inline tests/compile-fail/data_race/read_write_race_stack.rs:34]:
```suggestion
            // Concurrent allocate the memory.
            // Uses relaxed semantics to not generate
            // a release sequence.
```

File: tests/compile-fail/data_race/write_write_race_stack.rs [hunk 8]
```diff
@@ -0,0 +1,57 @@
...
+    //  1. stack-allocate
+    //  2. atomic_store
+    //  3. atomic_load
+    //  4. write-value
+    //  5. write-value
+    unsafe {
+        let j1 = spawn(move || {
+            //Concurrent allocate the memory.
+            //Uses relaxed semantics to not generate
+            //a release sequence.
```
Comment (bjorn3) [inline tests/compile-fail/data_race/write_write_race_stack.rs:34]:
```suggestion
            // Concurrent allocate the memory.
            // Uses relaxed semantics to not generate
            // a release sequence.
```

File: src/data_race.rs [hunk 9]
```diff
@@ -646,16 +671,26 @@ pub struct VClockAlloc {
...
 
-    // Pointer to global state.
+    /// Pointer to global state.
     global: MemoryExtra,
 }
 
 impl VClockAlloc {
-    /// Create a new data-race allocation detector.
-    pub fn new_allocation(global: &MemoryExtra, len: Size) -> VClockAlloc {
+
```
Comment (bjorn3) [inline src/data_race.rs:679]:
```suggestion
```

File: src/data_race.rs [hunk 10]
```diff
@@ -215,20 +239,19 @@ struct MemoryCellClocks {
     atomic_ops: Option<Box<AtomicMemoryCellClocks>>,
 }
 
-/// Create a default memory cell clocks instance
-/// for uninitialized memory.
-impl Default for MemoryCellClocks {
-    fn default() -> Self {
+impl MemoryCellClocks {
+
```
Comment (bjorn3) [inline src/data_race.rs:243]:
```suggestion
```

**Review by bjorn3 — COMMENTED** [review]
A few nits

**Comment by JCTyblaidd** [comment]
Looked through the log & ran ci.sh locally:

It seems to fail if -Z mir-opt-level=3 is passed as a compiler flag, so mir-opt might be making the behaviour defined and causing the test to fail.

All the tests pass for this:
```
## Running compile-fail tests in tests/compile-fail against miri for target x86_64-unknown-linux-gnu
   Compiler flags: --edition 2018 -Dwarnings -Dunused --sysroot /home/james/.cache/miri/HOST
```
But the test fails for this:
```
## Running compile-fail tests in tests/compile-fail against miri for target x86_64-unknown-linux-gnu
   Compiler flags: --edition 2018 -Dwarnings -Dunused --sysroot /home/james/.cache/miri/HOST -Z mir-opt-level=3
```

File: tests/compile-fail/data_race/read_write_race_stack.rs [hunk 11]
```diff
@@ -40,8 +40,9 @@ pub fn main() {
             
             sleep(Duration::from_millis(1000));
 
-            //read
-            stack_var //~ ERROR Data race detected between Read on Thread(id = 1) and Write on Thread(id = 2)
+            // Read, the add 1 fixes -Z mir-opt-level=3 from removing the read via dest-prop and breaking
+            // the test.
+            stack_var + 1 //~ ERROR Data race detected between Read on Thread(id = 1) and Write on Thread(id = 2)
```
Comment (oli-obk) [inline tests/compile-fail/data_race/read_write_race_stack.rs:45]: you can also change the mir-opt-level in the `compile-flags` comment at the top of the file.

File: src/data_race.rs [hunk 12]
```diff
@@ -646,22 +670,32 @@ pub struct VClockAlloc {
...
 impl VClockAlloc {
-    /// Create a new data-race allocation detector.
-    pub fn new_allocation(global: &MemoryExtra, len: Size) -> VClockAlloc {
+    /// Create a new data-race detector for newly allocated memory.
+    pub fn new_allocation(global: &MemoryExtra, len: Size, track_alloc: bool) -> VClockAlloc {
+        let (alloc_timestamp, alloc_index) = if track_alloc {
+            let (alloc_index, clocks) = global.current_thread_state();
+            let alloc_timestamp = clocks.clock[alloc_index];
+            (alloc_timestamp, alloc_index)
+        }else{
```
Comment (RalfJung) [inline src/data_race.rs:684]:
```suggestion
        } else {
```

File: src/data_race.rs [hunk 13]
```diff
@@ -646,22 +670,32 @@ pub struct VClockAlloc {
...
+            alloc_ranges: RefCell::new(RangeMap::new(
+                len, MemoryCellClocks::new(alloc_timestamp, alloc_index)
+            )),
         }
     }
 
     // Find an index, if one exists where the value
     // in `l` is greater than the value in `r`.
     fn find_gt_index(l: &VClock, r: &VClock) -> Option<VectorIdx> {
+        log::info!("Find index where not {:?} <= {:?}", l, r);
```
Comment (RalfJung) [inline src/data_race.rs:698]: This seems a bit too verbose for `info!`... would `trace!` work?

File: src/data_race.rs [hunk 14]
```diff
@@ -1134,6 +1168,8 @@ impl GlobalState {
             vector_info.push(thread)
         };
 
+        log::info!("Creating thread = {:?} with vector index = {:?}", thread, created_index);
```
Comment (RalfJung) [inline src/data_race.rs:1171]: Same here for verbosity.

File: src/machine.rs [hunk 15]
```diff
@@ -478,7 +478,24 @@ impl<'mir, 'tcx> Machine<'mir, 'tcx> for Evaluator<'mir, 'tcx> {
                 (None, Tag::Untagged)
             };
         let race_alloc = if let Some(data_race) = &memory_extra.data_race {
-            Some(data_race::AllocExtra::new_allocation(&data_race, alloc.size))
+            match kind {
+                // V-Table generation is lazy and so racy, so do not track races.
+                // Also V-Tables are read only so no data races can be detected.
```
Comment (RalfJung) [inline src/machine.rs:483]:
```suggestion
                // Also V-Tables are read only so no data races can occur.
```

Comment (RalfJung) [reply src/machine.rs:483]: Also please explain that vtables are different from other global memory because we use interpreter writes to initialize them -- it's those writes that cause the race detector to fire.

File: tests/compile-fail/data_race/alloc_read_race.rs [hunk 16]
```diff
@@ -0,0 +1,47 @@
...
+            // Uses relaxed semantics to not generate
+            // a release sequence.
+            let pointer = &*ptr.0;
+            pointer.store(Box::into_raw(Box::new(0usize)), Ordering::Relaxed);
+        });
+
+        let j2 = spawn(move || {
+            let pointer = &*ptr.0;
+
+            //Note detects with write due to the initialization of memory
```
Comment (RalfJung) [inline tests/compile-fail/data_race/alloc_read_race.rs:37]: I don't understand this comment.

File: tests/compile-fail/data_race/dangling_thread_race.rs [hunk 17]
```diff
@@ -26,7 +26,7 @@ fn main() {
 
     // Detatch the thread and sleep until it terminates
     mem::drop(join);
-    sleep(Duration::from_millis(100));
+    sleep(Duration::from_millis(1000));
```
Comment (RalfJung) [inline tests/compile-fail/data_race/dangling_thread_race.rs:29]: That's a lot of waiting; does 500ms work?

File: src/data_race.rs [hunk 18]
```diff
@@ -192,6 +192,25 @@ struct AtomicMemoryCellClocks {
...
 
+#[derive(Copy, Clone, PartialEq, Eq, Debug)]
+enum WriteType {
+    /// Allocate memory.
+    Allocate,
+    /// Standard unsynchronized write.
+    Write,
+    /// Deallocate memory
+    Deallocate,
+}
```
Comment (RalfJung) [inline src/data_race.rs:203]: To make sure that I understand this correctly... if it's the dealloc happening first, there won't be a race reported but an out-of-bounds access, right? It's only when the read is first, and then a dealloc follows, but it is not synchronized, *then* a race is reported? And same for allocations? I think this would be worth documenting somewhere.

Also, this is a further deviation from the paper, right? So please add it to the list of "differences from the paper" at the top of this file.

File: tests/compile-fail/data_race/write_write_race_stack.rs [hunk 19]
```diff
@@ -0,0 +1,57 @@
+// ignore-windows: Concurrency on Windows is not supported yet.
+// compile-flags: -Zmiri-disable-isolation
```
Comment (RalfJung) [inline tests/compile-fail/data_race/write_write_race_stack.rs:2]: Why is isolation being disabled here?

File: tests/compile-fail/data_race/dangling_thread_race.rs [hunk 20]
```diff
@@ -26,7 +26,7 @@ fn main() {
 
     // Detatch the thread and sleep until it terminates
```
Comment (bjorn3) [inline tests/compile-fail/data_race/dangling_thread_race.rs:27]:
```suggestion
    // Detach the thread and sleep until it terminates
```
typo

File: tests/compile-fail/data_race/write_write_race_stack.rs (hunk 19 above)
Comment (RalfJung) [reply tests/compile-fail/data_race/write_write_race_stack.rs:2]: Ah, it's sleeping.

File: tests/compile-fail/data_race/release_seq_race.rs [hunk 21]
```diff
@@ -40,9 +40,9 @@ pub fn main() {
         });
 
         let j3 = spawn(move || {
-            sleep(Duration::from_millis(1000));
+            sleep(Duration::from_millis(5000));
```
Comment (RalfJung) [inline tests/compile-fail/data_race/release_seq_race.rs:43]: 5 seconds seems rather excessive. I'd like to avoid having tests run too long. Is there something taht can be dine to avoid this?

File: tests/compile-fail/data_race/read_write_race_stack.rs [hunk 22]
```diff
@@ -0,0 +1,54 @@
+// ignore-windows: Concurrency on Windows is not supported yet.
+// compile-flags: -Zmiri-disable-isolation -Zmir-opt-level=0
```
Comment (RalfJung) [inline tests/compile-fail/data_race/read_write_race_stack.rs:2]: Please add a comment explaining why you set the opt-level to 0.

**Comment by RalfJung** [comment]
I wonder if there is a way to make the vtable init writes occur at timestamp 0? That would avoid having to disable the race detector for vtables.

File: tests/compile-fail/data_race/release_seq_race.rs (hunk 21 above)
Comment (JCTyblaidd) [reply tests/compile-fail/data_race/release_seq_race.rs]: The change was from when I was trying to debug the CI failure that I forgot to revert, i have rolled back to more reasonable values.

**Comment by JCTyblaidd** [comment]
The v-tables are marked as immutable so we could just disable the data-race detector for any immutable memory instead of switching on memory type, assuming the memory is never marked mutable again. The alternative is to again expose some state of method that results in the internal switch on data-race detection being temporarily disabled similarly to atomic read/writes internally.

Though the issue doesn't seem to occur for the caller_location memory since it seems to allocate new memory each time it is invoked, which i think exposes different behaviour to rustc:

```
use std::panic::Location;

fn location() -> &'static Location<'static> {
    Location::caller()
}

fn main() {
    let a = location() as *const _;
    let b = location() as *const _;
    /// Passes on rustc & fails on miri
    assert_eq!(a,b);
}
```

I would assume both v-tables and caller location memory should be treated similarly as immutable statics initialized at timestamp 0.

File: src/data_race.rs [hunk 23]
```diff
@@ -192,13 +195,22 @@ struct AtomicMemoryCellClocks {
...
     Allocate,
+
     /// Standard unsynchronized write.
     Write,
-    /// Deallocate memory
+
+    /// Deallocate memory.
+    /// Some races with deallocation will be missed and instead
+    /// reported as invalid accesses of freed memory due to
+    /// the order of checks.
```
Comment (RalfJung) [inline src/data_race.rs:213]:
```suggestion
    /// Note that when memory is deallocated first, later non-atomic accesses
    /// will be reported as use-after-free, not as data races.
    /// (Same for `Allocate` above.)
```

**Comment by RalfJung** [comment]
> Though the issue doesn't seem to occur for the caller_location memory since it seems to allocate new memory each time it is invoked, which i think exposes different behaviour to rustc

Note that even for vtables, Miri behavior differs from rustc -- rustc will duplicate vtables when they are used in multiple codegen units, while Miri entirely deduplicates them.

> The alternative is to again expose some state of method that results in the internal switch on data-race detection being temporarily disabled similarly to atomic read/writes internally.

The write accesses that initialize the vtable are fine, right?
Could we have a method which takes an `AllocId` (or a `Pointer`+`Size`) and reset all clocks in that memory region to 0? That could then be called after Miri is done lazily initializing the vtable. (Caller locations don't need it I think since they are not shared.)

**Comment by JCTyblaidd** [comment]
```
The write accesses that initialize the vtable are fine, right?
Could we have a method which takes an AllocId (or a Pointer+Size) and reset all clocks in that memory region to 0? That could then be called after Miri is done lazily initializing the vtable
```

Yes this would work and should be easy to add, how do you think this method should be exposed to the v-table initialization code, extra method in Machine?

**Comment by RalfJung** [comment]
> Yes this would work and should be easy to add, how do you think this method should be exposed to the v-table initialization code, extra method in Machine?

Hm, I have not thought about this... yeah a new machine method makes sense. It could be called something like `after_static_mem_initialized` or so.

File: src/machine.rs [hunk 24]
```diff
@@ -478,7 +478,27 @@ impl<'mir, 'tcx> Machine<'mir, 'tcx> for Evaluator<'mir, 'tcx> {
                 (None, Tag::Untagged)
             };
         let race_alloc = if let Some(data_race) = &memory_extra.data_race {
-            Some(data_race::AllocExtra::new_allocation(&data_race, alloc.size))
+            match kind {
```
Comment (RalfJung) [inline src/machine.rs:481]: The `machine` file is meant to mostly be doing some gluing. This here is some proper "business logic". Could you move this inside the `data_race::AllocExtra::new_allocation` constructor?

**Comment by JCTyblaidd** [comment]
Reworked to use machine hook to reset data_race state - requires https://github.com/rust-lang/rust/pull/79942 or similar.

File: src/data_race.rs [hunk 25]
```diff
@@ -681,7 +760,7 @@ impl VClockAlloc {
                         .enumerate()
                         .find_map(|(idx, &r)| if r == 0 { None } else { Some(idx) })
                         .expect("Invalid VClock Invariant");
-                    Some(idx)
+                    Some(idx + r_slice.len())
```
Comment (RalfJung) [inline src/data_race.rs:763]: Is this a bugfix, or what does this do?

Comment (JCTyblaidd) [reply src/data_race.rs:763]: Bugfix, would return the incorrect vector index as the source of the data-race for VClocks with different sizes.

a race between [1,2] and [1] would return that the race was with index 0 instead of 1.

Comment (RalfJung) [reply src/data_race.rs:763]: Okay, thanks. Is there a test ensuring that this will not regress?

Comment (JCTyblaidd) [reply src/data_race.rs:763]: Yes, i added all thread ids to the tests instead of matching on just //~ERROR data race.

The test dealloc_read_race_stack_drop.rs has this case occur and covers the bug by requiring explicit matching on
```
//~ ERROR Data race detected between Deallocate on Thread(id = 1) and Read on Thread(id = 2)
```
whereas with the bug it would return:
```
//~ ERROR Data race detected between Deallocate on Thread(id = 1) and Read on Thread(id = 0, name = "main") 
```

Comment (RalfJung) [reply src/data_race.rs:763]: Okay, awesome. :)

**Comment by RalfJung** [comment]
@JCTyblaidd thanks for the fix and even adjust rustc for this!
@bors r+
