### PR TITLE
Abort instead of panic on asserting intrinsics

### LINKED ISSUE #1222: Abort in "assert_*" intrinsics
[These three intrinsics](https://github.com/rust-lang/miri/blob/704228d0bb65227c82a8b44ab819485912b44007/src/shims/intrinsics.rs#L447-L449) should, IMO, abort instead of panic. The main reason we make them panic in rustc is that we want a good backtrace, and doing that from codegen is hard. But causing a panic is easy thanks to libcore having panic support, and std hooking into it.

But in Miri, we can show great backtraces on abort! So, there is no reason to use panics IMO. So I propose that we extend this with an abort message:
https://github.com/rust-lang/miri/blob/704228d0bb65227c82a8b44ab819485912b44007/src/eval.rs#L56
and then cause an abort from the intrinsic.

@elichai that they would look into this.

### PR DESCRIPTION
**Pull request by elichai**
This fixes #1222 
replacing the panic with an abort and a corresponding message.
the stack trace is already printed, this just adds an optional message the caller can pass, and I just pass the same message we passed to the panic but now to the abort instead.

r? @RalfJung

### CODE REVIEW

File: src/machine.rs [hunk 1]
```diff
@@ -272,8 +272,8 @@ impl<'mir, 'tcx> Machine<'mir, 'tcx> for Evaluator<'tcx> {
     }
 
     #[inline(always)]
-    fn abort(_ecx: &mut InterpCx<'mir, 'tcx, Self>) -> InterpResult<'tcx, !> {
-        throw_machine_stop!(TerminationInfo::Abort)
+    fn abort(_ecx: &mut InterpCx<'mir, 'tcx, Self>, msg: Option<String>) -> InterpResult<'tcx, !> {
+        throw_machine_stop!(TerminationInfo::Abort(msg.unwrap_or_default()))
```
Comment (RalfJung) [inline src/machine.rs]: This will look really odd when there is no message:
```
the evaluated program aborted execution: 
```
I suggest to make `TerminationInfo::Abort` take `Option<String>`, and then just throw with `None` here.

File: src/shims/intrinsics.rs [hunk 2]
```diff
@@ -440,15 +441,15 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
             "assert_uninit_valid" => {
                 let ty = substs.type_at(0);
                 let layout = this.layout_of(ty)?;
-                // Return here because we panicked instead of returning normally from the intrinsic.
+                // Abort here because the caller might not be panic safe.
                 if layout.abi.is_uninhabited() {
-                    return this.start_panic(&format!("attempted to instantiate uninhabited type `{}`", ty), unwind);
+                    Machine::abort(this, Some(format!("attempted to instantiate uninhabited type `{}`", ty)))?;
```
Comment (RalfJung) [inline src/shims/intrinsics.rs]: You can just use `throw_machine_stop!` here, to avoid having to change `Machine::abort`.

File: tests/compile-fail/inhabited_type.rs [hunk 3]
```diff
@@ -0,0 +1,7 @@
+ // error-pattern: the evaluated program aborted
```
Comment (RalfJung) [inline tests/compile-fail/inhabited_type.rs]: The test name is odd. What about "uninit_uninhabited_type"?

Also, please check here that the "attempted to instantiate uninhabited type" is part of the message.

Comment (elichai) [reply tests/compile-fail/inhabited_type.rs]: you're right. was weird for me too, choose it because the intrinsic is called `assert_inhabited` so I choose inhabited even though uninhabited/uninhabitable sounds better. will change.

File: src/machine.rs (hunk 1 above)
Comment (elichai) [reply src/machine.rs]: hmm, and then print `Some("attempted to...")` when there's an error?

also, if I replace to `throw_machine_stop!` I'll avoid touching this function.
although I think it will also be nice for const-eval in the future

Comment (RalfJung) [reply src/machine.rs]: With a message, just add the `: ` and then the error message.

> although I think it will also be nice for const-eval in the future

Then we can change it in the future, if it really turns out to be useful. Let's avoid adding API surface now that will bitrot and remain unused.

File: src/diagnostics.rs [hunk 4]
```diff
@@ -20,7 +20,12 @@ pub fn report_diagnostic<'tcx, 'mir>(
             let info = info.downcast_ref::<TerminationInfo>().expect("invalid MachineStop payload");
             match info {
                 TerminationInfo::Exit(code) => return Some(*code),
-                TerminationInfo::Abort => format!("the evaluated program aborted execution"),
+                TerminationInfo::Abort(opt_msg) =>
+                    if let Some(msg) = opt_msg {
+                        format!("the evaluated program aborted execution: {}", msg)
+                    } else {
+                        format!("the evaluated program aborted execution")
+                    },
```
Comment (elichai) [inline src/diagnostics.rs]: `the evaluated program aborted execution: None` and `the evaluated program aborted execution: Some("attempted...")` looked really weird. so I just conditionally formats it.

Could also be done like: `format!("the evaluated program aborted execution: {}", msg.as_ref().map(|m|format!(": {}", m).unwrap_or_default()))` but I think the simpler if let is more readable even if it duplicates the string

File: src/diagnostics.rs [hunk 5]
```diff
@@ -20,7 +20,12 @@ pub fn report_diagnostic<'tcx, 'mir>(
             let info = info.downcast_ref::<TerminationInfo>().expect("invalid MachineStop payload");
             match info {
                 TerminationInfo::Exit(code) => return Some(*code),
-                TerminationInfo::Abort => format!("the evaluated program aborted execution"),
+                TerminationInfo::Abort(opt_msg) =>
+                    if let Some(msg) = opt_msg {
```
Comment (RalfJung) [inline src/diagnostics.rs]: You can fold the inner `if let` into the outer `match`:
```
TerminationInfo::Abort(Some(msg)) =>
TerminationInfo::Abort(None) =>
```

**Comment by RalfJung** [comment]
I added your original message to say "fixes #1222" (not "solves") so that GH will close that issue automatically when the PR gets merged.

File: src/diagnostics.rs (hunk 4 above)
Comment (RalfJung) [reply src/diagnostics.rs]: > the evaluated program aborted execution: None and the evaluated program aborted execution: Some("attempted...") looked really weird. so I just conditionally formats it.

Yes, debug-printing the `Option` clearly makes no sense. :)

File: src/diagnostics.rs (hunk 5 above)
Comment (elichai) [reply src/diagnostics.rs]: Nice. forgot this was even a thing :)

**Comment by RalfJung** [comment]
Looking good, thanks. :)
@bors r+
