### PR TITLE
Handle `read`s on STDIN

### LINKED ISSUE #1434: stdin cannot be read
I tried to run my stdin reading program yesterday with miri 0.1.0 (10419b3 2020-05-11) and rustc 1.45.0-nightly (a74d1862d 2020-05-14) but upon reading the stdin `Ok(0)` seems to be always returned at least on Linux.

Example:

```
use std::io::Read;

fn main() {
    let mut bytes = [0u8; 8192];
    let total = std::io::stdin().lock().read(&mut bytes[..]).unwrap();
    println!("{}", total);
}
```

With stable `echo foo | cargo run` prints 4.
With miri `echo foo | cargo +nightly miri run -- -Zmiri-disable-isolation` prints 0. Same for reading in a loop.

Looking at `src/shims/foreign_items/posix.rs` and `src/shims/fs.rs` I can't at least see any relevant TODO's or other notes which would suggest this should not work.

Could this be because `src/bin/cargo-miri.rs` launches a subprocess and somehow the stdin does not get inherited?

### PR DESCRIPTION
**Pull request by samrat**
Closes #1434

### CODE REVIEW

File: src/shims/foreign_items/posix.rs [hunk 1]
```diff
@@ -66,7 +66,18 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
                 let buf = this.read_scalar(buf)?.not_undef()?;
                 let count = this.read_scalar(count)?.to_machine_usize(this)?;
                 let result = if fd == 0 {
-                    throw_unsup_format!("reading from stdin is not implemented")
+                    use std::io::{self, Read};
+
+                    let mut buffer = String::new();
+                    let res = io::stdin().read_to_string(&mut buffer);
```
Comment (RalfJung) [inline src/shims/foreign_items/posix.rs:72]: This does not look right -- you should somehow be taking `count` into account, or you might be reading more than fits the target buffer.

File: src/shims/foreign_items/posix.rs [hunk 2]
```diff
@@ -66,7 +66,18 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
...
+
+                    match res {
+                        Ok(bytes) => {
+                            this.memory.write_bytes(buf, buffer.bytes())?;
+                            i64::try_from(bytes).unwrap()
+                        },
+                        Err(_) => -1,
```
Comment (RalfJung) [inline src/shims/foreign_items/posix.rs:79]: When returning "-1", we have to set errno to an appropriate error... but I realize the stdout code also does not do that. So maybe add a FIXME in both places so we don't forget to do this eventually?

File: src/shims/foreign_items/posix.rs (hunk 1 above)
Comment (RalfJung) [reply src/shims/foreign_items/posix.rs:72]: Your `write_bytes` could cause memory corruption in the interpreted program because you are writing beyond the bounds of the buffer you were given.

Another problem here is that `read_to_string` will fail on non-UTF-8 data. We are working with raw bytes here, so the right type to use is `Vec<u8>`.

Comment (RalfJung) [reply src/shims/foreign_items/posix.rs:72]: You can use the `read` function in `fs.rs` for inspiration.

File: src/shims/foreign_items/posix.rs [hunk 3]
```diff
@@ -66,7 +66,18 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
                 let buf = this.read_scalar(buf)?.not_undef()?;
                 let count = this.read_scalar(count)?.to_machine_usize(this)?;
                 let result = if fd == 0 {
-                    throw_unsup_format!("reading from stdin is not implemented")
+                    use std::io::{self, Read};
```
Comment (RalfJung) [inline src/shims/foreign_items/posix.rs:69]: Since reading from stdin can break non-determinism, please add a call to `this.check_no_isolation`.

**Comment by RalfJung** [comment]
@samrat FYI, this PR has some feedback for you to address. :)  No rush though, just making sure it does not get lost.

**Comment by RalfJung** [comment]
@samrat what is the status here? Do you still plan to work on this?

**Comment by samrat** [comment]
@RalfJung Apologies for the lack of updates here, and for the delay. I'll try to work on it this weekend and address the feedback on the PR.

**Comment by RalfJung** [comment]
No need to rush, I'd just like to close this PR and give other contributors a chance in case you decide to not work on this for the foreseeable future. :) But

File: src/shims/posix/foreign_items.rs [hunk 4]
```diff
@@ -67,7 +67,25 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
                 let buf = this.read_scalar(buf)?.not_undef()?;
                 let count = this.read_scalar(count)?.to_machine_usize(this)?;
                 let result = if fd == 0 {
-                    throw_unsup_format!("reading from stdin is not implemented")
+                    use std::io::{self, Read};
```
Comment (RalfJung) [inline src/shims/posix/foreign_items.rs:70]: Please add this at the top of the file, we usually avoid local imports.

File: src/shims/posix/foreign_items.rs [hunk 5]
```diff
@@ -67,7 +67,25 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
...
+
+                    this.check_no_isolation("read")?;
+
+                    let mut buffer = vec![0; count as usize];
```
Comment (RalfJung) [inline src/shims/posix/foreign_items.rs:74]: `as` casts are always suspicious. Why can this not be bigger than a host usize?
This is what the `read` for files does:
```rust
// We cap the number of read bytes to the largest value that we are able to fit in both the
// host's and target's `isize`. This saves us from having to handle overflows later.
let count = count.min(this.machine_isize_max() as u64).min(isize::MAX as u64);
```

File: src/shims/posix/foreign_items.rs [hunk 6]
```diff
@@ -67,7 +67,25 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
...
+                        // `Stdin::read` never returns a value larger
+                        // than `count`, so this cannot fail.
+                        .map(|c| i64::try_from(c).unwrap());
+
+                    match res {
+                        Ok(bytes) => {
+                            this.memory.write_bytes(buf, buffer)?;
+                            i64::try_from(bytes).unwrap()
+                        },
+                        // FIXME: set errno to appropriate value
```
Comment (RalfJung) [inline src/shims/posix/foreign_items.rs:86]: Setting the errno is easy:
```rust
                Err(e) => {
                    this.set_last_error_from_io_error(e)?;
                    Ok(-1)
                }
```

**Comment by RalfJung** [comment]
Does anyone reading along have an idea for how to properly test this?

**Comment by samrat** [comment]
@RalfJung I've addressed your comments. 

This does introduce some duplication with `read`, so I attempted factoring out the common parts into a method that takes `impl Read` and so can read both `File`'s and `Stdin`: https://github.com/samrat/miri/commit/3b9c8d3cd13bf3ad6a4badbc90ab3bc880d6dba2#diff-560909e2fdd6fac0fb0b832d9470ac7cR438. Currently, I'm not sure how to resolve a multiple mutable borrows type error that results with this approach.

Do you think this approach is workable?

File: src/shims/posix/foreign_items.rs [hunk 7]
```diff
@@ -67,10 +69,23 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
...
                     this.check_no_isolation("read")?;
 
+                    // We cap the number of read bytes to the largest
+                    // value that we are able to fit in both the
+                    // host's and target's `isize`. This saves us from
+                    // having to handle overflows later.
+                    let count = count.min(this.machine_isize_max() as u64).min(isize::MAX as u64);
+                    // This can never fail because `count` was capped
+                    // to be smaller than `isize::MAX`.
+                    let count = isize::try_from(count).unwrap();
```
Comment (RalfJung) [inline src/shims/posix/foreign_items.rs:82]: This is unnecessary (and I recently removed it from `fs.rs`).

**Comment by RalfJung** [comment]
> This does introduce some duplication with read

True. Let's go with this for the PR though, and do refactoring later.
IMO the proper fix here is to handle FDs 1-3 in `fs.rs` together with the rest of them.

File: src/shims/posix/foreign_items.rs [hunk 8]
```diff
@@ -11,6 +12,7 @@ use shims::posix::fs::EvalContextExt as _;
 use shims::posix::sync::EvalContextExt as _;
 use shims::posix::thread::EvalContextExt as _;
 
+
```
Comment (RalfJung) [inline src/shims/posix/foreign_items.rs:15]: Spurious new newline.

**Comment by RalfJung** [comment]
Thanks. :)
@bors r+

**Comment by RalfJung** [comment]
For the `read` refactoring, if you want to work on that, could you open an issue? I am on vacation now, but I can write up mentoring instructions in about a week or so when I am back.
