### PR TITLE
Stop parsing ui_test annotations in `run-dep` mode

### LINKED ISSUE #2967: `./miri run-dep` parses ui-test comments
Title says it all: running `./miri run-dep` shouldn't care about whether the ui-test comments in the file make sense, they should just all be ignored. But currently when working on a test I am getting errors like

```
$ ./miri run-dep tests/fail/shims/memcpy_zero.rs
    Finished dev [optimized + debuginfo] target(s) in 0.01s
    Finished dev [optimized + debuginfo] target(s) in 0.01s
     Running `target/debug/cargo-miri miri setup --print-sysroot`
    Finished test [optimized + debuginfo] target(s) in 0.02s
     Running tests/compiletest.rs (target/debug/deps/compiletest-abb37bc11260f53d)
   Building test dependencies...
Error: 
   0: [
          InvalidComment {
              msg: "no pattern specified",
              line: 9,
          },
      ]

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
error: test failed, to rerun pass `--test compiletest`
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #2967

### CODE REVIEW

File: tests/compiletest.rs [hunk 1]
```diff
@@ -274,10 +274,16 @@ fn main() -> Result<()> {
...
-    config.program.args.push("always".into());
-    let mut cmd = ui_test::test_command(config, Path::new(&path))?;
+    let mut cmd = config.program.build(&config.out_dir);
+
+    cmd.arg("--color").arg("always");
+    cmd.arg(path);
+
+    if let Some(edition) = config.edition {
+        cmd.arg("--edition").arg(edition);
+    }
```
Comment (RalfJung) [inline tests/compiletest.rs:286]: Does this mean `./miri run-dep`  defaults to edition 2021? Should we make `./miri run` also add `--edition 2021`?

Comment (oli-obk) [reply tests/compiletest.rs:286]: probably 😆 Seems like a good default to have

Comment (oli-obk) [reply tests/compiletest.rs:286]: But it's then hard to overwrite... so maybe let's just remove it from run-dep

Comment (RalfJung) [reply tests/compiletest.rs]: Will `./miri run-dep file.rs --edition 2021` work?

Comment (oli-obk) [reply tests/compiletest.rs]: It works now 😁 I tested that the behaviour around `--` is now the same as with `./miri run`.

File: tests/compiletest.rs [hunk 2]
```diff
@@ -274,13 +274,20 @@ fn main() -> Result<()> {
...
+            config.program.args.push(flag.into());
+        }
+    }
+    let mut cmd = config.program.build(&config.out_dir);
+
+    cmd.arg("--color").arg("always");
+    cmd.arg(path);
+
     cmd.args(args);
+    println!("Running {cmd:?}");
```
Comment (oli-obk) [inline tests/compiletest.rs:291]: I re-added this, as this is what `./miri run` also prints

Comment (RalfJung) [reply tests/compiletest.rs:291]: Well, for `./miri run` it doesn't contain 3 lines of linker junk though.^^

File: tests/compiletest.rs [hunk 3]
```diff
@@ -274,13 +274,20 @@ fn main() -> Result<()> {
...
-    // the arguments to the interpreted prog
-    cmd.arg("--");
+    config.program.args.clear(); // We want to give the user full control over flags
+    config.build_dependencies_and_link_them()?;
+
+    if let Ok(extra_flags) = env::var("MIRIFLAGS") {
+        for flag in extra_flags.split_whitespace() {
+            config.program.args.push(flag.into());
+        }
+    }
```
Comment (RalfJung) [inline tests/compiletest.rs:284]: I'd rather have this done in `./miri` than here (then it is nicely in the same place for both run and run-dep)

File: tests/compiletest.rs [hunk 4]
```diff
@@ -274,13 +274,20 @@ fn main() -> Result<()> {
...
+    let mut cmd = config.program.build(&config.out_dir);
+
+    cmd.arg("--color").arg("always");
```
Comment (RalfJung) [inline tests/compiletest.rs:287]: Do we still need this?

File: tests/compiletest.rs (hunk 2 above)
Comment (oli-obk) [reply tests/compiletest.rs:291]: I could print before adding that 😆

Comment (RalfJung) [reply tests/compiletest.rs:291]: `./miri run` prints only because that is forced behavior by cargo, I don't think we want to reproduce that here... maybe just add a `-q` in `./miri run`?

File: tests/compiletest.rs (hunk 3 above)
Comment (oli-obk) [reply tests/compiletest.rs]: it was already done 😆 I ended up doing it twice

File: tests/compiletest.rs (hunk 2 above)
Comment (oli-obk) [reply tests/compiletest.rs]: Did that for both `run` and `run-dep`

**Comment by RalfJung** [comment]
Looks good, thanks!
@bors r+

**Comment by RalfJung** [comment]
Output is not fully identical yet:
```rust
$ ./miri run-dep tests/pass/hello.rs
   Building test dependencies...
Hello, world!
```
Should we hide that as well?

**Comment by oli-obk** [comment]
Yea, but that has to happen on the ui_test side. I'm working on simplifying the API (now that I got a bunch of users of it), so that `--quiet` and friends are automatically handled and affect these kind of outputs
