### PR TITLE
Skip doctests of `proc-macro` crates

### LINKED ISSUE #1813: Miri fails in many ways on `awint`
Previously, my [awint](https://github.com/AaronKutch/awint) repo was unified under two crates in a workspace, but when I split them up Miri started failing in many ways. Here are all the ways I know (note: run `cargo clean` before each case):
- `cargo miri test` (note: disable `awint/tests/fuzz_all.rs` or else the tests may take a long time) results in "found possibly newer version of crate `core`" error.
- `cargo test && cargo miri test` results in Miri trying to interpret an exe file as JSON
- `cargo miri test && cargo test` results in a bizarre error where it says it could not execute a process and gives no reason

### PR DESCRIPTION
**Pull request by hyd-dev**
Fixes #1813.

Verified that the newly added tests failed without the `cargo-miri` change and pass with normal `cargo test`.

### CODE REVIEW

File: cargo-miri/bin.rs [hunk 1]
```diff
@@ -903,6 +903,13 @@ fn phase_rustdoc(fst_arg: &str, mut args: env::Args) {
         show_error(format!("cross-interpreting doc-tests is not currently supported by Miri."));
     }
 
+    // Doc-tests of `proc-macro` crates (and their dependencies) are always built for the host,
+    // so we are not able to run them in Miri.
+    if ArgFlagValueIter::new("--crate-type").any(|crate_type| crate_type == "proc-macro") {
+        eprintln!("Running doc-tests of `proc-macro` crates is not currently supported by Miri.");
```
Comment (RalfJung) [inline cargo-miri/bin.rs:909]:
```suggestion
        eprintln!("Running doctests of `proc-macro` crates is not currently supported by Miri.");
```
https://doc.rust-lang.org/rustdoc/documentation-tests.html spells it without a "-"

File: test-cargo-miri/subcrate/src/lib.rs [hunk 2]
```diff
@@ -1,2 +1,5 @@
+#[cfg(doctest)]
+use num_cpus as _;
```
Comment (RalfJung) [inline test-cargo-miri/subcrate/src/lib.rs:2]: I'm a bit confused by this, I expected to see a doctest instead?
```rust
//! ```rust
//! assert!(true);
//! ```
```

File: cargo-miri/bin.rs (hunk 1 above)
Comment (hyd-dev) [reply cargo-miri/bin.rs]: The preexisting `show_error()` above uses "doc-tests" (with "-"). 🙃

File: test-cargo-miri/subcrate/src/lib.rs (hunk 2 above)
Comment (hyd-dev) [reply test-cargo-miri/subcrate/src/lib.rs:2]: I wanted to test that it does not invoke rustdoc at all. The error in #1813 happens when rustdoc is collecting doctests (if I remember correctly), and it fails because it found a dependency was not compiled using the libcore in Miri sysroot (thus I use `use num_cpus` here).

That said, maybe
```rust
#[cfg(doctest)]
compile_error!("rustdoc should not touch me");
```
is clearer.

File: cargo-miri/bin.rs (hunk 1 above)
Comment (RalfJung) [reply cargo-miri/bin.rs]: Ah, we should probably fix that too, then.^^ Sorry for this.
(I can do that in a separate PR.)

File: test-cargo-miri/subcrate/src/lib.rs (hunk 2 above)
Comment (RalfJung) [reply test-cargo-miri/subcrate/src/lib.rs:2]: I like the `compile_error!` version.

**Comment by RalfJung** [comment]
Thanks a lot for taking care of these nasty cargo integration bugs. :)
@bors r+
