### PR TITLE
Avoid error patterns matching themselves

### LINKED ISSUE #2156: Error patterns do not seem to work?
I edited an error pattern to make it not match the output and the tests still pass...
```diff
--- a/tests/compile-fail/validity/dangling_ref1.rs
+++ b/tests/compile-fail/validity/dangling_ref1.rs
@@ -3,5 +3,5 @@
 use std::mem;
 
 fn main() {
-    let _x: &i32 = unsafe { mem::transmute(16usize) }; //~ ERROR encountered a dangling reference (address $HEX is unallocated)
+    let _x: &i32 = unsafe { mem::transmute(16usize) }; //~ ERROR encountered a dangling reference (address $HEX is unallocateds)
 }
```
Cc @oli-obk this seems rather critical^^

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #2156
fixes https://github.com/rust-lang/miri/issues/2155

this will be obsolete the moment I extract that data from json diagnostics instead of just regexing the stderr.

### CODE REVIEW

**Comment by RalfJung** [comment]
Yeah I just realized the same thing. :joy: an error annotation justifying itself is such a great bug. :D

File: ui_test/.gitignore [hunk 1]
```diff
@@ -0,0 +1 @@
+Cargo.lock
```
Comment (RalfJung) [inline ui_test/.gitignore:1]: This is a workspace crate, why would such a file exist?

File: ui_test/tests/comment_parser.rs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+fn main() {
+    let _x: &i32 = unsafe { mem::transmute(16usize) }; //~ ERROR encountered a dangling reference (address $HEX is unallocated)
+}
+    ";
+    let comments = Comments::parse(Path::new("<dummy>"), s);
+    println!("{:#?}", comments);
+    assert_eq!(comments.error_matches[0].definition_line, 4);
+    assert_eq!(comments.error_matches[0].revision, None);
+    assert_eq!(comments.error_matches[0].matched, "encountered a dangling reference (address $HEX is unallocated)");
```
Comment (RalfJung) [inline ui_test/tests/comment_parser.rs:18]: This doesn't test for the issue of matching against yourself though, does it?

File: ui_test/tests/comment_parser.rs [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+fn issue_2156() {
+    let s = r"
+use std::mem;
+
+fn main() {
+    let _x: &i32 = unsafe { mem::transmute(16usize) }; //~ ERROR encountered a dangling reference (address $HEX is unallocated)
+}
+    ";
+    let comments = Comments::parse(Path::new("<dummy>"), s);
+    println!("{:#?}", comments);
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply ui_test/tests/comment_parser.rs:15]: you only see it if it fails

File: ui_test/tests/comment_parser.rs (hunk 2 above)
Comment (oli-obk) [reply ui_test/tests/comment_parser.rs]: yea that function was created when I thought it was a parser issue

File: ui_test/.gitignore (hunk 1 above)
Comment (RalfJung) [reply ui_test/.gitignore:1]: Shouldn't that use the workspace lockfile?

Or do we actually not have a workspace? cargo-miri is also just a separate crate, so I guess that is the case.
And using workspaces anyway means trouble because of our rustc integration...

But does this mean `./miri test` does currently not run these tests?

File: ui_test/tests/comment_parser.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (RalfJung) [reply ui_test/tests/comment_parser.rs:15]: Fair. But still, please at least make the output a bit more self-descriptive.

File: ui_test/.gitignore (hunk 1 above)
Comment (oli-obk) [reply ui_test/.gitignore:1]: it doesn't run those tests.

File: ui_test/tests/comment_parser.rs [hunk 4]
```diff
@@ -0,0 +1,19 @@
+use std::path::Path;
+
+use ui_test::Comments;
+
+#[test]
+fn issue_2156() {
```
[the remark this answers is not in the document]
Comment (RalfJung) [reply ui_test/tests/comment_parser.rs:6]: > oli-obk marked this conversation as resolved. 

I hope this means it is going to be added to `./miri test`. :)

File: ui_test/src/lib.rs [hunk 5]
```diff
@@ -169,7 +169,7 @@ pub fn run_tests(config: Config) {
 }
 
 #[derive(Debug)]
-enum Error {
+pub enum Error {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply ui_test/src/lib.rs]: I moved to unit tests

File: miri [hunk 6]
```diff
@@ -134,7 +134,8 @@ test|test-debug|bless|bless-debug)
     esac
     # Then test, and let caller control flags.
     # Only in root project as `cargo-miri` has no tests.
```
Comment (RalfJung) [inline miri:136]:
```suggestion
    # Only in root project and ui_test as `cargo-miri` has no tests.
```

File: miri [hunk 7]
```diff
@@ -134,7 +134,8 @@ test|test-debug|bless|bless-debug)
...
-    exec cargo test $CARGO_BUILD_FLAGS "$@"
+    cargo test $CARGO_BUILD_FLAGS "$@"
+    cargo test --manifest-path ui_test/Cargo.toml
```
Comment (RalfJung) [inline miri:138]: `$CARGO_BUILD_FLAGS "$@"` should probably be added here as well?

File: ui_test/.gitignore (hunk 1 above)
Comment (RalfJung) [reply ui_test/.gitignore:1]: We have the other lock files committed. This is required to ensure tests are reproducible. Why wouldn't we want to commit this one as well?

File: ui_test/src/comments.rs [hunk 8]
```diff
@@ -26,16 +29,23 @@ pub struct Comments {
...
-    pub fn parse(path: &Path) -> Self {
-        let mut this = Self::default();
+    pub fn parse_file(path: &Path) -> Self {
         let content = std::fs::read_to_string(path).unwrap();
+        Self::parse(path, &content)
+    }
+
+    /// Parse comments in `content`.
+    /// `path` is only used to emit diagnostics if parsing fails.
+    pub fn parse(path: &Path, content: &str) -> Self {
```
Comment (RalfJung) [inline ui_test/src/comments.rs:47]: Can this be made private now?

File: miri (hunk 7 above)
Comment (oli-obk) [reply miri]: I went all the way and implemented command line path filtering again

File: ui_test/.gitignore (hunk 1 above)
Comment (oli-obk) [reply ui_test/.gitignore:1]: for our main test suite it's irrelevant. This is just for unit tests of the ui_test crate. library crates usually don't commit their Cargo.lock

Comment (RalfJung) [reply ui_test/.gitignore]: > library crates usually don't commit their Cargo.lock

I know. I was about to say I disagree with that common choice since it means old CI runs cannot be (easily) reproduced, but we can defer this to a later PR. Then you added the lockfile already anyway. Thanks. :)

File: miri [hunk 9]
```diff
@@ -133,8 +133,9 @@ test|test-debug|bless|bless-debug)
         ;;
     esac
     # Then test, and let caller control flags.
-    # Only in root project as `cargo-miri` has no tests.
-    exec cargo test $CARGO_BUILD_FLAGS "$@"
+    # Only in root project and ui_test as `cargo-miri` has no tests.
+    cargo test $CARGO_BUILD_FLAGS "$@"
+    cargo test --manifest-path ui_test/Cargo.toml "$@"
```
Comment (RalfJung) [inline miri:138]: Any specific reason why you omitted CARGO_BUILD_FLAGS?

**Comment by RalfJung** [comment]
LGTM! r=me with the last nit resolved (by adding a comment explaining the lack of CARGO_BUILD_FLAGS, or adding them) and the commits squashed a bit (or entirely).

File: miri (hunk 7 above)
Comment (RalfJung) [reply miri]: Awesome, thanks. :)
