### PR TITLE
More robust comment parsing

### LINKED ISSUE #2170: ui_test: more robust comment parsing
Currently, if we fail to parse a `//~` line or an annotation like `// ignore-target`, we just go on. That's a pretty bad default for infrastructure that is meant to test our code! For both of these I think we should hard error if we cannot parse the line.

For `//~` that is fairly easy; if any comment starting `//~` eludes us we can just error.

For the other annotations it is a lot harder since that might just be a regular comment. I think we need to change their syntax so that we can tell that this line is meant to be special. `//@` might work? We should ideally sync this with compiletest, in case they have similar plans.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #2170

I haven't ported the entire test suite yet. Once we've done that, I will remove the old parsing system (or in fact, turn them into errors so that accidental usage of old-style comments will be detected)

### CODE REVIEW

File: miri [hunk 1]
```diff
@@ -163,8 +163,8 @@ test|test-debug|bless|bless-debug)
     esac
     # Then test, and let caller control flags.
     # Only in root project and ui_test as `cargo-miri` has no tests.
-    $CARGO test $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml "$@"
     $CARGO test $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/ui_test/Cargo.toml "$@"
+    $CARGO test $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml "$@"
```
Comment (RalfJung) [inline miri:167]: Not sure I like that, building the ui_test tests can take a bit and I don't want to wait for that before the main Miri tests run. In fact I often Ctrl-C during the ui_test tests so that I can get my terminal back.^^

File: ui_test/src/comments.rs [hunk 2]
```diff
@@ -64,6 +64,43 @@ impl Condition {
     }
 }
 
+macro_rules! checked {
```
Comment (RalfJung) [inline ui_test/src/comments.rs:67]: Please add comments... I find macro definitions basically impossible to read.

File: ui_test/src/comments.rs [hunk 3]
```diff
@@ -72,14 +109,45 @@ impl Comments {
 
     /// Parse comments in `content`.
     /// `path` is only used to emit diagnostics if parsing fails.
-    pub(crate) fn parse(path: &Path, content: &str) -> Self {
+    ///
+    /// This function will only parse `//@` and `//~` style comments
+    /// and ignore all others
```
Comment (RalfJung) [inline ui_test/src/comments.rs:114]: And `//[` it seems?

File: ui_test/src/comments.rs [hunk 4]
```diff
@@ -72,14 +109,45 @@ impl Comments {
...
+            } else {
+                fallthrough_to = None;
+            }
+        }
+        this
+    }
+
+    /// Parse comments in `content`.
+    /// `path` is only used to emit diagnostics if parsing fails.
+    pub(crate) fn parse(path: &Path, content: &str) -> Self {
```
Comment (RalfJung) [inline ui_test/src/comments.rs:144]: I don't think we want to keep maintaining all this code.

> (or in fact, turn them into errors so that accidental usage of old-style comments will be detected)

If you want to do that, please just use a single regex like `// *(compiler?-flag|only-|ignore-)` and warn/error when that matches. We don't need the full parser for this.

File: ui_test/src/comments.rs [hunk 5]
```diff
@@ -72,14 +109,45 @@ impl Comments {
...
 
         // The line that a `|` will refer to
         let mut fallthrough_to = None;
+        for (l, line) in content.lines().enumerate() {
+            let l = l + 1; // enumerate starts at 0, but line numbers start at 1
+            if let Some((_, command)) = line.split_once("//@") {
+                let command = command.trim();
+                if let Some((command, args)) = command.split_once(':') {
+                    this.parse_command_with_args(command, args, path, l);
+                } else if let Some((command, _comments)) = command.split_once(' ') {
```
Comment (RalfJung) [inline ui_test/src/comments.rs:126]: Looks like there is some syntax being defined here, please document that.

File: ui_test/src/comments.rs [hunk 6]
```diff
@@ -140,36 +208,141 @@ impl Comments {
...
-                let revision = captures.name("revision").map(|rev| rev.as_str().to_string());
+    fn parse_command_with_args(&mut self, command: &str, args: &str, path: &Path, l: usize) {
+        checked!(path, l);
+        match command {
+            "revisions" => {
+                check!(self.revisions.is_none(), "cannot specifiy revisions twice");
+                self.revisions = Some(args.split_whitespace().map(|s| s.to_string()).collect());
+            }
+            "compile-flags" => {
+                self.compile_flags.extend(args.split_whitespace().map(|s| s.to_string()));
```
Comment (RalfJung) [inline ui_test/src/comments.rs:223]: Please document that these accumulate.

File: ui_test/src/comments.rs [hunk 7]
```diff
@@ -140,36 +208,141 @@ impl Comments {
...
+            "error-pattern" => {
+                check!(
+                    self.error_pattern.is_none(),
+                    "cannot specifiy error_pattern twice, previous: {:?}",
+                    self.error_pattern
+                );
+                self.error_pattern = Some((args.trim().to_string(), l));
+            }
+            // Maybe the user just left a comment explaining a command without arguments
+            _ => self.parse_command(command, path, l),
```
Comment (RalfJung) [inline ui_test/src/comments.rs:250]: ...? This is odd.

I think what I would have expected is a parser that takes things from the line. Eagerly finding the `:` and this entire with/without args split doesn't look like normal parsing.^^

File: ui_test/src/comments.rs [hunk 8]
```diff
@@ -140,36 +208,141 @@ impl Comments {
...
-                fallthrough_to = None;
-            }
+        if let Some(s) = command.strip_prefix("ignore-") {
+            self.ignore.push(Condition::parse(s));
+            return;
         }
-        this
+
+        if let Some(s) = command.strip_prefix("only-") {
+            self.only.push(Condition::parse(s));
```
Comment (RalfJung) [inline ui_test/src/comments.rs:263]: Note that `Condition::parse` can panic... now that you have error reporting here it'd be nice to also use that for incorrect conditions.

For proper reliable parsing, I think `ignore-windows` should become `ignore-target-windows`, otherwise we have the same problem again of having some special commands (ignore-debug, ignore-32bit) and then silently falling back to another way of interpreting the command.

File: miri (hunk 1 above)
Comment (oli-obk) [reply miri:167]: ah true ^^ it takes milliseconds to run, but the compiling delay is noticeable. Once it's compiled the next time will not be noticeable though unless you touch ui_test, in which case we *do* want to recompile and rerun the tests, so 🤷

File: ui_test/src/comments.rs (hunk 8 above)
Comment (oli-obk) [reply ui_test/src/comments.rs:263]: agreed. For minimal churn I want to change as little as possible until we rip out the old logic and then improve the parser step by step.

File: ui_test/src/comments.rs (hunk 7 above)
Comment (oli-obk) [reply ui_test/src/comments.rs:250]: yea... it felt convenient to do it this way ^^ but I can do a proper token munching parser instead.

**Comment by oli-obk** [comment]
The new attribute parsing errors now look like

```
tests/fail/memleak.rs ... ok
Error: 
   0: tests/fail/memleak_rc.rs:3: failed to parse annotation
   1: unknown command normalasdfize-stderr-test

Location:
   ui_test/src/comments.rs:248
```

(plus some terminal coloring for readability)

File: miri (hunk 1 above)
Comment (RalfJung) [reply miri]: It's never compiled after a `./rustup-toolchain` though, which is a significant fraction of my builds.

File: ui_test/src/comments.rs (hunk 4 above)
Comment (RalfJung) [reply ui_test/src/comments.rs]: What's the issue with just porting them all now?

I don't like having so many dead code paths here.

**Comment by RalfJung** [comment]
> The new attribute parsing errors now look like
> 
> ```
> tests/fail/memleak.rs ... ok
> Error: 
>    0: tests/fail/memleak_rc.rs:3: failed to parse annotation
>    1: unknown command normalasdfize-stderr-test
> 
> Location:
>    ui_test/src/comments.rs:248
> ```
> 
> (plus some terminal coloring for readability)

I am confused by that error. There are two locations there, which one is it at? And why does error 0 have a filename and line but error 1 not?

File: ui_test/src/tests.rs [hunk 9]
```diff
@@ -317,7 +324,13 @@ fn main() {
...
+        [Error::ErrorPatternWithoutErrorAnnotation(_, 5)] => Ok(()),
         _ => panic!("{:#?}", errors),
     }
 }
+
+static INIT: std::sync::Once = std::sync::Once::new();
+
+pub fn init() {
+    INIT.call_once(|| color_eyre::install().unwrap());
+}
```
Comment (RalfJung) [inline ui_test/src/tests.rs:336]: Uh, what is this? The static is de-facto even private to this function, right?

File: ui_test/src/comments.rs [hunk 10]
```diff
@@ -140,36 +178,155 @@ impl Comments {
...
+            match command.chars().position(|c: char| !c.is_alphabetic() && c != '-') {
+                None => (command, ""),
+                Some(i) => {
+                    let (command, args) = command.split_at(i);
+                    let mut args = args.chars();
+                    let next = args
+                        .next()
+                        .expect("the `position` above guarantees that there is at least one char");
+                    let args = match next {
+                        ':' | ' ' => args.as_str(),
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply ui_test/src/comments.rs:197]: yea, just replicating the existing grammar for now, we can iterate on it later ^^

File: ui_test/src/comments.rs [hunk 11]
```diff
@@ -140,36 +178,155 @@ impl Comments {
...
+                        eyre!("environment variables must be key/value pairs separated by a `=`")
+                    })?;
+                    self.env_vars.push((k.to_string(), v.to_string()));
+                },
+            "normalize-stderr-test" => {
+                let (from, to) = args
+                    .split_once("->")
+                    .ok_or_else(|| eyre!("normalize-stderr-test needs a `->`"))?;
+                let from = from.trim().trim_matches('"');
+                let to = to.trim().trim_matches('"');
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply ui_test/src/comments.rs:224]: oh yea, that's just me being lazy ^^

File: ui_test/src/tests.rs (hunk 9 above)
Comment (oli-obk) [reply ui_test/src/tests.rs:336]: yea, it's to make sure all tests have an initialized eyre, but only the first one (racy) actually performs the act

**Comment by oli-obk** [comment]
> I am confused by that error. There are two locations there, which one is it at? And why does error 0 have a filename and line but error 1 not?

the "Location" is the place in ui testing where the error was raised

the list is a sort of backtrace of information. This helps avoid passing down all the information, as each bubbling up can attach information in the failure case instead of pushing information in

File: ui_test/src/comments.rs (hunk 11 above)
[the remark this answers is not in the document]
Comment (RalfJung) [reply ui_test/src/comments.rs]: Ah, without a FIXME I thought this was meant to be its final form. :)

**Comment by RalfJung** [comment]
> the "Location" is the place in ui testing where the error was raised

Okay. For user-visible errors I don't think we want to show any of our internal source code locations by default. IMO basically we should either panic ("we don't care, just report the error somehow") or do it properly... going half-way doesn't seem worth the effort?
Also that doesn't explain why only one of the errors points at a test file+line.

File: ui_test/src/comments.rs [hunk 12]
```diff
@@ -140,36 +177,179 @@ impl Comments {
...
+            }
+            "rustc-env" =>
+                for env in args.split_whitespace() {
+                    let (k, v) = env.split_once('=').ok_or_else(|| {
+                        eyre!("environment variables must be key/value pairs separated by a `=`")
+                    })?;
+                    self.env_vars.push((k.to_string(), v.to_string()));
+                },
+            "normalize-stderr-test" => {
+                fn parse_str(s: &str) -> Result<(&str, &str)> {
```
Comment (RalfJung) [inline ui_test/src/comments.rs:220]:
```suggestion
                /// Parses a string literal. `s` has to start with `"`; everything until the next `"` is
                /// returned in the first component. `\` can be used to escape arbitrary character.
                /// Second return component is the rest of the string with leading whitespace removed.
                fn parse_str(s: &str) -> Result<(&str, &str)> {
```

**Comment by oli-obk** [comment]
> Okay. For user-visible errors I don't think we want to show any of our internal source code locations by default. IMO basically we should either panic ("we don't care, just report the error somehow") or do it properly... going half-way doesn't seem worth the effort?

done, we show a message about RUST_BACKTRACE, but nothing else by default

> Also that doesn't explain why only one of the errors points at a test file+line.

it's not multiple errors. this is the "spantrace" for a single error. So whenever we call a function, we can attach some information to the failure-path on that function call. To showcase this, I only added information to the `parse_checked_line` call (adding the file + line information). if we replace more `?` with

```
.map_err(|err| err.wrap_err(format!("your info goes here")))?
```

then we get more entries in that list, telling us exactly how we got to the error.

File: ui_test/src/comments.rs (hunk 4 above)
Comment (oli-obk) [reply ui_test/src/comments.rs]: Mostly because it's very conflict prone and I'd have to rebase too often ^^
