### PR TITLE
 Patch `--extern` arguments in `phase_cargo_rustc` as well

### LINKED ISSUE #1705: Can't find crate with `hyper` crate as a dependency
## MCVE

`Cargo.toml`:

```toml
[dependencies]
hyper = "0.14.4"
```

## Error

```
...
Compiling hyper v0.14.4
error[E0463]: can't find crate for `http`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.4/src/lib.rs:61:9
   |
61 | pub use http;
   |         ^^^^ can't find crate

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by hyd-dev**
Fixes #1705.

### CODE REVIEW

**Comment by RalfJung** [comment]
> This contains #1671 now

Can you just take the relevant parts of that PR, i.e. `forward_patched_extern_arg`? I'd prefer to review these separately.

File: cargo-miri/bin.rs [hunk 1]
```diff
@@ -625,15 +625,6 @@ fn phase_cargo_rustc(mut args: env::Args) {
...
 
-    // cdylib is just skipped, we cannot interpret it and do not need it
-    // for the rest of the build either.
-    if get_arg_flag_value("--crate-type").as_deref() == Some("cdylib") {
-        if verbose {
-            eprint!("[cargo-miri rustc] (cdylib skipped)");
-        }
-        return;
-    }
-
```
Comment (hyd-dev) [inline cargo-miri/bin.rs:607]: The #1675 regression test still passed (both before and after f82c018c14a2457184576e6f2ba5a33d251fc3bc) even I remove this, so either that test did not work or this PR fixes #1675 in another way as well.
I also added a test for `cdylib`-only crate (since that is the "skipped" case if this is not removed, but this is removed anyway, so that test may be redundant).

File: test-cargo-miri/issue-1705/src/lib.rs [hunk 2]
```diff
@@ -0,0 +1,5 @@
+use byteorder::{LittleEndian, ByteOrder};
+
+pub fn use_the_dependency() {
+    let _n = <LittleEndian as ByteOrder>::read_u32(&[1,2,3,4]);
+}
```
Comment (hyd-dev) [inline test-cargo-miri/issue-1705/src/lib.rs:5]: The new tests duplicate `issue-1567/src/lib.rs`, but I don't know how to write them without duplication (unless `include!("issue-1567/src/lib.rs")` or `#[path = "../../issue-1567/src/lib.rs"] pub mod ...`... Sorry.

**Review by hyd-dev — COMMENTED** [review]
> Can you just take the relevant parts of that PR, i.e. `forward_patched_extern_arg`? I'd prefer to review these separately.

Sure. Starting to rebase now...

File: cargo-miri/bin.rs (hunk 1 above)
Comment (RalfJung) [reply cargo-miri/bin.rs:607]: Do you mean the test added in https://github.com/rust-lang/miri/pull/1708? I did verify that removing the `cdylib` thing here makes that test fail, but you might have to `rm target -rf` to make sure it doesn't use cached results.

Comment (hyd-dev) [reply cargo-miri/bin.rs:607]: Yes. IIRC I ran `cargo clean` before running tests. Sounds like this PR really fixes #1675 in another way.

Comment (hyd-dev) [reply cargo-miri/bin.rs:607]: Sorry for the #1567 typo...

File: test-cargo-miri/issue-1705/src/lib.rs (hunk 2 above)
Comment (RalfJung) [reply test-cargo-miri/issue-1705/src/lib.rs:5]: That's okay, it's not like this is a lot of code.

File: cargo-miri/bin.rs [hunk 3]
```diff
@@ -694,6 +689,18 @@ fn phase_cargo_rustc(args: env::Args) {
     }
 }
 
+fn forward_patched_extern_arg(args: &mut impl Iterator<Item = String>, cmd: &mut Command) {
```
Comment (RalfJung) [inline cargo-miri/bin.rs:692]: Can you move this function up, to the other helper functions?

File: cargo-miri/bin.rs [hunk 4]
```diff
@@ -739,16 +746,7 @@ fn phase_cargo_runner(binary: &Path, binary_args: env::Args) {
     let json_flag = "--json";
     while let Some(arg) = args.next() {
         if arg == extern_flag {
```
Comment (RalfJung) [inline cargo-miri/bin.rs:748]: This is now the only use of `extern_flag` so I guess it'd make sense to inline this.

File: cargo-miri/bin.rs (hunk 1 above)
Comment (hyd-dev) [reply cargo-miri/bin.rs:607]: [CI run](https://github.com/rust-lang/miri/runs/1898418367) for 45bcbfe65f0b6b2055a0b8f7f0f0fc8c59a1c272 (8d48ad908485a04112f27d6a22c85eae3e8e4aa7...45bcbfe65f0b6b2055a0b8f7f0f0fc8c59a1c272 does not change that test) confirmed this PR really fixes #1567.

File: test-cargo-miri/src/lib.rs [hunk 5]
```diff
@@ -3,5 +3,11 @@
 /// assert!(cargo_miri_test::make_true());
 /// ```
 pub fn make_true() -> bool {
+    extern "C" {
+        fn use_cdylib();
+    }
+    drop(use_cdylib);
```
Comment (RalfJung) [inline test-cargo-miri/src/lib.rs:9]: Hm, I don't think this will actually "use" anything in Miri.

File: cargo-miri/bin.rs (hunk 1 above)
Comment (RalfJung) [reply cargo-miri/bin.rs:607]: > Sounds like this PR really fixes #1567 in another way.

That's great, this fix makes more sense anyway. :)

File: cargo-miri/bin.rs (hunk 3 above)
Comment (hyd-dev) [reply cargo-miri/bin.rs:692]: (I copied this, including its location, and the bellow `extern_flag` change, from #1671 directly without modification, but sure I can change them.)

File: test-cargo-miri/src/lib.rs (hunk 5 above)
Comment (hyd-dev) [reply test-cargo-miri/src/lib.rs:9]: Would coercing it to a function pointer be better? (I think calling it is not supported since it's `extern "C"`.)

Comment (RalfJung) [reply test-cargo-miri/src/lib.rs:9]: That won't do much either I think -- a call would be needed.
Since that doesn't work... I am not sure if we can't really properly test this currently.

Comment (hyd-dev) [reply test-cargo-miri/src/lib.rs:9]: Maybe it's better to remove this, the function can't be called anyway. The `cdylib` dependency itself can still be used to test whether `cargo-miri` can build it or not.

Comment (RalfJung) [reply test-cargo-miri/src/lib.rs:9]: So, before this PR that cdylib library caused some kind of error?

Comment (hyd-dev) [reply test-cargo-miri/src/lib.rs:9]: No, but `cargo-miri` used to handle `cdylib` specially so I wrote this test.

(I explained that in https://github.com/rust-lang/miri/pull/1710#discussion_r575829920, looks like it got lost:)
> I also added a test for `cdylib`-only crate (since that is the "skipped" case if this is not removed, but this is removed anyway, so that test may be redundant).

Comment (RalfJung) [reply test-cargo-miri/src/lib.rs:9]: Okay, sure.
Please add a comment somewhere in that crate to explain why it exists.

Comment (hyd-dev) [reply test-cargo-miri/src/lib.rs:9]: Should I remove this probably useless `drop(use_cdylib)` then?

Comment (RalfJung) [reply test-cargo-miri/src/lib.rs:9]: Yeah, please do.

**Comment by RalfJung** [comment]
Looks good. :) It is still marked as a draft though, is there something you still wanted to do?

Also, maybe squash the history a bit; no need to preserve all those 9 commits I think.

**Comment by hyd-dev** [comment]
> It is still marked as a draft though, is there something you still wanted to do?

I'm just not sure where `forward_patched_extern_arg()` belongs to (it could also be in #1671 and maybe that could be merged first).

**Comment by RalfJung** [comment]
https://github.com/rust-lang/miri/pull/1671 isn't quite ready yet and I'd prefer not to block this fix on that PR.

Thanks for yet another cargo-miri fix :)
@bors r+
