### PR TITLE
Restore test filtering by substring.

### LINKED ISSUE #2958: Test filtering is broken
`./miri test vec` should run the tests that contain "vec" in their name. But it doesn't, the tests all get skipped:
```
## Running ui tests in tests/pass against miri for x86_64-unknown-linux-gnu
   Compiler: /home/r/src/rust/miri/target/debug/miri "--error-format=json" "-Dwarnings" "-Dunused" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--out-dir" OUT_DIR

test result: ok. 0 tests passed, 0 ignored, 0 filtered out

## Running ui tests in tests/pass-dep against miri for x86_64-unknown-linux-gnu
   Compiler: /home/r/src/rust/miri/target/debug/miri "--error-format=json" "-Dwarnings" "-Dunused" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--out-dir" OUT_DIR
   Building test dependencies...

test result: ok. 0 tests passed, 0 ignored, 0 filtered out

## Running ui tests in tests/panic against miri for x86_64-unknown-linux-gnu
   Compiler: /home/r/src/rust/miri/target/debug/miri "--error-format=json" "-Dwarnings" "-Dunused" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--out-dir" OUT_DIR
   Building test dependencies...

test result: ok. 0 tests passed, 0 ignored, 0 filtered out

## Running ui tests in tests/fail against miri for x86_64-unknown-linux-gnu
   Compiler: /home/r/src/rust/miri/target/debug/miri "--error-format=json" "-Dwarnings" "-Dunused" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--out-dir" OUT_DIR
   Building test dependencies...

test result: ok. 0 tests passed, 0 ignored, 0 filtered out

## Running ui tests in tests/extern-so/pass against miri for x86_64-unknown-linux-gnu
   Compiler: /home/r/src/rust/miri/target/debug/miri "--error-format=json" "-Dwarnings" "-Dunused" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "-Zmiri-extern-so-file=/home/r/src/rust/miri/target/miri-extern-so/libtestlib.so" "--out-dir" OUT_DIR

test result: ok. 0 tests passed, 0 ignored, 0 filtered out

## Running ui tests in tests/extern-so/fail against miri for x86_64-unknown-linux-gnu
   Compiler: /home/r/src/rust/miri/target/debug/miri "--error-format=json" "-Dwarnings" "-Dunused" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "-Zmiri-extern-so-file=/home/r/src/rust/miri/target/miri-extern-so/libtestlib.so" "--out-dir" OUT_DIR

test result: ok. 0 tests passed, 0 ignored, 0 filtered out
```

This also affects CI; our checks for partially supported targets are currently not actually checking anything.

@oli-obk could this be caused by some recent ui-test updates?

### PR DESCRIPTION
**Pull request by oli-obk**
Previously it was only looking for tests whose path was a prefix of the given filter

fixes #2958

### CODE REVIEW

File: tests/compiletest.rs [hunk 1]
```diff
@@ -145,7 +145,10 @@ fn run_tests(mode: Mode, path: &str, target: &str, with_dependencies: bool) -> R
         // The files we're actually interested in (all `.rs` files).
         |path| {
             path.extension().is_some_and(|ext| ext == "rs")
-                && (filters.is_empty() || filters.iter().any(|f| path.starts_with(f)))
+                && (filters.is_empty()
+                    || filters.iter().any(|f| {
+                        path.components().any(|c| c.as_os_str().to_string_lossy().contains(f))
```
Comment (RalfJung) [inline tests/compiletest.rs:150]: That's not the right behavior -- filtering for `pass/stack` should also work. It should just be doing substring on the entire filename.
