### PR TITLE
Make file descriptors into refcount references

### LINKED ISSUE #3525: Make file descriptors into refcounted references to "file descriptions"
Currently, every file descriptor has to implement `dup`, and some do that incorrectly. The issue is that file descriptors are more like `Arc` than like `Box`, so all state should be shared among all the duplicates, which typically requires an extra level of indirection -- e.g. in eventfd or epoll, where duplicate file descriptors should reference the same underlying state.

Instead of making each FD type handle that, we should remove `dup` from the `FileDescriptor` trait and handle this ourselves. I see two ways to do that:
- Literally use `Arc<dyn FileDescription>` instead of `Box<dyn FileDescriptor>`, so `Arc` handles the refcounting for us for free. However this will require interior mutability if the file description tracks mutable state (as many of the "special" FDs will).
- Add some sort of `FxHashMap<FileDescriptionId, (usize, Box<dyn FileDescription>)>` (where the `usize` is a refcount) and then make the FD table simply reference `FileDescriptionId`. This means we have to do refcounting ourselves but we can get exclusive access to the data inside a file description.

Interior mutability is annoying, but then there is some chance we'll need to give the `read`/`write` methods access to the machine (even mutable access!) and then it seems hard to avoid some form of interior mutability. So currently my gut feeling is that manual refcounting isn't worth it.

### PR DESCRIPTION
**Pull request by Luv-Ray**
fixes #3525 

Remove `fn dup` in `trait FileDescription`, define `struct FileDescriptor(Rc<RefCell<dyn FileDescription>>)`, and use `BTreeMap<i32, FileDescriptor>` in `FdTable`.

---

There are some refactors similar to the following form:
```rust
{  // origin:
    if let Some(file_descriptor) = this.machine.fds.get_mut(fd) {
        // write file_descriptor
        this.try_unwrap_io_result(result)
    } else {
        this.fd_not_found()
    }
}
{  // now:
    let Some(mut file_descriptor) = this.machine.fds.get_mut(fd) else {
        return this.fd_not_found();
    };
    // write file_descriptor
    drop(file_descriptor);
    this.try_unwrap_io_result(result)
}
```
The origin form can't compile because as using `RefCell` to get interior mutability, `fn get_mut` return `Option<std::cell::RefMut<'_, dyn FileDescription>>` instead of `Option<&mut dyn FileDescription>` now, and the `deref_mut` on `file_descriptor: RefMut` will cause borrow `this` as mutable more than once at a time. 
So this form of refactors and manual drops are are implemented to avoid borrowing `this` at the same time.

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks for the PR! That was quick. :)

> define struct FileDescription(Rc<RefCell<dyn FileDescriptor>>)

This sounds the wrong way around. Many file descriptors map to fewer file descriptions, not the other way around.

File: src/shims/unix/fd.rs [hunk 1]
```diff
@@ -41,24 +43,19 @@ pub trait FileDescriptor: std::fmt::Debug + Any {
         throw_unsup_format!("cannot seek on {}", self.name());
     }
 
-    fn close<'tcx>(
-        self: Box<Self>,
-        _communicate_allowed: bool,
-    ) -> InterpResult<'tcx, io::Result<i32>> {
+    /// Note: Please ensure `Rc::strong_count(&fd) == 1` before calling this fuction.
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply src/shims/unix/fd.rs:46]: ah, but that's what you meant 🤦 yea, we should only call this once

File: src/shims/unix/fd.rs [hunk 2]
```diff
@@ -329,7 +313,8 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriInterpCxExt<'mir, 'tcx> {
         let fd = this.read_scalar(fd_op)?.to_i32()?;
 
         Ok(Scalar::from_i32(if let Some(file_descriptor) = this.machine.fds.remove(fd) {
-            let result = file_descriptor.close(this.machine.communicate())?;
+            let result =
+                file_descriptor.0.as_ref().borrow_mut().close(this.machine.communicate())?;
```
Comment (oli-obk) [inline src/shims/unix/fd.rs:317]: so.. we'll want to check the refcount here first, and only call close if it's 1

Comment (Luv-Ray) [reply src/shims/unix/fd.rs]: refactored the close check to another function, thanks for the review :)

File: src/shims/unix/fd.rs [hunk 3]
```diff
@@ -41,24 +43,19 @@ pub trait FileDescriptor: std::fmt::Debug + Any {
         throw_unsup_format!("cannot seek on {}", self.name());
     }
 
-    fn close<'tcx>(
-        self: Box<Self>,
-        _communicate_allowed: bool,
-    ) -> InterpResult<'tcx, io::Result<i32>> {
+    /// Note: This function should not be called except [`FileDescriptor::close`].
+    fn close<'tcx>(&mut self, _communicate_allowed: bool) -> InterpResult<'tcx, io::Result<i32>> {
```
Comment (RalfJung) [inline src/shims/unix/fd.rs:47]: Can you make this function take `self`? Then we can be sure it is called only once.

We can use `Rc::into_inner` to get ownership of `self` for this.

**Review by RalfJung — COMMENTED** [review]
Nice! I quite like the `let ... else` pattern, it avoids rightward drift of the actual core logic of these operations.

However, I think we can do `close` a bit nicer, without manually looking at the `strong_count`.

File: src/shims/unix/fd.rs (hunk 3 above)
Comment (Luv-Ray) [reply src/shims/unix/fd.rs:47]: That's correct, using `self` as a parameter for `close` would be more natural. However, it would result in an error:

>  the size for values of type `Self` cannot be known at compilation time

An alternative approach is to take `Box<self>` as parameter and `FileDescriptor` will become `Rc<RefCell<Box<dyn FileDescription>>>`. What do you think about this?

Comment (RalfJung) [reply src/shims/unix/fd.rs:47]: Ah, right, it must be object safe... the double pointer indirection is a bit unfortunate,y but yeah making it `Box<self>` sounds like a good idea to me.

Comment (Luv-Ray) [reply src/shims/unix/fd.rs]: done :)

File: src/shims/unix/fd.rs [hunk 4]
```diff
@@ -172,16 +159,28 @@ impl FileDescriptor for NullOutput {
...
+
+impl FileDescriptor {
+    pub fn new<T: FileDescription>(fd: T) -> Self {
+        FileDescriptor(Rc::new(RefCell::new(Box::new(fd))))
+    }
 
-    fn dup(&mut self) -> io::Result<Box<dyn FileDescriptor>> {
-        Ok(Box::new(NullOutput))
+    pub fn close<'ctx>(self, communicate_allowed: bool) -> InterpResult<'ctx, io::Result<i32>> {
+        match Rc::into_inner(self.0) {
```
Comment (RalfJung) [inline src/shims/unix/fd.rs:173]:
```suggestion
        // Destroy this `Rc` using `into_inner` so we can call `close` instead of
        // implicitly running the destructor of the file description.
        match Rc::into_inner(self.0) {
```

File: src/shims/unix/fd.rs [hunk 5]
```diff
@@ -43,8 +43,10 @@ pub trait FileDescription: std::fmt::Debug + Any {
         throw_unsup_format!("cannot seek on {}", self.name());
     }
 
-    /// Note: This function should not be called except [`FileDescriptor::close`].
-    fn close<'tcx>(&mut self, _communicate_allowed: bool) -> InterpResult<'tcx, io::Result<i32>> {
+    fn close<'tcx>(
+        self: Box<Self>,
+        _communicate_allowed: bool,
+    ) -> InterpResult<'tcx, io::Result<i32>> {
```
Comment (RalfJung) [inline src/shims/unix/fd.rs:49]: Do you know why `close` returns an `i32`? Shouldn't this be `InterpResult<'tcx, io::Result<()>>`?

File: src/shims/unix/fd.rs [hunk 6]
```diff
@@ -233,12 +234,12 @@ impl FdTable {
         new_fd
     }
 
-    pub fn get(&self, fd: i32) -> Option<Ref<'_, dyn FileDescription>> {
```
Comment (RalfJung) [inline src/shims/unix/fd.rs]: You can probably keep the `Option<Ref<'_, dyn FileDescription>>` return type by using `Ref::map`.

Comment (Luv-Ray) [reply src/shims/unix/fd.rs]: learned a lot :)

File: src/shims/unix/fd.rs (hunk 5 above)
Comment (Luv-Ray) [reply src/shims/unix/fd.rs]: As `EvalContextExt::close` returns `InterpResult<'tcx, Scalar<Provenance>>`, we can return `InterpResult<'tcx, io::Result<()>>` in `FileDescription::close` and then map the `io::Result<()>` to `io::Result<i32>`

File: src/shims/unix/fs.rs [hunk 7]
```diff
@@ -17,15 +17,17 @@ use crate::shims::unix::*;
...
 struct FileHandle {
     file: File,
     writable: bool,
 }
 
-impl FileDescriptor for FileHandle {
+impl FileDescription for FileHandle {
     fn name(&self) -> &'static str {
-        "FILE"
+        "file"
```
Comment (Luv-Ray) [inline src/shims/unix/fs.rs:30]: All other `FileDescription`'s name are lower case, so I changed it to keep the same.

File: src/shims/unix/fd.rs [hunk 8]
```diff
@@ -330,6 +325,8 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriInterpCxExt<'mir, 'tcx> {
 
         Ok(Scalar::from_i32(if let Some(file_descriptor) = this.machine.fds.remove(fd) {
             let result = file_descriptor.close(this.machine.communicate())?;
+            // return `0` if close is successful
+            let result = result.map(|_| 0i32);
```
Comment (Luv-Ray) [inline src/shims/unix/fd.rs:329]: let `FileDescription::close` return `InterpResult<'tcx, io::Result<()>>` and map the `()` to `0i32` here

File: src/shims/unix/fd.rs [hunk 9]
```diff
@@ -169,10 +169,12 @@ impl FileDescriptor {
         FileDescriptor(Rc::new(RefCell::new(Box::new(fd))))
     }
 
-    pub fn close<'ctx>(self, communicate_allowed: bool) -> InterpResult<'ctx, io::Result<i32>> {
+    // Destroy this `Rc` using `into_inner` so we can call `close` instead of
+    // implicitly running the destructor of the file description.
```
Comment (RalfJung) [inline src/shims/unix/fd.rs:173]: The comment was meant to go inside the function, not outside it.

Github has a handy button to apply these suggestions so you don;t have to copy-paste them. :)

File: src/shims/unix/fd.rs (hunk 8 above)
Comment (RalfJung) [inline src/shims/unix/fd.rs:329]:
```suggestion
            let result = result.map(|()| 0i32);
```
This makes sure we notice if the argument type becomes something else that we do not want to throw away

File: src/shims/unix/fd.rs [hunk 10]
```diff
@@ -234,14 +236,14 @@ impl FdTable {
         new_fd
     }
 
-    pub fn get(&self, fd: i32) -> Option<Ref<'_, Box<dyn FileDescription>>> {
+    pub fn get(&self, fd: i32) -> Option<Ref<'_, dyn FileDescription>> {
         let fd = self.fds.get(&fd)?;
-        Some(fd.0.as_ref().borrow())
+        Some(Ref::map(fd.0.as_ref().borrow(), |fd| fd.as_ref()))
```
Comment (RalfJung) [inline src/shims/unix/fd.rs:241]: The first `as_ref` should be unnecessary, `Rc` auto-derefs

**Comment by RalfJung** [comment]
Awesome, I think we're done. :)

Please squash the commits together.

**Comment by RalfJung** [comment]
Thanks a lot!

@bors r+

**Comment by RalfJung** [comment]
@Luv-Ray a possible next step, if you want, would be to give `read` and `write` access to `ecx: &mut InterpCx<'mir, 'tcx, MiriMachine<'mir, 'tcx>>`. This will be needed in the future to support blocking on these operations.

To make that work out in terms of borrowing, I think what we will have to do is clone the `Rc` in the `read`/`write` functions in `unix/fd.rs`, so that we have a fully owned `FileDescriptor` next to a uniquely borrowed `InterpCx`.

**Comment by Luv-Ray** [comment]
Thanks for review! I think I can give it a try on the next step.
