### PR TITLE
Don't use `MIRI_DEFAULT_ARGS` to compile host crates

### LINKED ISSUE #1760: undefined symbol: miri_resolve_frame
I just installed* miri and wanted to try it before adding a stage to the github actions.
But executing `cargo +nightly miri test` on [asn1rs](https://github.com/kellerkindt/asn1rs/) throws the following error:

```bash
error: /tmp/cargo-target/debug/deps/libasn1rs_macros-398599e648a8b772.so: undefined symbol: miri_resolve_frame
 --> asn1rs/src/lib.rs:5:1
  |
5 | pub extern crate asn1rs_macros as macros;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `asn1rs`

To learn more, run the command again with --verbose.
```
```bash
$ cargo +nightly miri test --version
miri 0.1.0 (12dac5c 2021-03-17)
```

*like that
```bash
$ rustup +nightly component add miri
$ cargo +nightly miri test
I will run `"/home/...../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "install" "xargo"` to install a recent enough xargo. Proceed? [Y/n] y
    Updating crates.io index
  Downloaded xargo v0.3.22
...
```

### PR DESCRIPTION
**Pull request by hyd-dev**
They (specifically, `--cfg=miri`) may cause procedural macros (and probably build scripts) to depend on Miri-only symbols, such as `miri_resolve_frame`.

This PR makes `miri` detect host crates inspecting the value of the `MIRI_BE_RUSTC` environment variable (`target` -> target crate, `host` -> host crate, other -> panic) and skip the insertion of `MIRI_DEFAULT_ARGS` if it's a host crate.

Fixes #1760

### CODE REVIEW

File: src/bin/miri.rs [hunk 1]
```diff
@@ -170,7 +176,15 @@ fn main() {
...
         let mut callbacks = rustc_driver::TimePassesCallbacks::default();
-        run_compiler(env::args().collect(), &mut callbacks)
+        run_compiler(
+            env::args().collect(),
+            &mut callbacks,
+            // Don't insert `MIRI_DEFAULT_ARGS`, in particular, `--cfg=miri`, if we are building a
+            // "host" crate. That may cause procedural macros (and probably build scripts) to depend
+            // on Miri-only symbols, such as `miri_resolve_frame`:
+            // https://github.com/rust-lang/miri/issues/1760
+            env::args().skip(1).any(|arg| arg == "--target"),
```
Comment (RalfJung) [inline src/bin/miri.rs:186]: Doesn't `cargo miri` already know if this is a crate built for interpretation vs for the host? Would it be easier to forward that information instead of re-computing it by checking for a command-line flag?

Comment (RalfJung) [reply src/bin/miri.rs:186]: I imagine something like `MIRI_BE_RUSTC=host` disabling the arguments.

File: src/bin/miri.rs [hunk 2]
```diff
@@ -300,5 +314,5 @@ fn main() {
 
     debug!("rustc arguments: {:?}", rustc_args);
     debug!("crate arguments: {:?}", miri_config.args);
-    run_compiler(rustc_args, &mut MiriCompilerCalls { miri_config })
+    run_compiler(rustc_args, &mut MiriCompilerCalls { miri_config }, true)
```
Comment (RalfJung) [inline src/bin/miri.rs:317]:
```suggestion
    run_compiler(rustc_args, &mut MiriCompilerCalls { miri_config }, /* insert_default_args: */ true)
```

**Comment by hyd-dev** [comment]
```
thread 'rustc' panicked at 'no callback found', src/thread.rs:714:55
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: core::option::Option<T>::expect
             at /Users/runner/.rustup/toolchains/master/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: miri::thread::EvalContextExt::run_timeout_callback
             at ./src/thread.rs:714:13
   5: miri::eval::eval_main::{{closure}}
             at ./src/eval.rs:230:21
   6: miri::eval::eval_main
             at ./src/eval.rs:218:38
   7: <miri::MiriCompilerCalls as rustc_driver::Callbacks>::after_analysis::{{closure}}
             at ./src/bin/miri.rs:53:40
   8: rustc_interface::passes::QueryContext::enter::{{closure}}
             at /Users/runner/.rustup/toolchains/master/lib/rustlib/src/rust/compiler/rustc_interface/src/passes.rs:755:42
   9: rustc_middle::ty::context::tls::enter_context::{{closure}}
             at /Users/runner/.rustup/toolchains/master/lib/rustlib/src/rust/compiler/rustc_middle/src/ty/context.rs:1726:50
  10: rustc_middle::ty::context::tls::set_tlv
             at /Users/runner/.rustup/toolchains/master/lib/rustlib/src/rust/compiler/rustc_middle/src/ty/context.rs:1710:9
  11: rustc_middle::ty::context::tls::enter_context
             at /Users/runner/.rustup/toolchains/master/lib/rustlib/src/rust/compiler/rustc_middle/src/ty/context.rs:1726:9
  12: rustc_interface::passes::QueryContext::enter
             at /Users/runner/.rustup/toolchains/master/lib/rustlib/src/rust/compiler/rustc_interface/src/passes.rs:755:9
  13: <miri::MiriCompilerCalls as rustc_driver::Callbacks>::after_analysis
             at ./src/bin/miri.rs:35:9
  14: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  15: rustc_span::with_source_map
  16: rustc_interface::interface::create_compiler_and_run
  17: scoped_tls::ScopedKey<T>::set
```
:thinking:

**Comment by hyd-dev** [comment]
This looks like a strange timer issue... I don't think it's related to this PR though.

**Comment by RalfJung** [comment]
It somehow managed to trigger this line

https://github.com/rust-lang/miri/blob/7b2e325728e800664e55a7b91bac8b8b8378ab74/src/thread.rs#L714

That... should not be possible? We have some non-determinism somewhere...

File: cargo-miri/bin.rs [hunk 3]
```diff
@@ -420,7 +420,7 @@ path = "lib.rs"
     } else {
         command.env("RUSTC", &cargo_miri_path);
     }
-    command.env("MIRI_BE_RUSTC", "1");
+    command.env("MIRI_BE_RUSTC", "target");
```
Comment (RalfJung) [inline cargo-miri/bin.rs:423]: Please also adjust the README where this env var is documented.

File: src/bin/miri.rs [hunk 4]
```diff
@@ -166,11 +172,25 @@ fn main() {
...
+            // "host" crate. That may cause procedural macros (and probably build scripts) to depend
+            // on Miri-only symbols, such as `miri_resolve_frame`:
+            // https://github.com/rust-lang/miri/issues/1760
+            if crate_kind == "target" {
+                true
+            } else if crate_kind == "host" {
+                false
+            } else {
+                panic!("invalid `MIRI_BE_RUSTC` value: {:?}", crate_kind)
+            }
```
Comment (RalfJung) [inline src/bin/miri.rs:192]: Can you move this logic into `let insert_default_args = ...`? Currently it is not very clear what those booleans values mean.

File: src/bin/miri.rs [hunk 5]
```diff
@@ -166,11 +172,25 @@ fn main() {
...
+        run_compiler(
+            env::args().collect(),
+            &mut callbacks,
+            // Don't insert `MIRI_DEFAULT_ARGS`, in particular, `--cfg=miri`, if we are building a
+            // "host" crate. That may cause procedural macros (and probably build scripts) to depend
+            // on Miri-only symbols, such as `miri_resolve_frame`:
+            // https://github.com/rust-lang/miri/issues/1760
+            if crate_kind == "target" {
+                true
+            } else if crate_kind == "host" {
```
Comment (RalfJung) [inline src/bin/miri.rs:188]: You can probably turn this `if ... else` chain into a `match`. :)

File: test-cargo-miri/build.rs [hunk 6]
```diff
@@ -1,5 +1,10 @@
 #![feature(llvm_asm)]
 
+use std::env;
+
+#[cfg(miri)]
+compile_error!("`miri` cfg should not be set");
```
Comment (RalfJung) [inline test-cargo-miri/build.rs:6]:
```suggestion
compile_error!("`miri` cfg should not be set in build script");
```

File: test-cargo-miri/issue-1760/build.rs [hunk 7]
```diff
@@ -0,0 +1,9 @@
+use std::env;
+
+#[cfg(miri)]
+compile_error!("`miri` cfg should not be set");
```
Comment (RalfJung) [inline test-cargo-miri/issue-1760/build.rs:4]:
```suggestion
compile_error!("`miri` cfg should not be set in build script");
```

File: test-cargo-miri/issue-1760/src/lib.rs [hunk 8]
```diff
@@ -0,0 +1,9 @@
+use proc_macro::TokenStream;
+
+#[cfg(miri)]
+compile_error!("`miri` cfg should not be set");
```
Comment (RalfJung) [inline test-cargo-miri/issue-1760/src/lib.rs:4]:
```suggestion
compile_error!("`miri` cfg should not be set in proc_macro");
```

File: test-cargo-miri/build.rs [hunk 9]
```diff
@@ -11,6 +16,8 @@ fn not_in_miri() -> i32 {
 
 fn main() {
     not_in_miri();
+    // Make sure `--print=cfg` lists `miri`.
```
Comment (RalfJung) [inline test-cargo-miri/build.rs:19]: What is that `--print=cfg` that your tests keep talking about?

Comment (hyd-dev) [reply test-cargo-miri/build.rs:19]: I mean `miri --print=cfg`:
```
$ miri --print=cfg
debug_assertions
miri
...
$ MIRI_BE_RUSTC=host miri --print=cfg
debug_assertions
panic="unwind"
...
```
https://github.com/rust-lang/miri/blob/7b2e325728e800664e55a7b91bac8b8b8378ab74/cargo-miri/bin.rs#L647

I think Cargo interpret that output to set `CARGO_CFG_*` environment variables: https://doc.rust-lang.org/nightly/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts

Maybe I should write "`miri --print=cfg`"?

Comment (RalfJung) [reply test-cargo-miri/build.rs:19]: I did not know about `CARGO_CFG_`. The `--print` part seems like an implementation detail, but a relevant one for getting this right in Miri. So maybe briefly explain that in the comment?
```
// Cargo calls `miri --print=cfg` to populate the `CARGO_CFG_*` env vars; make sure that the "miri" flag is set.
```
(or "is not set for proc macros")

File: src/bin/miri.rs (hunk 5 above)
Comment (RalfJung) [reply src/bin/miri.rs]: Ah, bummer. Fair.

File: README.md [hunk 10]
```diff
@@ -286,9 +286,14 @@ Moreover, Miri recognizes some environment variables:
 The following environment variables are internal, but used to communicate between
 different Miri binaries, and as such worth documenting:
 
-* `MIRI_BE_RUSTC` when set to any value tells the Miri driver to actually not
-  interpret the code but compile it like rustc would. This is useful to be sure
-  that the compiled `rlib`s are compatible with Miri.
+* `MIRI_BE_RUSTC` can be set to `host` or `target`. It tells the Miri driver to
+  actually not interpret the code but compile it like rustc would. `host` tells it
```
Comment (RalfJung) [inline README.md:290]: IMO it'd be clearer to make a positive statement, not a negative one:

> With `target`, miri sets some compiler flags to prepare the code for interpretation; with `host`, this is not done.

**Comment by RalfJung** [comment]
This is great, thanks a lot. :-)
Can you squash the commits together a bit? Then I'll land it.

**Comment by hyd-dev** [comment]
Squashed. :rocket:

**Comment by RalfJung** [comment]
@bors r+
:ship:
