### PR TITLE
Move test suite to ui tests and bless stderr output

### LINKED ISSUE #2027: Switch compile-fail tests to ui tests
Currently, we use the `compile-fail` mode of `compiletest` for our "expected to fail" tests. rustc has switched to `ui` a long time ago, and it probably would make sense for Miri to follow suit. That would also unblock https://github.com/rust-lang/miri/pull/2015.

https://github.com/rust-lang/miri/pull/1977 finally makes this feasible by hiding libstd internals from the default stacktraces.

However, besides making sure we can actually get compiletest to do this properly (miri's needs are somewhat special), we also need to figure out how to support something like `--bless`. Clippy might be a good template here.

ui tests would also make it much easier to evaluate PRs like https://github.com/rust-lang/miri/pull/1971.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #2027

* [ ] //~ annotations should check that the error happens on their line
* [x] document all the things

### CODE REVIEW

**Comment by oli-obk** [comment]
I reverted the directory moves for now

**Comment by oli-obk** [comment]
hmm... gotta figure out how to handle the optimized stderr

File: cargo-miri/bin.rs [hunk 1]
```diff
@@ -461,7 +461,10 @@ path = "lib.rs"
     command.env_remove("RUSTFLAGS");
     // Disable debug assertions in the standard library -- Miri is already slow enough.
     // But keep the overflow checks, they are cheap.
-    command.env("RUSTFLAGS", "-Cdebug-assertions=off -Coverflow-checks=on");
+    command.env(
+        "RUSTFLAGS",
+        "-Cdebug-assertions=off -Coverflow-checks=on -Zremap-cwd-prefix=rustc_src",
```
Comment (RalfJung) [inline cargo-miri/bin.rs:466]: Does the regular std build also do this?
Either way, please extend the comment above to explain this flag.

File: tests/compiletest.rs [hunk 2]
```diff
@@ -43,24 +44,16 @@ fn run_tests(mode: &str, path: &str, target: &str) {
     config.src_base = PathBuf::from(path);
     config.target = target.to_owned();
     config.target_rustcflags = Some(flags);
+    if let Ok(_) = env::var("MIRI_BLESS") {
```
Comment (RalfJung) [inline tests/compiletest.rs:47]:
```suggestion
    if env::var_os("MIRI_BLESS").is_some() {
```

Comment (RalfJung) [reply tests/compiletest.rs:47]: Also the env var should be documented in the README.

File: tests/run-pass/backtrace-api.stderr [hunk 3]
```diff
@@ -3,16 +3,16 @@ $DIR/backtrace-api.rs:12:50 (func_c)
...
-RUSTLIB/std/src/panicking.rs:LL:COL (std::panicking::r#try::do_call)
-RUSTLIB/std/src/panicking.rs:LL:COL (std::panicking::r#try)
-RUSTLIB/std/src/panic.rs:LL:COL (std::panic::catch_unwind)
-RUSTLIB/std/src/rt.rs:LL:COL (std::rt::lang_start_internal::{closure#2})
-RUSTLIB/std/src/panicking.rs:LL:COL (std::panicking::r#try::do_call)
-RUSTLIB/std/src/panicking.rs:LL:COL (std::panicking::r#try)
-RUSTLIB/std/src/panic.rs:LL:COL (std::panic::catch_unwind)
-RUSTLIB/std/src/rt.rs:LL:COL (std::rt::lang_start_internal)
-RUSTLIB/std/src/rt.rs:LL:COL (std::rt::lang_start)
+rustc_src/src/ops/function.rs:227:5 (<fn() as std::ops::FnOnce<()>>::call_once - shim(fn()))
```
Comment (RalfJung) [inline tests/run-pass/backtrace-api.stderr:6]: Looks like this line also needs to be adjusted to avoid leaking the line numbers:
https://github.com/rust-lang/miri/blob/5e3be823b2d97a0e7411ee34bd02df38f5f35b92/tests/run-pass/backtrace-api.rs#L2

File: miri [hunk 4]
```diff
@@ -123,10 +123,15 @@ build|build-debug)
     cargo build $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/Cargo.toml "$@"
     cargo build $CARGO_BUILD_FLAGS --manifest-path "$MIRIDIR"/cargo-miri/Cargo.toml "$@"
     ;;
-test|test-debug)
+test|test-debug|bless|bless-debug)
```
Comment (RalfJung) [inline miri:126]: Please also document this (in CONTRIBUTING.md, probably)

**Comment by RalfJung** [comment]
> hmm... gotta figure out how to handle the optimized stderr

Ah, yeah, that has been a problem sometimes even with compile-fail and is a lot worse with `ui`.
Can we somehow tell compiletest to check the error annotations but not the reference files? Worst case, tell it to bless and un-do the blessing afterwards...

**Comment by RalfJung** [comment]
We'll also have to normalize Alloc IDs and SB Tags in many places. Is there a way to add a "default normalizer" to compiletest so we don't have to add the same `normalize-stderr` to dozens of tests?

File: cargo-miri/bin.rs (hunk 1 above)
Comment (oli-obk) [reply cargo-miri/bin.rs:466]: Well, no, but the regular rust build doesn't rebuild libstd on every machine 😄

This flag exists for reproducible builds and is used by linux distros

**Comment by oli-obk** [comment]
> We'll also have to normalize Alloc IDs and SB Tags in many places. Is there a way to add a "default normalizer" to compiletest so we don't have to add the same `normalize-stderr` to dozens of tests?

Yea, I haven't figured this out yet.. maybe I can add something to the miri binary instead that filters all the stderr output

**Comment by RalfJung** [comment]
Is patching compiletest an option? Shouldn't be too hard to add a new field to [the config struct](https://github.com/laumann/compiletest-rs/blob/c41ebe974231f0b96bdadffc3b2a274b17fb3515/src/common.rs#L107) and using that to [initialize TestProps](https://github.com/laumann/compiletest-rs/blob/51df6a780bcf57ad9aa933cab98fc762051b0239/src/header.rs#L286).

**Comment by bjorn3** [comment]
> Anyway, right now we have a problem: paths to the sysroot are flaky, as they depend on where your sysroot is. Gotta figure out how rustc handles this.

You can set the `CFG_VIRTUAL_RUST_SOURCE_BASE_DIR` env var to the sysroot source path. Compiletest will then replace `virtual_rust_source_base_dir.join("library")` with the literal `$SRC_DIR`. At least that is the case with the compiletest version of rustc. I'm not sure if it also works with the version from crates.io. Maybe it needs a different way to configure this.

**Comment by RalfJung** [comment]
@oli-obk what are your plans for this? I would love to see this happen. :)

**Comment by oli-obk** [comment]
I talked with pnkfelix about it yesterday. I'm going to add default filters to compiletest, and once that is merged, bump the crates.io version and then we can set some default filters here. That'll probably take a bit tho

**Comment by RalfJung** [comment]
Sounds like a great plan. :)

compiletest-rs is quite far behind the rustc version, FWIW. As in, many years. Doing a bump might be more like re-doing the extraction from scratch rather than updating the existing thing...

**Comment by oli-obk** [comment]
> compiletest-rs is quite far behind the rustc version, FWIW. As in, many years. Doing a bump might be more like re-doing the extraction from scratch rather than updating the existing thing...

oof yea, I looked at this. And remembered I tried this before... Not sure what the best way forward is, but I think this is a larger project. I don't want to do the change just in the crates.io version, but re-doing a sync when it's just going to get out of sync again is also not great.

**Comment by RalfJung** [comment]
Yeah, just doing the change on crates.io is where I would have started. It's terrible but I have up my hopes for this getting back in sync.^^

Or we go the low-tech way and simply have a common prelude in all our test files, and some ad-hoc hacky scripts to update it when needed...

**Comment by oli-obk** [comment]
Now I just gotta get back `//~ ERROR` annotations and we're good to go..

**Comment by oli-obk** [comment]
@RalfJung once I get all the targets working, I would like to merge this. While there are still minor bugs that I want to fix before merging, there is one major missing feature that I need to fix: `//~` annotations do not check that the diagnostic happened on the line, just that it happened. Fixing this is not a problem, but it still requires a bit of work. Merging now will avoid forcing me to keep maintaining and rebasing this branch until everything works.

Opinions?

**Comment by oli-obk** [comment]
🚀 CI is passing.

I'll see if it still works if we run it from within the rustc repo

**Comment by oli-obk** [comment]
ok, it doesn't work, but only because ui tests are changing in tiny ways. maybe we just don't check stderr files in rustc CI?

**Comment by oli-obk** [comment]
This is ready for review (passes miri CI and rustc CI)

**Comment by RalfJung** [comment]
> ok, it doesn't work, but only because ui tests are changing in tiny ways. maybe we just don't check stderr files in rustc CI?

How are they changing?
We should at least check the `ERROR` annotations in rustc. Not checking the full ui test seems fine, since we have the cronjob.

File: CONTRIBUTING.md [hunk 5]
```diff
@@ -89,6 +89,16 @@ MIRI_LOG=rustc_mir::interpret=info,miri::stacked_borrows ./miri run tests/run-pa
 In addition, you can set `MIRI_BACKTRACE=1` to get a backtrace of where an
 evaluation error was originally raised.
 
+#### UI testing
+
+We use ui-testing in miri, meaning we generate `.stderr` and `.stdout` files for the output
```
Comment (RalfJung) [inline CONTRIBUTING.md:94]:
```suggestion
We use ui-testing in Miri, meaning we generate `.stderr` and `.stdout` files for the output
```
Same for the rest of the new text.

File: CONTRIBUTING.md [hunk 6]
```diff
@@ -89,6 +89,16 @@ MIRI_LOG=rustc_mir::interpret=info,miri::stacked_borrows ./miri run tests/run-pa
...
+produced by miri. You can use `./miri bless` to automatically (re)generate these files when
+you add new tests or change how miri presents certain output.
+
+Note that when you also use `MIRIFLAGS` to change optimizations and similar, the ui output
+will change in unexpected ways, so we ignore that output for now. In order to still be able
+to run the other checks, use `MIRI_SKIP_UI_CHECKS=1 ./miri test`.
```
Comment (RalfJung) [inline CONTRIBUTING.md:100]: "we ignore that output for now" sounds like the test runner will automatically ignore the output when MIRIFLAGS is set, but that is not what you mean, right?
```suggestion
will change in unexpected ways. In order to still be able
to run the other checks while ignoring the ui output, use `MIRI_SKIP_UI_CHECKS=1 ./miri test`.
```

**Comment by oli-obk** [comment]
> We should at least check the `ERROR` annotations in rustc. Not checking the full ui test seems fine, since we have the cronjob.

This is what I do.

The changes are just some minor things where we now show spans in libstd because the paths are available. I know we also have them here, so I don't know why that makes a difference

File: tests/compiletest.rs [hunk 7]
```diff
@@ -1,71 +1,432 @@
...
-        config.compile_lib_path = PathBuf::from(lib_path);
-    }
-    config.filters = env::args().nth(1).into_iter().collect();
-    config.host = get_host();
-    config.src_base = PathBuf::from(path);
-    config.target = target.to_owned();
-    config.target_rustcflags = Some(flags);
-    compiletest::run_tests(&config);
-}
+    let grab_entries =
```
Comment (RalfJung) [inline tests/compiletest.rs:50]: There's a lot of new code here without many comments. Please add some comments explaining what is going on.

File: tests/compiletest.rs [hunk 8]
```diff
@@ -1,71 +1,432 @@
...
+                    }
+                    // Only look at .rs files
+                    if let Some(ext) = path.extension() {
+                        if ext != "rs" {
+                            continue;
+                        }
+                    } else {
+                        continue;
+                    }
+                    total.fetch_add(1, Ordering::Relaxed); // Read rules for skipping from file
```
Comment (RalfJung) [inline tests/compiletest.rs:78]: I don't understand the comment. Who is reading which rules here as part of the `fetch_add`?

File: tests/compiletest.rs [hunk 9]
```diff
@@ -1,71 +1,432 @@
...
+    OutputDiffers {
+        path: PathBuf,
+        actual: String,
+        expected: String,
+    },
+}
+
+type Errors = Vec<Error>;
+
+fn revisions(path: &Path) -> Vec<String> {
```
Comment (RalfJung) [inline tests/compiletest.rs:163]: So we have a mini test runner lib here now. :D
Seems fine, I guess, but could this be a separate file from the "driver" logic?

File: tests/compiletest.rs [hunk 10]
```diff
@@ -1,71 +1,432 @@
...
+                        let (m, errors) = run_test(&path, &target, &flags, mode, &revision);
 
-fn compile_fail(path: &str, target: &str) {
+                        eprint!("{} .. ", path.display());
+                        if errors.is_empty() {
+                            eprintln!("{}", "ok".green());
+                        } else {
+                            eprint!("{}", "FAILED".red().bold());
+                            if !revision.is_empty() {
+                                eprint!(" (revision `{}`)", revision);
```
Comment (RalfJung) [inline tests/compiletest.rs:93]: Why do we show the revision only if it failed? And after the state?
I would have expected something more like `{path.display()} (revision: {revision}) .. {status}`

File: tests/compiletest.rs [hunk 11]
```diff
@@ -1,71 +1,432 @@
...
+    revision: &str,
+) -> (Command, Errors) {
+    // Run miri
+    let mut miri = Command::new(miri_path());
+    miri.args(flags.iter());
+    miri.arg(path);
+    if !revision.is_empty() {
+        miri.arg(format!("--cfg={revision}"));
+    }
+    miri.env("RUSTC_BACKTRACE", "0");
```
Comment (RalfJung) [inline tests/compiletest.rs:187]: Why this?

File: tests/compiletest.rs [hunk 12]
```diff
@@ -1,71 +1,432 @@
...
+            extension.to_string()
+        } else {
+            format!("{}.{}", revision, extension)
+        }
+    };
+    let stderr = check_output(&output.stderr, path, &mut errors, revised("stderr"), target);
+    check_output(&output.stdout, path, &mut errors, revised("stdout"), target);
+    let require = match mode {
+        Mode::Pass => false,
+        Mode::Panic => false, // Should we do anything here?
```
Comment (RalfJung) [inline tests/compiletest.rs:203]: "require" what? What might we even do here?

File: tests/compiletest.rs [hunk 13]
```diff
@@ -1,71 +1,432 @@
...
+    path: &Path,
+    stderr: &str,
+    errors: &mut Errors,
+    require: bool,
+    revision: &str,
+) {
+    let content = std::fs::read_to_string(path).unwrap();
+    let mut found_annotation = false;
+    let regex =
+        Regex::new("//(\\[(?P<revision>[^\\]]+)\\])?~[\\^|]*\\s*(ERROR|HELP|WARN)?:?(?P<text>.*)")
```
Comment (RalfJung) [inline tests/compiletest.rs:220]: This might be more readable with raw strings, avoiding all the `\\`

Comment (RalfJung) [reply tests/compiletest.rs:220]: Also regexps don't usually do escaping inside `[...]`, so it should be `[^|]` I think.

File: tests/compiletest.rs [hunk 14]
```diff
@@ -1,71 +1,432 @@
...
+    for line in content.lines() {
+        if let Some(s) = line.strip_prefix("// error-pattern:") {
+            let s = s.trim();
+            if !stderr.contains(s) {
+                errors.push(Error::PatternNotFound(s.to_string()));
+            }
+            found_annotation = true;
+        }
+        if let Some(captures) = regex.captures(line) {
+            // FIXME: check that the error happens on the marked line
```
Comment (RalfJung) [inline tests/compiletest.rs:231]: Please open an issue for this.

File: tests/compiletest.rs [hunk 15]
```diff
@@ -1,71 +1,432 @@
...
+    if actual == expected {
+        return;
+    }
+    eprintln!("actual output differed from expected {}", path.display());
+    eprintln!("{}", pretty_assertions::StrComparison::new(expected, actual));
+    eprintln!()
+}
+
+fn ignore_file(p: &Path, target: &str) -> bool {
+    let content = std::fs::read_to_string(p).unwrap();
```
Comment (RalfJung) [inline tests/compiletest.rs:302]: Wow how often do we read the same file into a string?^^

File: tests/compiletest.rs [hunk 16]
```diff
@@ -1,71 +1,432 @@
...
+    for line in content.lines() {
+        if let Some(s) = line.strip_prefix("// ignore-") {
```
Comment (RalfJung) [inline tests/compiletest.rs:304]: Please document somewhere the magic annotations we support.

**Review by RalfJung — COMMENTED** [review]
I think I am okay with the overall strategy. Effectively forking the part of compiletest that we care about is probably a good call, though I would like to see it a bit more isolated from the other preexisting code in our test suite. I left a bunch of comments, mostly asking for more comments and docs. :)

I will try to scroll over the diff in `tests/` as well to see if anything stands out, but GH doesn't render that so I'll probably check it out locally for that.

File: tests/compile-fail/extern_static.stderr [hunk 17]
```diff
@@ -0,0 +1,14 @@
+error: unsupported operation: `extern` static FOO is not supported by Miri
```
Comment (RalfJung) [inline tests/compile-fail/extern_static.stderr:1]: Given such an error, how do I figure out which crate defined this static and where?
The old output handled that nicely...

File: tests/run-fail/panic/unsupported_syscall.rs [hunk 18]
```diff
@@ -1,5 +1,5 @@
 // ignore-windows: No libc on Windows
-// ignore-macos: `syscall` is not supported on macOS
+// ignore-apple: `syscall` is not supported on macOS
```
Comment (RalfJung) [inline tests/run-fail/panic/unsupported_syscall.rs:2]: Why do we use a different syntax that compiletest here?
Will it at least complain when it sees `ignore-foo` and doesn't understand "foo"?

File: tests/run-pass/stacked-borrows/generators-self-referential.rs [hunk 19]
```diff
@@ -13,7 +13,7 @@ fn firstn() -> impl Generator<Yield = u64, Return = ()> {
         let num = &mut num;
 
         yield *num;
-        *num += 1; //~ ERROR: borrow stack
+        *num += 1; // would fail here borrow stack
```
Comment (RalfJung) [inline tests/run-pass/stacked-borrows/generators-self-referential.rs:16]:
```suggestion
        *num += 1; // would fail here
```

**Comment by RalfJung** [comment]
> This is what I do.
>
> The changes are just some minor things where we now show spans in libstd because the paths are available. I know we also have them here, so I don't know why that makes a difference

Ah, so that will be hard to normalize as well.
Spans in libstd are weird, yeah... but seems fine now to do as you suggest. :+1:

File: tests/compiletest.rs [hunk 20]
```diff
@@ -1,71 +1,432 @@
...
+    // erase thread caller ids
+    "\\(call [0-9]+\\)"              => "(call ID)",
+    // erase platform module paths
+    "sys::[a-z]+::"                  => "sys::PLATFORM::",
+    // Windows file paths
+    "\\\\"                           => "/",
+    // erase platform file paths
+    "sys/[a-z]+/"                    => "sys/PLATFORM/",
+    // erase error annotations in tests
+    "\\s*//~.*"                      => "",
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply tests/compiletest.rs:393]: Compiletest does this, too. Otherwise spans that cross such comments show the comments in,stderr

File: tests/compiletest.rs [hunk 21]
```diff
@@ -1,71 +1,432 @@
...
+    // erase borrow stack indices
+    "<[0-9]+>"                       => "<BORROW_IDX>",
+    // erase whitespace that differs between platforms
+    " +at (.*\\.rs)"                 => " at $1",
+    // erase generics in backtraces
+    "([0-9]+: .*)::<.*>"             => "$1",
+    // erase addresses in backtraces
+    "([0-9]+: ) +0x[0-9a-f]+ - (.*)" => "$1$2",
+    // erase hexadecimals
+    "0x[0-9a-fA-F]+(\\[a[0-9]+\\])?" => "$$HEX",
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply tests/compiletest.rs:379]: Hard to distinguish and not always true with alignment and such

File: tests/compiletest.rs (hunk 8 above)
Comment (oli-obk) [reply tests/compiletest.rs:78]: Huh... not sure what I meant

File: tests/compiletest.rs (hunk 9 above)
Comment (oli-obk) [reply tests/compiletest.rs:163]: I want to make it a separate crate entirely

File: tests/compiletest.rs (hunk 11 above)
Comment (oli-obk) [reply tests/compiletest.rs:187]: This is what happened before. Otherwise locally setting the env var influences ui test output

File: tests/compiletest.rs [hunk 22]
```diff
@@ -1,71 +1,432 @@
...
+                }
+            }
+
+            if !stderr.contains(matched) {
+                errors.push(Error::InlinePatternNotFound(matched.to_string()));
+            }
+            found_annotation = true;
+        }
+    }
+    if found_annotation != require {
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply tests/compiletest.rs:246]: Oh yea, I should distinguish those cases.

File: tests/compiletest.rs (hunk 15 above)
Comment (oli-obk) [reply tests/compiletest.rs:302]: Oh right, I was worried about this and it may in fact affect perf

File: tests/compiletest.rs (hunk 20 above)
[the remark this answers is not in the document]
Comment (RalfJung) [reply tests/compiletest.rs:393]: Yeah but that doesn't cause spurious differences though?

It does look odd though, so -- makes sense.

File: tests/compiletest.rs (hunk 21 above)
[the remark this answers is not in the document]
Comment (RalfJung) [reply tests/compiletest.rs:379]: Can you add a FIXME and an issue (or make it part of a larger tracking issue) to make this more targeted? It is a shame to no longer test the precise offsets/values that we used to test.

File: tests/compiletest.rs (hunk 9 above)
Comment (RalfJung) [reply tests/compiletest.rs:163]: Sure, though short-term it's nice to have this in-tree. But making it a separate file would help with reviewing so it would make sense to do that before landing IMO.

File: tests/compiletest.rs (hunk 11 above)
Comment (RalfJung) [reply tests/compiletest.rs:187]: Happened before where? In compiletest?
```suggestion
    // Tests should work even when people have that env var set.
    miri.env("RUSTC_BACKTRACE", "0");
```

File: tests/run-fail/panic/unsupported_syscall.rs (hunk 18 above)
Comment (RalfJung) [reply tests/run-fail/panic/unsupported_syscall.rs:2]: I guess if the target actually says "apple" rather than "macos" then "ingore-apple" actually makes more sense...

File: tests/compiletest.rs (hunk 9 above)
Comment (oli-obk) [reply tests/compiletest.rs:163]: Oh, I did mean a separate crate in tree. Just so I can write unit tests for the test runner itself

File: tests/compiletest.rs (hunk 8 above)
Comment (oli-obk) [reply tests/compiletest.rs:78]: oh it belongs to the next line 🤦

File: tests/compiletest.rs (hunk 13 above)
Comment (oli-obk) [reply tests/compiletest.rs:220]: `[^x]` means all characters except for `x` as `^` is the inverter for these

Comment (oli-obk) [reply tests/compiletest.rs:220]: But using raw strings was definitely better

Comment (RalfJung) [reply tests/compiletest.rs:220]: Ah right, but I don't think `\` has any effect in `[`. So make it `[|^]` then.

File: CONTRIBUTING.md [hunk 23]
```diff
@@ -92,12 +92,12 @@ evaluation error was originally raised.
 #### UI testing
 
 We use ui-testing in miri, meaning we generate `.stderr` and `.stdout` files for the output
-produced by miri. You can use `./miri bless` to automatically (re)generate these files when
+produced by Miri. You can use `./miri bless` to automatically (re)generate these files when
 you add new tests or change how miri presents certain output.
```
Comment (RalfJung) [inline CONTRIBUTING.md:96]:
```suggestion
you add new tests or change how Miri presents certain output.
```

File: cargo-miri/bin.rs [hunk 24]
```diff
@@ -461,6 +461,8 @@ path = "lib.rs"
     command.env_remove("RUSTFLAGS");
     // Disable debug assertions in the standard library -- Miri is already slow enough.
     // But keep the overflow checks, they are cheap.
+    // Also remap the current directory to something that is reliably across different
```
Comment (RalfJung) [inline cargo-miri/bin.rs:464]:
```suggestion
    // Also remap the current directory to something that is stable across different
```

File: tests/compiletest.rs [hunk 25]
```diff
@@ -465,8 +121,7 @@ fn main() {
     // Panic tests expect backtraces to be printed.
     env::set_var("RUST_BACKTRACE", "1");
 
-    let target = get_target();
-    ui(Mode::Pass, "tests/run-pass", &target);
-    ui(Mode::Panic, "tests/run-fail", &target);
-    ui(Mode::UB, "tests/compile-fail", &target);
+    ui(Mode::Pass, "tests/run-pass");
+    ui(Mode::Panic, "tests/run-fail");
+    ui(Mode::UB, "tests/compile-fail");
```
Comment (RalfJung) [inline tests/compiletest.rs]: Looking at the names of the folders, maybe we should call the variants `RunFail` and `CompileFail`?

Though "compile-fail" is not  a great name and we should probably rename the folder instead...

File: tests/compiletest.rs [hunk 26]
```diff
@@ -41,317 +37,23 @@ fn run_tests(mode: Mode, path: &str, target: &str) {
...
+    let config = Config {
+        args: flags,
+        target,
+        stderr_filters: REGEXES.clone(),
+        stdout_filters: REGEXES.clone(),
+        root_dir: PathBuf::from(path),
+        mode,
+        program: miri_path(),
+        bless: env::var_os("MIRI_BLESS").is_some(),
+        skip_output_checks: env::var_os("MIRI_SKIP_UI_CHECKS").is_some(),
```
Comment (RalfJung) [inline tests/compiletest.rs:54]: Please document these env vars in the README as well, like we do with all the others.

File: ui_test/src/lib.rs [hunk 27]
```diff
@@ -410,9 +409,9 @@ pub enum Mode {
 
 impl Mode {
     fn ok(self, status: ExitStatus) -> Errors {
-        match (status.success(), self) {
-            (false, Mode::UB) | (false, Mode::Panic) | (true, Mode::Pass) => vec![],
-            (true, Mode::Panic) | (true, Mode::UB) | (false, Mode::Pass) =>
+        match (status.code().unwrap(), self) {
+            (1, Mode::UB) | (101, Mode::Panic) | (0, Mode::Pass) => vec![],
+            (_, Mode::Panic) | (_, Mode::UB) | (_, Mode::Pass) =>
```
Comment (RalfJung) [inline ui_test/src/lib.rs]:
```suggestion
            _ =>
```

File: tests/compiletest.rs [hunk 28]
```diff
@@ -123,5 +128,5 @@ fn main() {
 
     ui(Mode::Pass, "tests/run-pass");
     ui(Mode::Panic, "tests/run-fail");
-    ui(Mode::UB, "tests/compile-fail");
+    ui(Mode::Fail, "tests/compile-fail");
```
Comment (RalfJung) [inline tests/compiletest.rs:131]: So what about "pass", "panic", and "fail" for the folder names?

File: tests/run-fail/panic/unsupported_syscall.rs (hunk 18 above)
Comment (oli-obk) [reply tests/run-fail/panic/unsupported_syscall.rs:2]: yea, the ignore/only flags are essentially checking for substrings in the target triple.

File: tests/compiletest.rs (hunk 25 above)
Comment (RalfJung) [reply tests/compiletest.rs]: > I didn't want to cause the folder renaming churn.

Fair, we can leave that to a separate PR.

> I want run-pass, run-panic and run-fail

The "run" part looks rather redundant in these names...

Comment (oli-obk) [reply tests/compiletest.rs]: yeaaa... we don't really have compile-fail tests, so leaving out the run part makes sense

File: tests/compiletest.rs (hunk 21 above)
[the remark this answers is not in the document]
Comment (oli-obk) [reply tests/compiletest.rs]: I set it up so that the stderr output does not contain this, but the error patterns work on the unnormalized stderr, giving us back a way to test these

[the remark this answers is not in the document]
Comment (RalfJung) [reply tests/compiletest.rs]: I think we can maybe also do something where only hex numbers at least 4 digits long are normalized? That would still cover "invalid pointer 0xdaf130", but would allow "error at offset 0x10" to persist.

**Comment by oli-obk** [comment]
I addressed all review comments

File: tests/compiletest.rs [hunk 29]
```diff
@@ -1,82 +1,123 @@
...
 fn miri_path() -> PathBuf {
     PathBuf::from(option_env!("MIRI").unwrap_or(env!("CARGO_BIN_EXE_miri")))
 }
 
-fn run_tests(mode: &str, path: &str, target: &str) {
+fn run_tests(mode: Mode, path: &str, target: Option<String>) {
     let in_rustc_test_suite = option_env!("RUSTC_STAGE").is_some();
+
+    if in_rustc_test_suite {
+        std::env::set_var("MIRI_SKIP_UI_CHECKS", "1");
```
Comment (RalfJung) [inline tests/compiletest.rs:15]: Given that `env::set_var` is a troubled API, and that the intended recipient of this flag is this very same function -- can you avoid this, and instead `set` this in the rustc bootstrap code?

File: ui_test/README.md [hunk 30]
```diff
@@ -0,0 +1,20 @@
...
+
+## Supported magic comment annotations
+
+* `// ignore-XXX` avoids running the test on targets whose triple contains `XXX`
+    * `XXX` can also be one of `64bit`, `32bit` or `16bit`
+* `// only-XXX` avoids running the test on targets whose triple **does not** contain `XXX`
+    * `XXX` can also be one of `64bit`, `32bit` or `16bit`
+* `// stderr-per-bitwidth` produces one stderr file per bitwidth, as they max differ significantly sometimes
+* `// error-pattern: XXX` make sure the stderr output contains `XXX`
+* `//~ ERROR: XXX` make sure the stderr output contains `XXX` for an error in the line where this comment is written
```
Comment (RalfJung) [inline ui_test/README.md:11]: So this has actually been implemented now? :D
If not, please mention that here.

File: ui_test/README.md [hunk 31]
```diff
@@ -0,0 +1,20 @@
...
+    * Also supports `HELP` or `WARN` for different kind of message
+    * if the all caps note is left out, defaults to `ERROR`
+* `// revisions: XXX YYY` runs the test once for each space separated name in the list
+    * emits one stderr file per revision
+    * `//~` comments can be restricted to specific revisions by adding the revision name before the `~` in square brackets: `//[XXX]~`
+* `// compile-flags: XXX` appends `XXX` to the command line arguments passed to the rustc driver
+* `// rustc-env: XXX=YYY` sets the env var `XXX` to `YYY` for the rustc driver execution.
+    * for Miri this is equivalent to setting env vars for the program execution
```
Comment (RalfJung) [inline ui_test/README.md:19]: I don't understand this comment.

File: ui_test/src/comments.rs [hunk 32]
```diff
@@ -0,0 +1,111 @@
...
+
+                let revision = captures.name("revision").map(|rev| rev.as_str().to_string());
+                this.error_matches.push(ErrorMatch { matched, revision, definition_line: l });
+            }
+        }
+        this
+    }
+}
+
+pub struct ErrorMatch {
```
Comment (RalfJung) [inline ui_test/src/comments.rs:107]: Please move the type definitions together at the top of the file.

File: ui_test/src/lib.rs [hunk 33]
```diff
@@ -0,0 +1,414 @@
...
+                while let Some(path) = todo.pop() {
+                    // Collect everything inside directories
+                    if path.is_dir() {
+                        for entry in std::fs::read_dir(path).unwrap() {
+                            todo.push(entry.unwrap().path());
+                        }
+                        continue;
+                    }
+                    // Only look at .rs files
+                    if let Some(ext) = path.extension() {
```
Comment (RalfJung) [inline ui_test/src/lib.rs:65]: `if !path.extension().map(|ext| ext == "rs").unwrap_or(false)` seems more elegant than having `continue` twice.

File: ui_test/src/lib.rs [hunk 34]
```diff
@@ -0,0 +1,414 @@
...
+                        if ext != "rs" {
+                            continue;
+                        }
+                    } else {
+                        continue;
+                    }
+                    total.fetch_add(1, Ordering::Relaxed);
+                    let comments = Comments::parse(&path);
+                    // Read rules for skipping from file
```
Comment (RalfJung) [inline ui_test/src/lib.rs:74]: We are not "reading" those rules here any more, right? Just interpreting them.

File: ui_test/src/lib.rs [hunk 35]
```diff
@@ -0,0 +1,414 @@
...
+    let path = output_path(path, comments, kind, target);
+    if config.bless {
+        if output.is_empty() {
+            let _ = std::fs::remove_file(path);
+        } else {
+            std::fs::write(path, &output).unwrap();
+        }
+    } else {
+        let expected_output = std::fs::read_to_string(&path).unwrap_or_default();
+        if !config.skip_output_checks {
```
Comment (RalfJung) [inline ui_test/src/lib.rs:311]:
```suggestion
    } else if !config.skip_output_checks {
        let expected_output = std::fs::read_to_string(&path).unwrap_or_default();
         {
```
and then remove the unnecessary nested scope

File: tests/compiletest.rs [hunk 36]
```diff
@@ -87,7 +128,7 @@ fn main() {
     // Panic tests expect backtraces to be printed.
     env::set_var("RUST_BACKTRACE", "1");
```
Comment (RalfJung) [inline tests/compiletest.rs:129]: Lol, so we set it to "1" here and then reset it to "0" in the ui_test library? :joy: 
Can we just remove the `set_var` here? Avoiding that API would be better anyway.

File: CONTRIBUTING.md [hunk 37]
```diff
@@ -89,6 +89,16 @@ MIRI_LOG=rustc_mir::interpret=info,miri::stacked_borrows ./miri run tests/run-pa
...
 
+#### UI testing
+
+We use ui-testing in Miri, meaning we generate `.stderr` and `.stdout` files for the output
+produced by Miri. You can use `./miri bless` to automatically (re)generate these files when
+you add new tests or change how Miri presents certain output.
+
+Note that when you also use `MIRIFLAGS` to change optimizations and similar, the ui output
+will change in unexpected ways. In order to still be able
+to run the other checks while ignoring the ui output, use `MIRI_SKIP_UI_CHECKS=1 ./miri test`.
```
Comment (RalfJung) [inline CONTRIBUTING.md:100]: Please add a link to `ui_test/README.md`

File: ui_test/src/lib.rs [hunk 38]
```diff
@@ -0,0 +1,414 @@
...
+                eprintln!();
+            }
+            if let Some(stderr) = dump_stderr {
+                eprintln!("actual stderr:");
+                eprintln!("{}", stderr);
+                eprintln!();
+            }
+        }
+        eprintln!(
+            "{} tests failed, {} tests passed, {} skipped",
```
Comment (RalfJung) [inline ui_test/src/lib.rs:150]: This can be potentially confusing since for "total" and "skipped" we count a test with many revisions as 1, but for failures we count it as multiple tests.

File: ui_test/src/lib.rs (hunk 35 above)
Comment (RalfJung) [reply ui_test/src/lib.rs:311]: Though thinking about it, maybe skip_output_checks should take precedence over config.bless?

File: ui_test/src/lib.rs [hunk 39]
```diff
@@ -0,0 +1,414 @@
...
+}
+
+fn output_path(path: &Path, comments: &Comments, kind: String, target: &str) -> PathBuf {
+    if comments.stderr_per_bitwidth {
+        return path.with_extension(format!("{}.{kind}", get_pointer_width(target)));
+    }
+    path.with_extension(kind)
+}
+
+fn compare_output(path: &Path, actual: &str, expected: &str) {
```
Comment (RalfJung) [inline ui_test/src/lib.rs:330]: This is only called when the output differs and we are printing that error, right?
Please pick a function name that better reflects that, or add a doc comment, or both.
Also the "if actual == expectd" seems off then?

File: ui_test/src/lib.rs [hunk 40]
```diff
@@ -0,0 +1,414 @@
...
+    eprintln!("{}", pretty_assertions::StrComparison::new(expected, actual));
+    eprintln!()
+}
+
+fn ignore_file(comments: &Comments, target: &str) -> bool {
+    for s in &comments.ignore {
+        if target.contains(s) {
+            return true;
+        }
+        if get_pointer_width(target).contains(s) {
```
Comment (RalfJung) [inline ui_test/src/lib.rs:344]: Why "contains"?

**Review by RalfJung — COMMENTED** [review]
Generally looks great! I left a bunch of comments/nits on the ui test library. I didn't re-check the test output itself; that part is probably easier to tweak post-landing. I also didn't check the details of how the library prints test failures, and the comment parsing. It seems to work well enough for now. :)

File: ui_test/src/comments.rs [hunk 41]
```diff
@@ -0,0 +1,111 @@
...
+                this.compile_flags.extend(s.split_whitespace().map(|s| s.to_string()));
+            }
+            if let Some(s) = line.strip_prefix("// rustc-env:") {
+                for env in s.split_whitespace() {
+                    if let Some((k, v)) = env.split_once('=') {
+                        this.env_vars.push((k.to_string(), v.to_string()));
+                    }
+                }
+            }
+            if let Some(s) = line.strip_prefix("// normalize-stderr-test") {
```
Comment (RalfJung) [inline ui_test/src/comments.rs:79]: Why does this not have a ":" but all the others do?
In rustc it can optionally have a colon. If we make it mandatory for all other options here, IMO we should do that for this option as well.

File: ui_test/README.md [hunk 42]
```diff
@@ -0,0 +1,20 @@
...
+* `// normalize-stderr-test "REGEX" "REPLACEMENT"` replaces all matches of `REGEX` in the stderr with `REPLACEMENT`. The replacement may specify `$1` and similar backreferences to paste captures.
```
Comment (RalfJung) [inline ui_test/README.md:20]: Isn't it "REGEX -> REPLACEMENT"? The arrow is missing.

File: ui_test/src/comments.rs (hunk 41 above)
Comment (oli-obk) [reply ui_test/src/comments.rs:79]: "backcompat"... I just tried to replicate what the test suite does and look into consistency later.

File: ui_test/src/lib.rs (hunk 35 above)
Comment (oli-obk) [reply ui_test/src/lib.rs:311]: I wasn't sure about what to do here. I'll just error if you specify both.

File: ui_test/README.md [hunk 43]
```diff
@@ -0,0 +1,20 @@
...
+
+* `// ignore-XXX` avoids running the test on targets whose triple contains `XXX`
+    * `XXX` can also be one of `64bit`, `32bit` or `16bit`
+* `// only-XXX` avoids running the test on targets whose triple **does not** contain `XXX`
+    * `XXX` can also be one of `64bit`, `32bit` or `16bit`
+* `// stderr-per-bitwidth` produces one stderr file per bitwidth, as they max differ significantly sometimes
+* `// error-pattern: XXX` make sure the stderr output contains `XXX`
+* `//~ ERROR: XXX` make sure the stderr output contains `XXX` for an error in the line where this comment is written
+    * Also supports `HELP` or `WARN` for different kind of message
+    * if the all caps note is left out, defaults to `ERROR`
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply ui_test/README.md:13]: 😆 well, I thought that's what it did, nevermind then, removing the comment

**Comment by oli-obk** [comment]
Addressed all comments and rebased (no squashing or other history editing)

File: ui_test/src/lib.rs (hunk 35 above)
Comment (RalfJung) [reply ui_test/src/lib.rs]: > I'll just error if you specify both.

Good idea. :)

File: ui_test/README.md [hunk 44]
```diff
@@ -0,0 +1,30 @@
...
+Note that the space after `//`, when it is present, is *not* optional -- it must be exactly one.
+
+* `// ignore-XXX` avoids running the test on targets whose triple contains `XXX`
+    * `XXX` can also be one of `64bit`, `32bit` or `16bit`
+* `// only-XXX` avoids running the test on targets whose triple **does not** contain `XXX`
+    * `XXX` can also be one of `64bit`, `32bit` or `16bit`
+* `// stderr-per-bitwidth` produces one stderr file per bitwidth, as they may differ significantly sometimes
+* `// error-pattern: XXX` make sure the stderr output contains `XXX`
+* `//~ ERROR: XXX` make sure the stderr output contains `XXX` for an error in the line where this comment is written
+    * NOTE: it is not checked at present that it is actually in the line where the error occurred, but you should treat it as such until that becomes true.
```
Comment (RalfJung) [inline ui_test/README.md:14]:
```suggestion
    * NOTE: it is not checked at present that it is actually in the line where the error occurred, or that it is truly an ERROR/WARNING/HELP/NOTE, but you should treat it as such until that becomes true.
```

File: ui_test/src/lib.rs [hunk 45]
```diff
@@ -0,0 +1,410 @@
...
+                        comments.revisions.clone().unwrap_or_else(|| vec![String::new()])
+                    {
+                        let (m, errors) = run_test(&path, &config, &target, &revision, &comments);
+
+                        // Using `format` to prevent messages from threads from getting intermingled.
+                        let mut msg = format!("{} ", path.display());
+                        if !revision.is_empty() {
+                            write!(msg, "(revision `{revision}`) ").unwrap();
+                        }
+                        write!(msg, " .. ").unwrap();
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply ui_test/src/lib.rs:94]: I am fairly certain, considering the output is correct XD

[the remark this answers is not in the document]
Comment (RalfJung) [reply ui_test/src/lib.rs:94]: Looking at the macro, `$dst.write_fmt`. So I guess it auto-borrows. TIL.
