### PR TITLE
fix: avoid stopping machine upon running env operations in isolation

### LINKED ISSUE #1034: Improve handling of failed operations in isolation mode
Currently, we abort program execution when we try access the external environment in isolation mode. However, `libstd` currently calls `getcwd` when printing out a panic backtrace. To ensure that panicking works in isolation mode, we've disabled the call to `getcwd` when `libstd` has `cfg(miri)` enabled.

Eventually, it would be good to rmeove this hack, and start returning proper error codes from disabled functions, rather than aborting the process.

See https://github.com/rust-lang/rust/pull/60026#discussion_r342257352 for more discussion

### PR DESCRIPTION
**Pull request by atsmtat**
get and set current dir operations used to halt the machine by
throwing an exception in isolation mode. This change updates them to
return a dummy `NotFound` error instead, and keep the machine running.

I started with a custom error using `ErrorKind::Other`, but since it
can't be mapped to a raw OS error, I dropped it. `NotFound` kind of make
sense for get operations, but not much for set operations. But that's
the only error supported for windows currently.

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks for the PR!

I recall suggesting something similar in the past, but the concern back then was that we should do this consistently for all operations. So this certainly does not fix #1034, as there are more operations that would need adjustment (getenv/setenv, all the file system operations -- basically everything that checks the `communicate` flag).

The other concern was discoverability: when such an operation fails, it can be hard for users to figure out why, since they might not expect the "isolation" Miri provides. I am not sure what is the best solution to this. Maybe keep the errors by default but offer a flag to let evaluation continue instead? I am not sure what your usecase is here so I cannot tell if that would help you or not.

Cc @oli-obk

**Comment by RalfJung** [comment]
Cc @Aaron1011

**Comment by oli-obk** [comment]
> Maybe keep the errors by default but offer a flag to let evaluation continue instead? I am not sure what your usecase is here so I cannot tell if that would help you or not.

We could turn the errors into warnings and possibly add a flag to turn them off entirely (which the warning could then mention)

**Comment by atsmtat** [comment]
What to do with the rest of the operations was gonna be my next question based on the feedback 🙂 I'll drop "fixes" line so that issue is not closed.
This PR is not to fix any use case I have, so I'm not really blocked or anything. Having fun learning Rust, and out of interest in compilers, I'm trying to learn about rustc and tools around it. I was digging into miri code, and found this easy issue to start with.

As for the question of discoverability, I'm trying to understand the problem:
- miri should never execute system calls in isolation mode, right?
- if miri were to continue execution of user program, it would have to either return an error or mimic the success call?
- if miri were to return a fake but sensible error for a given op (`PermissionDenied` for `getcwd` for example), with explicit message about "isolation" mode, isn't that OK? As user program might actually run into such error while running in the field.
- i assume that faking a success by returning a dummy for getter and no-op for setter is out of question, as it's just too evil?
- with a fake error, it's possible that user code doesn't take a path which user wants to exercise, and this might go unnoticed by the user. So we use warnings to point this out?
- i guess we don't expect users to refactor the code around these ops (handle an error and continue with dummy value for example) in order to run it in isolation?

**Comment by RalfJung** [comment]
> miri should never execute system calls in isolation mode, right?

Yes. (Even more strongly, Miri in isolation mode should be completely pure, deterministic, repeatable.)

> i assume that faking a success by returning a dummy for getter and no-op for setter is out of question, as it's just too evil?

Yes.

> if miri were to return a fake but sensible error for a given op (PermissionDenied for getcwd for example), with explicit message about "isolation" mode, isn't that OK? As user program might actually run into such error while running in the field.

Indeed I think this is a reasonable approach -- but I don't think we can return an "explicit message" to the caller, all we have is an error code. I assume a lot of code out there will `unwrap` `getcwd` immediately, or `?` it and bubble up the error in a nice way, but either way the program aborts quickly. It will look like the program is just broken under Miri, and the user has no idea to know that they just have to pass the flag to make things work.

So I like @oli-obk's proposal of having Miri itself print a warning (we already have infrastructure for that, see `NonHaltingDiagnostic` in `diag.rs` and, alternatively, [this warning](https://github.com/rust-lang/miri/blob/bcae3315a76876eb48e06519749cfe6e453a8e93/src/shims/posix/thread.rs#L18) upon spawning a thread). This is not something a "real" failing `getcwd` would ever do, but it seems okay.

So:
* Default behavior (with isolation on): print a warning (only on the first such call, ideally -- `sess.warn` does that automatically I think), then continue interpretation with a suitable error code.
* Isolation off: behavior unchanged compared to now.

At some point we might add a flag to suppress the warning, but that does not have to happen immediately.

**Comment by RalfJung** [comment]
>  But that's the only error supported for windows currently.

Supported where, in the Miri mapping to raw error codes? We can easily extend that. Which error could might a real Windows emit if the permission to change the current dir was denied?

**Comment by RalfJung** [comment]
@atsmtat I see you did a rebase; I am still setting the "waiting-on-author" flag based on the discussion above. If anything is unclear or if you think the ball is in our court and you need more feedback/review/help, please let me know. :)

**Comment by atsmtat** [comment]
> > miri should never execute system calls in isolation mode, right?
> 
> Yes. (Even more strongly, Miri in isolation mode should be completely pure, deterministic, repeatable.)
> 
> > i assume that faking a success by returning a dummy for getter and no-op for setter is out of question, as it's just too evil?
> 
> Yes.
> 
> > if miri were to return a fake but sensible error for a given op (PermissionDenied for getcwd for example), with explicit message about "isolation" mode, isn't that OK? As user program might actually run into such error while running in the field.
> 
> Indeed I think this is a reasonable approach -- but I don't think we can return an "explicit message" to the caller, all we have is an error code. I assume a lot of code out there will `unwrap` `getcwd` immediately, or `?` it and bubble up the error in a nice way, but either way the program aborts quickly. It will look like the program is just broken under Miri, and the user has no way to know that they just have to pass the flag to make things work.
> 
> So I like @oli-obk's proposal of having Miri itself print a warning (we already have infrastructure for that, see `NonHaltingDiagnostic` in `diag.rs` and, alternatively, [this warning](https://github.com/rust-lang/miri/blob/bcae3315a76876eb48e06519749cfe6e453a8e93/src/shims/posix/thread.rs#L18) upon spawning a thread). This is not something a "real" failing `getcwd` would ever do, but it seems okay.
> 
> So:
> 
>     * Default behavior (with isolation on): print a warning (only on the first such call, ideally -- `sess.warn` does that automatically I think), then continue interpretation with a suitable error code.
> 
Yes, I tried out `sess.warn`, and it prints warning only on the first call (does session mean a single run of a user program?). One downside of `sess.warn` is that it doesn't give user much idea about which code/line caused that call. I'm trying to see if I can print more info in the warning.

>     * Isolation off: behavior unchanged compared to now.
> 
> 
> At some point we might add a flag to suppress the warning, but that does not have to happen immediately.

**Comment by atsmtat** [comment]
> > But that's the only error supported for windows currently.
> 
> Supported where, in the Miri mapping to raw error codes? We can easily extend that. Which error code might a real Windows emit if the permission to change the current dir was denied?

Right, Miri mapping to raw error codes. I'll add appropriate Windows error codes.

**Comment by atsmtat** [comment]
What do you think about a warning with a span like this:
```
warning: `chdir` called in isolation mode returns a dummy error
   --> /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:158:17
    |
158 |     if unsafe { libc::chdir(p.as_ptr()) } != 0 {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^

```
I got the span from the top frame. Still not very helpful. Good to print user frame which calls into std. Is there a way to get such frame or it doesn't make sense? If you can point out an example where something like this is done, it'll be great.

**Comment by bjorn3** [comment]
> Yes, I tried out sess.warn, and it prints warning only on the first call

Diagnostics are deduplicated, so if the warning message is identical, it will only be printed once.

**Comment by RalfJung** [comment]
> Yes, I tried out sess.warn, and it prints warning only on the first call

Yes that was deliberate -- we don't want tons of warnings when a program does such a call in a loop.
However, it looks like you also want to show a span. In that case you'll want to register a `NonHaltingDiagnostic` with Miri's diagnostic infrastructure (see `diagnostic.rs`); however, then you'll have to add your own logic to avoid showing the error many times.

**Comment by atsmtat** [comment]
> > Yes, I tried out sess.warn, and it prints warning only on the first call
> 
> Yes that was deliberate -- we don't want tons of warnings when a program does such a call in a loop.
> However, it looks like you also want to show a span. In that case you'll want to register a `NonHaltingDiagnostic` with Miri's diagnostic infrastructure (see `diagnostic.rs`); however, then you'll have to add your own logic to avoid showing the error many times.

Looks like `NonHaltingDiagnostic` uses the same diagnostic infra, which dedups the messages. So it shows a single message per line in src. But because it's too verbose to print the backtrace by default, I pushed a change to throw a warning without a span or backtrace. This in fact prints a warning only once per a given op call. I'm considering adding two command line options on top of this  -- 1. track dummy errors in isolation, which prints backtraces using `NonHaltingDiagnostic` 2. ignore dummy errors in isolation, which doesn't print a warning.

I'll push these changes soon. Let me know what you think :)

**Comment by atsmtat** [comment]
@RalfJung I updated the PR with options for user visibility.
For input:
```rust
    assert_eq!(env::current_dir().unwrap_err().kind(), ErrorKind::NotFound);
    for _i in 0..3 {
        assert_eq!(env::current_dir().unwrap_err().kind(), ErrorKind::NotFound);
    }
```
Output of default run (with isolation, without any flags):
```
warning: `getcwd` in isolation mode produced a dummy error
  |
  = note: run with -Zmiri-track-dummy-op to track with a backtrace
  = note: run with -Zmiri-ignore-dummy-op to ignore warning
```

Output of run with `-Zmiri-track-dummy-op`:
```
note: tracking was triggered
   --> /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:134:17
    |
134 |             if !libc::getcwd(ptr, buf.capacity()).is_null() {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ produced dummy error for `getcwd`
    |
    = note: inside `std::sys::unix::os::getcwd` at /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:134:17
    = note: inside `std::env::current_dir` at /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/env.rs:47:5
note: inside `main` at tests/run-pass/current_dir_with_isolation.rs:7:16
   --> tests/run-pass/current_dir_with_isolation.rs:7:16
    |
7   |     assert_eq!(env::current_dir().unwrap_err().kind(), ErrorKind::NotFound);
    |                ^^^^^^^^^^^^^^^^^^
(frames omitted for brevity)

note: tracking was triggered
   --> /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:134:17
    |
134 |             if !libc::getcwd(ptr, buf.capacity()).is_null() {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ produced dummy error for `getcwd`
    |
    = note: inside `std::sys::unix::os::getcwd` at /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:134:17
    = note: inside `std::env::current_dir` at /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/env.rs:47:5
note: inside `main` at tests/run-pass/current_dir_with_isolation.rs:9:20
   --> tests/run-pass/current_dir_with_isolation.rs:9:20
    |
9   |         assert_eq!(env::current_dir().unwrap_err().kind(), ErrorKind::NotFound);
    |                    ^^^^^^^^^^^^^^^^^^
```


Running with `-Zmiri-ignore-dummy-op` doesn't produce any messaged related to dummy ops

File: src/bin/miri.rs [hunk 1]
```diff
@@ -236,6 +236,12 @@ fn main() {
                 "-Zmiri-track-raw-pointers" => {
                     miri_config.track_raw = true;
                 }
+                "-Zmiri-track-dummy-op" => {
+                    miri_config.dummy_op_visibility = miri::DummyOpVisibility::Track;
+                }
+                "-Zmiri-ignore-dummy-op" => {
+                    miri_config.dummy_op_visibility = miri::DummyOpVisibility::Hide;
+                }
```
Comment (RalfJung) [inline src/bin/miri.rs:244]: I don't think we should have two flags for this... also, "dummy op" is fairly unclear as a name.

I propose that instead we have a single flag, srawman name: `-Zmiri-isolated-op=<hide|warn|track>`. (I am not sure if "warn" vs "track" is a very meaningful difference here, I think it should be "warn" no matter the underlying implementation.) The underlying enum should probably also have a variant "allow" which corresponds to disabling isolation.

Comment (RalfJung) [reply src/bin/miri.rs:244]: > Looks like NonHaltingDiagnostic uses the same diagnostic infra, which dedups the messages. So it shows a single message per line in src. But because it's too verbose to print the backtrace by default, I pushed a change to throw a warning without a span or backtrace.

So maybe the values should be `<hide|warn|warn-nobacktrace|allow>`? (where the latter is equivalent to `-Zmiri-disable-isolation`)

File: src/diagnostics.rs [hunk 2]
```diff
@@ -279,6 +280,7 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
                     CreatedCallId(id) => format!("function call with id {}", id),
                     CreatedAlloc(AllocId(id)) => format!("created allocation with id {}", id),
                     FreedAlloc(AllocId(id)) => format!("freed allocation with id {}", id),
+                    DummyOpInIsolation(op) => format!("produced dummy error for `{}`", op),
```
Comment (RalfJung) [inline src/diagnostics.rs:283]: I don't know what you mean by "dummy" error. I suggest to say something more like "`{}` was made to return an error due to isolation" or so (and print a hint mentioning `-Zmiri-disable-isolation`).

**Comment by RalfJung** [comment]
> I wasn't sure about running rustfmt, so I haven't run it on my changes.

After rebasing onto latest master, running `rustfmt` should be fine.

> Output of default run (with isolation, without any flags):

In terms of deduplication, this looks great. :) I think we should adjust the messages a little. I don't think "note: tracking was triggered" makes sense, I'd more like to see something like "warning: operation rejected by isolation" or so.

File: src/bin/miri.rs (hunk 1 above)
Comment (atsmtat) [reply src/bin/miri.rs:244]: I used "dummy op" to represent a subset of ops which are faked in isolation. I'm fine with `-Zmiri-isolated-op`. 

> I think it should be "warn" no matter the underlying implementation

Do you mean to give user only two options - <hide|warn>, where `warn` prints backtraces, and without `-Zmiri-isolated-op` (by default), miri prints just a warning?

> The underlying enum should probably also have a variant "allow" which corresponds to disabling isolation.

Sorry, I didn't get this part. Presumably this variant controls isolation for such foreign ops (i.e. miri executes the op even in isolation), how does it get set? We provide one more option in `-Zmiri-isolated-op`? How is it different from `-Zmiri-disable-isolation`?

Comment (atsmtat) [reply src/bin/miri.rs:244]: I somehow missed your second comment, which clarifies my previous questions.
`-Zmiri-isolated-op=<hide|warn|warn-nobacktrace|allow>`, with `warn-nobacktrace` as default, sounds good to me. Will update the PR soon.

Comment (RalfJung) [reply src/bin/miri.rs:244]: Sorry, by "underlying enum" I meant the field in `MiriConfig`.

`-Zmiri-disable-isolation` would then be syntactic sugar for `-Zmiri-isolated-op=allow`.

> with warn-nobacktrace as default

I am honestly not sure if `warn` or `warn-nobacktrace` should be the default.

Comment (atsmtat) [reply src/bin/miri.rs:244]: > `-Zmiri-disable-isolation` would then be syntactic sugar for `-Zmiri-isolated-op=allow`

Is that so? Latter shouldn't change machine level `communicate` flag like the former do, right? I thought, when it's time to execute `chdir`, for example, we check for `machine.communicate || miri-config.isolated-op == allow`?

Comment (RalfJung) [reply src/bin/miri.rs:244]: When `communicate` is `true`, then the other isolated-op actions make no sense, right? It's always bad to have "nonesnsical" combinations. That's why I think this should be all one large enum.

What else would `-Zmiri-isolated-op=allow` means, when it is not the same as `-Zmiri-disable-isolation`?

>  we check for machine.communicate || miri-config.isolated-op == allow?

If we do that everywhere the `communicate` flag is used, we might as well remove that flag -- no?

Comment (atsmtat) [reply src/bin/miri.rs]: Ok, that makes sense. I wasn't sure if `communicate` has semantics other than just controlling isolated ops. I just pushed the change which captures all the settings in a single enum. For now, I've kept the `communicate` flag as it is, as it'd require touching more files. I'm not sure about the preference for smaller PRs. If you like the new changes and prefer to deprecate `communicate` in the same PR, I'd be happy to do 🙂

**Comment by atsmtat** [comment]
Updated output:
Default:
```
warning: `getcwd` was made to return an error due to isolation
  |
  = note: run with -Zmiri-isolated-op=warn to get warning with a backtrace
  = note: run with -Zmiri-isolated-op=hide to hide warning
  = note: run with -Zmiri-isolated-op=allow to disable isolation
```

With `warn`:
```
warning: operation rejected by isolation
   --> /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:134:17
    |
134 |             if !libc::getcwd(ptr, buf.capacity()).is_null() {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `getcwd` was made to return an error due to isolation
    |
    = note: inside `std::sys::unix::os::getcwd` at /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:134:17
    = note: inside `std::env::current_dir` at /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/env.rs:47:5
note: inside `main` at tests/run-pass/current_dir_with_isolation.rs:7:16
   --> tests/run-pass/current_dir_with_isolation.rs:7:16
    |
7   |     assert_eq!(env::current_dir().unwrap_err().kind(), ErrorKind::NotFound);
    |                ^^^^^^^^^^^^^^^^^^
...
warning: operation rejected by isolation
   --> /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:134:17
    |
134 |             if !libc::getcwd(ptr, buf.capacity()).is_null() {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `getcwd` was made to return an error due to isolation
    |
    = note: inside `std::sys::unix::os::getcwd` at /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:134:17
    = note: inside `std::env::current_dir` at /Users/atsmtat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/env.rs:47:5
note: inside `main` at tests/run-pass/current_dir_with_isolation.rs:9:20
   --> tests/run-pass/current_dir_with_isolation.rs:9:20
    |
9   |         assert_eq!(env::current_dir().unwrap_err().kind(), ErrorKind::NotFound);
    |                    ^^^^^^^^^^^^^^^^^^
```

**Comment by atsmtat** [comment]
> > I wasn't sure about running rustfmt, so I haven't run it on my changes.
> 
> After rebasing onto latest master, running `rustfmt` should be fine. We just recently made the repository rustfmt-compatible.
> 
How do I run `rustfmt` on miri? I couldn't add a component using rustup as it complains about a custom toolchain, miri.

> > Output of default run (with isolation, without any flags):
> 
> In terms of deduplication, this looks great. :) I think we should adjust the messages a little. I don't think "note: tracking was triggered" makes sense, I'd more like to see something like "warning: operation rejected by isolation" or so.

**Comment by RalfJung** [comment]
> How do I run rustfmt on miri? I couldn't add a component using rustup as it complains about a custom toolchain, miri.

`cargo +nightly fmt` should work, if you also have a nightly toolchain installed.

File: src/bin/miri.rs (hunk 1 above)
Comment (RalfJung) [reply src/bin/miri.rs]: It shouldn't have any other semantics.

I'd prefer not to have redundant option flags in the machine settings, so if you could e.g. replace `communicate` by `fn communicate()` or so, that would be great. :)

File: src/bin/miri.rs [hunk 3]
```diff
@@ -229,6 +229,7 @@ fn main() {
                 }
                 "-Zmiri-disable-isolation" => {
                     miri_config.communicate = true;
```
Comment (RalfJung) [inline src/bin/miri.rs:231]: That flag should also disappear from `miri_config`.

File: src/bin/miri.rs [hunk 4]
```diff
@@ -318,6 +319,19 @@ fn main() {
                     };
                     miri_config.cmpxchg_weak_failure_rate = rate;
                 }
+                arg if arg.starts_with("-Zmiri-isolated-op=") => {
+                    let action = match arg.strip_prefix("-Zmiri-isolated-op=").unwrap() {
+                        "hide" => miri::IsolatedOp::Reject(miri::RejectOpWith::NoWarning),
```
Comment (RalfJung) [inline src/bin/miri.rs:324]: I am not sure I like `hide` as name for "reject the operation, return error code, but do not print a warning"... but I don't have a better idea either. @oli-obk @bjorn3 @hyd-dev any suggestions?

File: src/eval.rs [hunk 5]
```diff
@@ -22,6 +22,29 @@ pub enum AlignmentCheck {
...
+    Warning,
+
+    /// Print a warning about rejected isolated op, without backtrace
+    WarningWithoutBacktrace,
+}
+
+#[derive(Copy, Clone, Debug)]
+pub enum IsolatedOp {
+    /// Reject op requiring communication with the host. Usually, miri
+    /// generates a fake error for such op, and prints a warning
```
Comment (RalfJung) [inline src/eval.rs:40]:
```suggestion
    /// return an error code for such op, and prints a warning
```

File: src/helpers.rs [hunk 6]
```diff
@@ -397,6 +397,26 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
         Ok(())
     }
 
+    /// Helper function used inside the shims of foreign functions which reject the op
+    /// when isolation is enabled. It is used to print a warning/backtrace about the rejection.
+    fn report_rejected_op(&self, op_name: &str, reject_with: RejectOpWith) {
```
Comment (RalfJung) [inline src/helpers.rs:402]: This seems to be overlapping in terms of functionality with `isolation_error`.

File: src/shims/env.rs [hunk 7]
```diff
@@ -321,20 +322,27 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
...
-        match env::current_dir() {
-            Ok(cwd) => {
-                if this.write_path_to_c_str(&cwd, buf, size)?.0 {
-                    return Ok(buf);
+        match this.machine.isolated_op {
+            IsolatedOp::Allow => {
+                let buf = this.read_scalar(&buf_op)?.check_init()?;
+                let size = this.read_scalar(&size_op)?.to_machine_usize(&*this.tcx)?;
+                // If we cannot get the current directory, we return null
+                match env::current_dir() {
```
Comment (RalfJung) [inline src/shims/env.rs:330]: I'd prefer if we could avoid the rightwards drift here.
Can you handle the "reject" case early and return, so that the rest of the function can proceed as before?

File: tests/run-pass/current_dir_with_isolation.rs [hunk 8]
```diff
@@ -0,0 +1,16 @@
+use std::env;
+use std::io::ErrorKind;
+
+fn main() {
+    // Test that current dir operations return the dummy error instead
```
Comment (RalfJung) [inline tests/run-pass/current_dir_with_isolation.rs:5]:
```suggestion
    // Test that current dir operations return a proper error instead
```

File: src/bin/miri.rs (hunk 4 above)
Comment (bjorn3) [reply src/bin/miri.rs:324]: Maybe return-error-code or something like that?

File: src/helpers.rs (hunk 6 above)
Comment (atsmtat) [reply src/helpers.rs:402]: It's still used by ops which panic in isolation, as they're not converted to return an error.

Comment (RalfJung) [reply src/helpers.rs:402]: Okay. But we should somehow reflect this in the code. Maybe add a FIXME at `isolation_error` saying that this only exists for old ops not yet converted to return a proper error code?

File: src/bin/miri.rs [hunk 9]
```diff
@@ -227,10 +227,6 @@ fn main() {
                 "-Zmiri-symbolic-alignment-check" => {
                     miri_config.check_alignment = miri::AlignmentCheck::Symbolic;
                 }
-                "-Zmiri-disable-isolation" => {
```
Comment (RalfJung) [inline src/bin/miri.rs:230]: Please don't remove this flag. It is very widely used, so this would break tons of projects' CI.

File: src/bin/miri.rs (hunk 4 above)
Comment (RalfJung) [reply src/bin/miri.rs:320]: Hm, but `warn`/`warn-nobacktrace` also return an error code so they should then have a similar name.

I am also wondering about the name of the flag itself... does "isolated" operation make sense? With "allow", it is not isolated any more, after all. Maybe "external" operation would be a better name? Any other suggestions?

File: src/bin/miri.rs (hunk 9 above)
Comment (atsmtat) [reply src/bin/miri.rs:230]: I misunderstood your previous comment about deleting the flag. Sorry about that. I restored the flag.

File: src/helpers.rs (hunk 6 above)
Comment (atsmtat) [reply src/helpers.rs:402]: Sure, done.

File: src/bin/miri.rs (hunk 4 above)
Comment (atsmtat) [reply src/bin/miri.rs:323]: I think merging the isolation switch setting and isolation error visibility setting into a single flag is causing the confusion. One more option is to use two flags, one to control isolation switch -- `-Zmiri-disable-isolation` (which already exists); one to control isolation error visibility -- `-Zmiri-isolation-error={ignore|warn|warn-nobacktrace}`.

File: src/bin/miri.rs (hunk 9 above)
Comment (RalfJung) [reply src/bin/miri.rs:230]: Oh I see what happened. Sorry for not being more clear.

File: src/bin/miri.rs (hunk 4 above)
Comment (RalfJung) [reply src/bin/miri.rs:323]: That idea is appealing, but then we have nonsensical combinations such as `-Zmiri-disable-isolation -Zmiri-isolation-error=ignore`.

Comment (atsmtat) [reply src/bin/miri.rs:323]: It shouldn't be too hard to catch such combinations in miri's cmd line parser and throw error about it.

Comment (atsmtat) [reply src/bin/miri.rs]: I updated the PR with a new flag `-Zmiri-isolation-error`.

File: src/bin/miri.rs [hunk 10]
```diff
@@ -203,6 +203,9 @@ fn main() {
     let mut miri_config = miri::MiriConfig::default();
     let mut rustc_args = vec![];
     let mut after_dashdash = false;
+
+    // If user has explicitly enabled isolation
```
Comment (RalfJung) [inline src/bin/miri.rs:207]:
```suggestion
    // If user has explicitly enabled/disabled isolation
```

File: src/bin/miri.rs [hunk 11]
```diff
@@ -228,7 +231,37 @@ fn main() {
                     miri_config.check_alignment = miri::AlignmentCheck::Symbolic;
                 }
                 "-Zmiri-disable-isolation" => {
-                    miri_config.communicate = true;
+                    if let Some(true) = isolation_enabled {
```
Comment (RalfJung) [inline src/bin/miri.rs:234]:
```suggestion
                    if matches!(isolation_enabled, Some(true)) {
```

File: src/bin/miri.rs [hunk 12]
```diff
@@ -228,7 +231,37 @@ fn main() {
...
+                        panic!(
+                            "-Zmiri-disable-isolation cannot be used along with -Zmiri-isolation-error"
+                        );
+                    } else {
+                        isolation_enabled = Some(false);
+                    }
+                    miri_config.isolated_op = miri::IsolatedOp::Allow;
+                }
+                arg if arg.starts_with("-Zmiri-isolation-error=") => {
+                    if let Some(false) = isolation_enabled {
```
Comment (RalfJung) [inline src/bin/miri.rs:244]:
```suggestion
                    if matches!(isolation_enabled, Some(false)) {
```

File: src/diagnostics.rs [hunk 13]
```diff
@@ -63,7 +71,7 @@ pub fn report_error<'tcx, 'mir>(
             #[rustfmt::skip]
             let helps = match info {
                 UnsupportedInIsolation(_) =>
-                    vec![format!("pass the flag `-Zmiri-disable-isolation` to disable isolation")],
+                    vec![format!("pass the flag `-Zmiri-disable-isolation` to disable isolation; or pass `-Zmiri-isolation-error=warn to configure miri to warn about isolation and continue instead of aborting")],
```
Comment (RalfJung) [inline src/diagnostics.rs:74]:
```suggestion
                    vec![format!("pass the flag `-Zmiri-disable-isolation` to disable isolation; or pass `-Zmiri-isolation-error=warn` to configure Miri to return an error code from isolated operations and continue with a warning")],
```

File: src/shims/env.rs [hunk 14]
```diff
@@ -321,21 +322,26 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
...
-        let size = this.read_scalar(&size_op)?.to_machine_usize(&*this.tcx)?;
-        // If we cannot get the current directory, we return null
-        match env::current_dir() {
-            Ok(cwd) => {
-                if this.write_path_to_c_str(&cwd, buf, size)?.0 {
-                    return Ok(buf);
+        if let IsolatedOp::Reject(reject_with) = this.machine.isolated_op {
+            this.reject_in_isolation("getcwd", reject_with)?;
+            let err = Error::new(ErrorKind::NotFound, "rejected due to isolation");
+            this.set_last_error_from_io_error(err)?;
```
Comment (RalfJung) [inline src/shims/env.rs:328]: Please return early in this branch, so that the code below does not have to be moved to the right.

File: src/shims/env.rs [hunk 15]
```diff
@@ -348,16 +354,22 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
...
-
-        // If we cannot get the current directory, we return 0
-        match env::current_dir() {
-            Ok(cwd) =>
-                return Ok(windows_check_buffer_size(this.write_path_to_wide_str(&cwd, buf, size)?)),
-            Err(e) => this.set_last_error_from_io_error(e)?,
+        if let IsolatedOp::Reject(reject_with) = this.machine.isolated_op {
+            this.reject_in_isolation("GetCurrentDirectoryW", reject_with)?;
+            let err = Error::new(ErrorKind::NotFound, "rejected due to isolation");
+            this.set_last_error_from_io_error(err)?;
```
Comment (RalfJung) [inline src/shims/env.rs:360]: Please return early in this branch, so that the code below does not have to be moved to the right.

File: src/shims/env.rs [hunk 16]
```diff
@@ -370,15 +382,21 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
...
         );
 
-        this.check_no_isolation("`chdir`")?;
+        if let IsolatedOp::Reject(reject_with) = this.machine.isolated_op {
+            this.reject_in_isolation("chdir", reject_with)?;
+            let err = Error::new(ErrorKind::NotFound, "rejected due to isolation");
+            this.set_last_error_from_io_error(err)?;
 
-        let path = this.read_path_from_c_str(this.read_scalar(path_op)?.check_init()?)?;
+            Ok(-1)
```
Comment (RalfJung) [inline src/shims/env.rs:390]: Please return early in this branch, so that the code below does not have to be moved to the right.

File: src/shims/env.rs [hunk 17]
```diff
@@ -393,15 +411,21 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
...
         this.assert_target_os("windows", "SetCurrentDirectoryW");
 
-        this.check_no_isolation("`SetCurrentDirectoryW`")?;
+        if let IsolatedOp::Reject(reject_with) = this.machine.isolated_op {
+            this.reject_in_isolation("SetCurrentDirectoryW", reject_with)?;
+            let err = Error::new(ErrorKind::NotFound, "rejected due to isolation");
+            this.set_last_error_from_io_error(err)?;
 
-        let path = this.read_path_from_wide_str(this.read_scalar(path_op)?.check_init()?)?;
+            Ok(0)
```
Comment (RalfJung) [inline src/shims/env.rs:419]: Please return early in this branch, so that the code below does not have to be moved to the right.

File: tests/run-pass/current_dir_with_isolation.stderr [hunk 18]
```diff
@@ -0,0 +1,12 @@
+warning: `getcwd` was made to return an error due to isolation
+  |
+  = note: run with -Zmiri-isolation-error=warn to get warning with a backtrace
+  = note: run with -Zmiri-isolation-error=ignore to hide warning
+  = note: run with -Zmiri-disable-isolation to disable isolation
```
Comment (RalfJung) [inline tests/run-pass/current_dir_with_isolation.stderr:5]: The point of the "nobacktrace" option is to not clutter the screen so much... so is it really a good idea to print all these notes?
They are not printed with `=warn`, are they?

File: src/bin/miri.rs [hunk 19]
```diff
@@ -228,7 +231,37 @@ fn main() {
...
+                        panic!(
+                            "-Zmiri-isolation-error cannot be used along with -Zmiri-disable-isolation"
+                        );
+                    } else {
+                        isolation_enabled = Some(true);
+                    }
+
+                    miri_config.isolated_op = match arg
+                        .strip_prefix("-Zmiri-isolation-error=")
```
Comment (RalfJung) [inline src/bin/miri.rs:253]: The new option needs to be documented in the README.

File: src/bin/miri.rs [hunk 20]
```diff
@@ -228,7 +231,37 @@ fn main() {
...
+                        .unwrap()
+                    {
+                        "abort" => miri::IsolatedOp::Reject(miri::RejectOpWith::Abort),
+                        "ignore" => miri::IsolatedOp::Reject(miri::RejectOpWith::NoWarning),
```
Comment (RalfJung) [inline src/bin/miri.rs:257]: I think we should rename "ignore", but I am not sure what to rename it to... maybe "hide"? I want it to be clear that isolation is still enforced.

File: tests/run-pass/current_dir_with_isolation.stderr (hunk 18 above)
Comment (atsmtat) [reply tests/run-pass/current_dir_with_isolation.stderr:5]: Agreed, it's a bit verbose. But given that it's printed only once out of N `getcwd` ops, I thought it might be user-friendly to print notes about the possible actions. I can drop the notes if you like.
Yes, they are not printed with `=warn`. But note that `=warn` prints a trace per line where `getcwd` is called.

File: src/bin/miri.rs (hunk 20 above)
Comment (atsmtat) [reply src/bin/miri.rs:257]: Listing out options I could think of:
- `-Zmiri-isolation-error=hide`
- `-Zmiri-isolation-error=no-warn`
- `-Zmiri-isolation-error=silent`

Comment (atsmtat) [reply src/bin/miri.rs:257]: One more
`-Zmiri-isolation-error=Shh..I_know_what_I_am_doing` 😄

File: tests/run-pass/current_dir_with_isolation.stderr (hunk 18 above)
Comment (RalfJung) [reply tests/run-pass/current_dir_with_isolation.stderr:5]: `warn` also goes through the rustc diagnostic system, so shouldn't it deduplicate?

I find it unlikely that someone would set this to `warn-nobacktrace` without having read the docs, and if they have read the docs then they will know the other options.

File: tests/run-pass/current_dir_with_isolation.stderr [hunk 21]
```diff
@@ -0,0 +1,12 @@
+warning: `getcwd` was made to return an error due to isolation
```
Comment (RalfJung) [inline tests/run-pass/current_dir_with_isolation.stderr:1]: This fails on Windows because the output is different there.
Can you add `// normalize-stderr-test` comments to the test file to make sure the output is the same across platforms? It should look something like this
```
// normalize-stderr-test "(getcwd|GetCurrentDirectoryW)" -> "$$FUN"
```

File: tests/run-pass/current_dir_with_isolation.stderr (hunk 18 above)
Comment (atsmtat) [reply tests/run-pass/current_dir_with_isolation.stderr:5]: I'm not sure how exactly deduping works, but my guess is -- since `warn` option prints a span that includes a location, only the calls from a given file+line location get deduped. Vs. `warn-nobacktrace` doesn't print a span, so all the calls from different locations are considered duplicates (because of the same message content?) and hence deduped.

I started with the intention of having default behaviour (`warn-nobacktrace` earlier) less verbose but with enough info about possible actions. Now that we've moved to default behaviour being `abort`, yes, it makes less sense to print notes. I'll drop the notes.

Comment (RalfJung) [reply tests/run-pass/current_dir_with_isolation.stderr:5]: > I started with the intention of having default behaviour (warn-nobacktrace earlier) less verbose but with enough info about possible actions. Now that we've moved to default behaviour being abort, yes, it makes less sense to print notes. I'll drop the notes.

Ah, yes, that makes sense. If we ever make this the default, we should reconsider this. :)

**Comment by atsmtat** [comment]
@RalfJung I've addressed your latest comments in recent commits. I believe you'd prefer I squash my branch commits. If so, let me know.

File: src/bin/miri.rs (hunk 20 above)
Comment (RalfJung) [reply src/bin/miri.rs:320]: From the proposals so far, I think I prefer "hide", so shall we go with that?

**Comment by RalfJung** [comment]
LGTM, assuming CI passes and pending the rename of "ignore". :)

**Comment by RalfJung** [comment]
Ah, and yes please squash the commits.

**Comment by atsmtat** [comment]
I renamed "ignore" and squashed the commits. Waiting for your approval to run CI.

File: src/shims/env.rs [hunk 22]
```diff
@@ -321,7 +322,12 @@ pub trait EvalContextExt<'mir, 'tcx: 'mir>: crate::MiriEvalContextExt<'mir, 'tcx
             "`getcwd` is only available for the UNIX target family"
         );
 
-        this.check_no_isolation("`getcwd`")?;
+        if let IsolatedOp::Reject(reject_with) = this.machine.isolated_op {
+            this.reject_in_isolation("getcwd", reject_with)?;
+            let err = Error::new(ErrorKind::NotFound, "rejected due to isolation");
```
Comment (RalfJung) [inline src/shims/env.rs:327]: Ah, I forgot about one discussion we had: didn't we say this should be `PermissionDenied`? And some `match` for windows error conversions should be extended?

If you don't want to do this now, please leave FIXME in the code to change the error type.

Comment (RalfJung) [reply src/shims/env.rs:327]: Also we should probably change `set_last_error_from_io_error` to take an error kind so that we don't have to make up a string here. But that, too, could be a separate PR if you prefer.

Sorry I forgot about these things in my last round of review.

Comment (hyd-dev) [reply src/shims/env.rs:327]: > so that we don't have to make up a string here.

I believe you could also use `Error::from(ErrorKind::...)` or `ErrorKind::....into()` to avoid the string:
https://doc.rust-lang.org/nightly/std/io/struct.Error.html#impl-From%3CErrorKind%3E

Comment (RalfJung) [reply src/shims/env.rs:327]: But is there even any reason that `set_last_error_from_io_error` would take more than an `ErrorKind`?

Comment (atsmtat) [reply src/shims/env.rs:327]: I specifically used `Error::new` as it allows custom payload for error not originated from OS. Quoting its documentation -- `This function is used to generically create I/O errors which do not originate from the OS itself.`. Shouldn't we use a custom message indicating that the problem is due to isolation so that user doesn't confuse it with an actual OS error? Or the intention is to make the distinction not clear?

As for which code to generate, yes, I mentioned using `PermissionDenied` earlier. But then, if it's a bogus error, does it matter?

For Windows code, I didn't want to mix it with this PR which is mainly about adding this new setup. I'll create a new PR for it. Also, we still have quite a few shims using old "always abort" setup, which I was planning to convert in next PR(s). Otherwise this new flag isn't very useful 🙂

Comment (hyd-dev) [reply src/shims/env.rs:327]: > But is there even any reason that `set_last_error_from_io_error` would take more than an `ErrorKind`?

No, I don't think so. I'm just pointing out an option if that function is not going to be changed as part of this PR.

> Shouldn't we use a custom message indicating that the problem is due to isolation so that user doesn't confuse it with an actual OS error?

The `set_last_error_from_io_error()` function only uses `e.kind()`, so I think the message will be discarded anyway.

Comment (atsmtat) [reply src/shims/env.rs:327]: Ah, I didn't see that. Thanks for pointing out. I guess I can change it to take `ErrorKind`. @RalfJung Do you prefer I do it in this PR?

Comment (RalfJung) [reply src/shims/env.rs:327]: > Do you prefer I do it in this PR?

Yeah I think that would be better. Thanks. :)

Comment (atsmtat) [reply src/shims/env.rs]: Fixed the parameter in a new commit, which I didn't squash as it's independent from the first commit.

Comment (RalfJung) [reply src/shims/env.rs]: Thanks a lot. :)

I think we probably want to change to a different error code, but we can do that later.

**Comment by atsmtat** [comment]
> Thanks a lot @atsmtat for working with me through these many rounds of review. :-)

No problem at all. Thanks for the reviews!

> @bors r+
